### ISSUE TITLE
GameObject positioning

### ISSUE THREAD

**Issue by redfred95** [The-Cataclysm-Preservation-Project/TrinityCore#101]
**Description:**

GameObject does not spawn on your current orientation.

**Current behaviour:**

The GameObject spawns North regardless of your orientation.

**Expected behaviour:**

Should spawn depending on character orientation position, this allows customisation within malls etc.

**Steps to reproduce the problem:**

1. Lookup any GameObject
2. Spawn object.
3. It will spawn facing North.

**TC rev. hash/commit:**
TrinityCore rev. [04b99ab](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/04b99ab8ac2f0730a7e652945daac1c5e5211175)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:**
Linux, Ubuntu 18.0.4

**Comment by Faq** [comment]
give a gob example, what you had in mind when wrote this ticket.

**Comment by redfred95** [comment]
Well it affects every single GameObject ID when spawned but this is the one I used.

204432 - [Lime Crate]

**Comment by Core002** [comment]
can confirm 91c0f13f7709edd778adb7d54e611696f1d22ca0
