### ISSUE TITLE
Show Helm / Show Cloak issue

### ISSUE THREAD

**Issue by redfred95** [The-Cataclysm-Preservation-Project/TrinityCore#102]
**Description:**
Display - > 'Show Helm' + 'Show Cloak'.

**Current behaviour:**
When checking 'Show Helm' or 'Show Cloak' settings to off within the display settings on the next relog it resets to default and shows the cloak again.

**Expected behaviour:**
When checking 'Show Helm' or 'Show Cloak' it should remembers those settings for the next login.

**Steps to reproduce the problem:**
1. Uncheck 'Show Helm' or 'Show Cloak', this will remove the cloak and helmet.
2. Logout and log back in.
3. Helmet & Cloak will be visible again.

**TC rev. hash/commit:**
TrinityCore rev. 04b99ab

**Operating system:**
Linux, Ubuntu 18.0.4

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/94
