### ISSUE TITLE
The Howling Oak - Worgen Quest

### ISSUE THREAD

**Issue by RavenHawkTech** [The-Cataclysm-Preservation-Project/TrinityCore#126]
Gwen is there but I cannot set the hearth stone, and Greymane is not present at all for turning even though the ? is showing he should be, I skipped out of the Worgen Area because I ran into the Warlock Trainer not working, then after learning the spell by leaving and getting back to the area I was able to continue to the point of tossing a TNT Barrel which I could not get to actually throw so I just said forget it and moved on, I went to Darnassus picked up the quest and cannot turn it in, I assume I'm out of phase; but just wanted to make sure. 

CHANGEME Description of the problem or issue here.

See Above Description

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/31

> Issues that wont follow the usual issue template will be closed without comments or warnings.
