### ISSUE TITLE
Issue logging into client with bnetserver

### ISSUE THREAD

**Issue by RavenHawkTech** [The-Cataclysm-Preservation-Project/TrinityCore#127]
Unable to log into client with bnetserver but if I pull and update authserver from 3.3.5 I was able to make it work

CHANGEME Description of the problem or issue here.

Client disconnects after trying to sign in with user account

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

being able to log in with bnetserver.. 

CHANGEME Tell us what should happen instead.

client shows disconnected after login

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

TrinityCore rev. f1c48d35c3c0 2020-06-22 12:31:37 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready

CHANGEME Copy the first line of the `worldserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

TDB 434.20051 CHANGEME Version of the TrinityCore database

Ubuntu 18.04 CHANGEME OS

**Comment by funjoker** [comment]
Master branch is 4.3.4.15595.
No 335 support.

**Comment by RavenHawkTech** [comment]
Did-ja read? I am running 4.3.4 I had to make USE of 3.3.5 authserver cause
bnetserver here is busted.

**Comment by funjoker** [comment]
The bnetserver is working since months on our test server now.

Please make sure you use the patcher correctly.
Don’t use already patched exe and dll.
Patch clean Wow.exe (dll is done automatically) make sure no error appears.
Rename original wow.exe and battle.net.dll to whatever.
Rename patched exe and dll to original naming (wow_patched.exe -> wow.exe)

Also works for x64.

Change config.wtf portal to your server ip 
Don’t use realmlist anywhere!

**Comment by funjoker** [comment]
You can also post the connection.log of your wow

**Comment by RavenHawkTech** [comment]
The connection_patcher on linux fails I can get you the error, however I
have had issues getting Windows to work as the required boost versions
1.65.0 for example when I get boost it shows as 1.65 and that is rejected..

**Comment by funjoker** [comment]
Obviously that the patcher only works for windows and Mac (currently not), since those are the only natively supported systems.

**Comment by RavenHawkTech** [comment]
Ok, I was using the connection patcher to patch wow.exe and that's when I
got the error message I'll collect and send as soon as I'm off work
