### ISSUE TITLE
Connection bnet to world

### ISSUE THREAD

**Issue by Chronaa** [The-Cataclysm-Preservation-Project/TrinityCore#128]
**Description:**

(Maybe just a config mistake by me)
The login to the world (character selection) is like a coin flipp.

**Current behaviour:**

If you try to login and get to the realm select and select your realm and press enter the coin flip starts.
Maybe you get a succes login at the first try and get to the character screen.
But the other option is you get a "logging in" and after that you get back to realm select and need to try again.
This is very annoying cause sometime you need to try it 4-5 times until it let you connect.

**Expected behaviour:**

After you type your login Data it should let you connect at the first try.

**Steps to reproduce the problem:**

1. Type your login data
2. Select your realm
3. And try to login.

**TC rev. hash/commit:** 

Commit: 9bd1cb89708fbd20a35f02d44c803332900d04ea

**TDB version:**  TDB_full_434.20051_2020_05_19

**Operating system:** Debian10

**Comment by Ovahlord** [comment]
That's not an issue. You just have do decrease the realm update interval in the bnetserver config. Unlike the old authserver, bnet is doing its job properly by only letting people logging in when it recognizes the realm as actually online

**Comment by Chronaa** [comment]
RealmStatusUpdateDelay?
I will decrease it Thanks for your replay :)
