### ISSUE TITLE
Druid Flyform can fly in Tol`Barad with portal.

### ISSUE THREAD

**Issue by Chronaa** [The-Cataclysm-Preservation-Project/TrinityCore#129]
**Description:**

If you use the portal while you are in Fly form you can still flying in TolBarad.

**Current behaviour:**

If you enter the portal with your druid in fly form you keep your form and can fly.

**Expected behaviour:**

you should lose your fly form while you use the portal.

**Steps to reproduce the problem:**

1. Go in fly form
2. use the portal to TolBarad.

**TC rev. hash/commit:** 

commit 0820ce33675f15e97c569eca731c98c312949e92

**TDB version:**  TDB_full_434.20051_2020_05_19

**Operating system:** Debian10

**Comment by Ovahlord** [comment]
What custom modification did you add? I tested this case multiple times now and I always get the flight form removed.

**Comment by Chronaa** [comment]
nvm. Im just stupid It works without problems.
