### ISSUE TITLE
Need Clinet...

### ISSUE THREAD

**Issue by Arshiya051** [The-Cataclysm-Preservation-Project/TrinityCore#130]
Hello. I need a game client. The client of this source. Can you give me your client?

**Comment by RavenHawkTech** [comment]
None of the emulator sites provide you the client directly, you can however find some at https://wowmortal.com/download.php

**Comment by funjoker** [comment]
Note: WoW.exe which come from pservers are mostly all patched and won’t work in this project.

But, you can still get the x64 client from blizzard. 
Just google for x64 4.3.4.15595 download and you will find sites linking official download links from blizzard (buffed.de for example)

**Comment by Arshiya051** [comment]
> Note: WoW.exe which come from pservers are mostly all patched and won’t work in this project.
> 
> But, you can still get the x64 client from blizzard.
> Just google for x64 4.3.4.15595 download and you will find sites linking official download links from blizzard (buffed.de for example)

Did you create this source in your client?

Can you upload and send to me?

**Comment by funjoker** [comment]
I will not upload or send a client.
