### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by NiganNi** [The-Cataclysm-Preservation-Project/TrinityCore#131]
Description:

I did everything according to the instructions. I go to the server and create a character. When you try to log on to the server at the end of loading the game crashes with the following message: "Disconnect from server".

Current behaviour:

Does not load characters

Expected behaviour:

Must upload a character

Steps to reproduce the problem:

attached screenshots
![1](https://user-images.githubusercontent.com/61392055/86617454-e6334580-bfbf-11ea-8563-4cbf96822e09.jpg)
![2](https://user-images.githubusercontent.com/61392055/86616903-2ba34300-bfbf-11ea-973e-e235dd1ecae1.jpg)
![3](https://user-images.githubusercontent.com/61392055/86616933-31008d80-bfbf-11ea-9518-93298bc02d01.jpg)

TrinityCore rev. 381d85eba4da 2020-07-02 18:09:16 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

TDB version: TDB_full_434.20051_2020_05_19

Operating system: Windows 10

**Comment by Faq** [comment]
crashlog or other logs?

**Comment by Ovahlord** [comment]
He does not use the correctly patched exe. the 2nd connection couldn't be established so the login just failed.

**Comment by NiganNi** [comment]
Ovahlord this refers to connection_patcher.exe ?
I can't run it already downloaded official clients from different sources, the same writes.
![4](https://user-images.githubusercontent.com/61392055/86619582-8e96d900-bfc3-11ea-8a30-73207de4a6be.jpg)
I understand connection_patcher.exe must build wow.exe?

**Comment by Ovahlord** [comment]
You have to patch a clean wow exe by dragging it on the patcher. That's all.

**Comment by NiganNi** [comment]
Thank you Ovahlord it worked and I got the file. But now instead of a broken connection, the server issues, and at the same download location :
WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 ('Zxcvb') address: 184.23.138.142

I guess it's the auth database?

**Comment by funjoker** [comment]
Did you rename original files and renamed patched files to original naming?

**Comment by NiganNi** [comment]
funjoker no, I didn't rename everything original.

bnetserver logs, perhaps the problem here is in the last line:
```
Using configuration file D:/OSPanel/CataTC_Х3/bnetserver.conf.
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.72.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.7.23
MySQL server ver: 5.7.23-log 
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.7.23
MySQL server ver: 5.7.23-log 
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Listening on connections from worldservers on port 1118...
```
Although creating a character still launches.

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information

**Comment by NiganNi** [comment]
I did everything according to the instructions, i still can't log in to the server.
got Wow-64_Patched.exe and Battle.net-64_Patched.dll -> renamed: Wow-64.exe and Battle.net-64.dll , still getting error loading character: WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 ('Zxcvb') address: 184.23.138.142
Help me understand what the problem is?

logs connection client:
7/8 23:44:23.942  Login program=WoW platform=Wn64 locale=ruRU
7/8 23:44:23.993  Component WoW.Wn64.15595
7/8 23:44:24.026  Component WoW.base.15595
7/8 23:44:24.060  Component WoW.ruRU.15595
7/8 23:44:24.093  Component Tool.Win.0
7/8 23:44:24.160  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/8 23:44:26.455  Failed to resolve eu
7/8 23:44:26.507  GRUNT: state: LOGIN_STATE_FAILED result: DISCONNECTED 
7/8 23:44:26.538  Login program=WoW platform=Wn64 locale=ruRU
7/8 23:44:26.571  Component WoW.Wn64.15595
7/8 23:44:26.604  Component WoW.base.15595
7/8 23:44:26.638  Component WoW.ruRU.15595
7/8 23:44:26.684  Component Tool.Win.0
7/8 23:44:26.728  Client Disconnect due to reason:8

![-11](https://user-images.githubusercontent.com/61392055/87014026-32ef6a00-c1d4-11ea-84eb-3ce0ebf0518b.jpg)
![-1](https://user-images.githubusercontent.com/61392055/87014050-3aaf0e80-c1d4-11ea-9ad5-f0f2570f8430.jpg)

**Comment by NiganNi** [comment]
new client log:
ClientConnection Initiating: COP_LOGIN_CHARACTER code=77
