### ISSUE TITLE
Does not log in to the server

### ISSUE THREAD

**Issue by NiganNi** [The-Cataclysm-Preservation-Project/TrinityCore#134]
Description:

Please do not close until the problem is resolved, did everything according to the instructions:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information
But I still get an error when logging in with a username like: qwerty@qwerty

![-11](https://user-images.githubusercontent.com/61392055/87074399-78895280-c227-11ea-82a2-84270a37465a.jpg)

files .auth are available:
C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\0a\3a\0a3afee2cade3a0e8b458c4b4660104cac7fc50e2ca9bef0d708942e77f15c1d.auth
C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\2e\6D\2E6D53ADAB37A41542B38E01F62CD365EAB8805ED0DE73C307CC6D9D1DFE478C.auth
C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\8f\52\8f52906a2c85b416a595702251570f96d3522f39237603115f2f1ab24962043c.auth
C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\85\1C\851C1D2EF926E9B9A345A460874E65517195129B9E3BDEC7CC77710FA0B1FAD6.auth

I go through Wow-64.exe.
Enter the login type zxcvb@zxcvb

after 5 seconds receive: "Disconnect from server"

I go to the log file:
7/9 20:55:39.820  Login program=WoW platform=Wn64 locale=ruRU
7/9 20:55:39.850  Component WoW.Wn64.15595
7/9 20:55:39.875  Component WoW.base.15595
7/9 20:55:39.900  Component WoW.ruRU.15595
7/9 20:55:39.925  Component Tool.Win.0
7/9 20:55:39.966  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/9 20:55:45.470  Failed to resolve eu
7/9 20:55:45.500  GRUNT: state: LOGIN_STATE_FAILED result: DISCONNECTED 
7/9 20:55:45.527  Login program=WoW platform=Wn64 locale=ruRU
7/9 20:55:45.550  Component WoW.Wn64.15595
7/9 20:55:45.574  Component WoW.base.15595
7/9 20:55:45.599  Component WoW.ruRU.15595
7/9 20:55:45.624  Component Tool.Win.0
7/9 20:55:45.662  Client Disconnect due to reason:8

Current behaviour:
does not enter the world

I have been trying to get to the server for several days and have already tried everything.
What am I doing wrong???

TrinityCore rev. 381d85e 2020-07-02 18:09:16 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

TDB version: TDB_full_434.20051_2020_05_19

Operating system: Windows 10

**Comment by Ovahlord** [comment]
did you use the set portal argument in the config.wtf file?

**Comment by NiganNi** [comment]
Okay I set it up config.wtf :
SET locale "ruRU"
SET portal "217.17.118.60"
SET patchlist "localhost"

The logs of the error has changed:
7/9 21:33:58.648  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/9 21:34:15.121  Login program=WoW platform=Wn64 locale=ruRU
7/9 21:34:15.149  Component WoW.Wn64.15595
7/9 21:34:15.174  Component WoW.base.15595
7/9 21:34:15.199  Component WoW.ruRU.15595
7/9 21:34:15.224  Component Tool.Win.0
7/9 21:34:15.265  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/9 21:34:15.294  Connecting to 217.17.118.60:1119
7/9 21:34:15.498  GRUNT: state: LOGIN_STATE_FAILED result: DISCONNECTED 
7/9 21:34:15.524  Login program=WoW platform=Wn64 locale=ruRU
7/9 21:34:15.549  Component WoW.Wn64.15595
7/9 21:34:15.574  Component WoW.base.15595
7/9 21:34:15.599  Component WoW.ruRU.15595
7/9 21:34:15.624  Component Tool.Win.0
7/9 21:34:15.653  Client initiated Disconnect from 217.17.118.60
7/9 21:34:15.677  Client Disconnect due to reason:8
7/9 21:34:15.700  Client initiated Disconnect from 217.17.118.60

But I still see "Disconnect from server"

**Comment by Ovahlord** [comment]
In that case your firewall settings are probably goofed up. It was able to locate the bnet server on port 1119 so make sure that the firewall is set up for this. You should also delete the realmlist.wtf to be safe because that file is no longer needed.

**Comment by NiganNi** [comment]
But I can already see the world's choice!
Now I have goes in menu choice individual and immediately same throws in the beginning of with message "Disconnect from server"
When you click on the world.

Client logs:
7/9 21:51:12.402  Login program=WoW platform=Wn64 locale=ruRU
7/9 21:51:12.440  Component WoW.Wn64.15595
7/9 21:51:12.459  Component WoW.base.15595
7/9 21:51:12.484  Component WoW.ruRU.15595
7/9 21:51:12.506  Component Tool.Win.0
7/9 21:51:12.542  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/9 21:51:12.568  Connecting to 217.17.118.60:1119
7/9 21:51:13.113  GRUNT: state: LOGIN_STATE_AUTHENTICATED result: LOGIN_OK 
7/9 21:51:13.179  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
7/9 21:51:13.203  GRUNT: state: RESPONSE_CONNECTED result: LOGIN_OK 
7/9 21:51:13.578  ClientConnection Completed: COP_CONNECT code=REALM_LIST_REALM_NOT_FOUND result=FALSE
7/9 21:51:13.611  ClientConnection Completed: COP_CONNECT code=RESPONSE_CANCELLED result=FALSE
7/9 21:51:13.634  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
7/9 21:51:13.861  ClientConnection Completed: COP_CONNECT code=RESPONSE_CONNECTED result=TRUE
7/9 21:51:13.903  ClientConnection Initiating: COP_AUTHENTICATE code=CSTATUS_AUTHENTICATING 
7/9 21:51:14.147  Client initiated Disconnect from 217.17.118.60
7/9 21:51:14.167  GRUNT: state: LOGIN_STATE_DISCONNECTED result: LOGIN_OK 
7/9 21:51:14.192  Login program=WoW platform=Wn64 locale=ruRU
7/9 21:51:14.217  Component WoW.Wn64.15595
7/9 21:51:14.242  Component WoW.base.15595
7/9 21:51:14.267  Component WoW.ruRU.15595
7/9 21:51:14.292  Component Tool.Win.0

Server logs:
WorldSocket::HandleAuthSession: Authentication failed for account: 1 ('1#1') address: 84.53.198.132

**Comment by Ovahlord** [comment]
are the ports  8085 and 8086 also forwarded properly?

**Comment by NiganNi** [comment]
Ovahlord thank you for setting me on the right path. My main problem was that I didn't change it **set portal** argument in the config.wtf

**Comment by iThorgrim-Hub** [comment]
Ok so i have same problem.

Port 1118, 1119, 8085, 8086, 3724 open.
Firewall down
Clean Wow.exe & Battle.net.dll
http://us.media.battle.net.edgesuite.net/downloads/wow-installers/live/WoWLive-64-Win-15595.zip

But disconnected from server when i enter my account logs.

![image](https://user-images.githubusercontent.com/58987080/99840425-d4b49980-2b6c-11eb-96ce-c46916dac9d8.png)
