### ISSUE TITLE
Bnet connection problems

### ISSUE THREAD

**Issue by brussens** [The-Cataclysm-Preservation-Project/TrinityCore#139]
**Description:**

Hello, friends. I just started getting to know 4.3.4 a few days ago, so please don't swear too much.

In general, the situation is such that we decided to make a server with a friend to look at the patch, but there were problems with bnet.
1. When connecting through a patched client, an error occurs that some component (Tool Win) is not found, and this components build can be different (for me is 2756, for friend is 2736) , depending on the pc, although the same copied client is used.
At the moment, we managed to avoid this problem by slightly changing the code (I believe that Component.Build == 0 means any value).
ComponentManager.cpp line 51:
```cpp
if (component->Program == c->Program && component->Platform == c->Platform && component->Build == c->Build)
```
Replaced by this.
```cpp
if (component->Program == c->Program && component->Platform == c->Platform && (component->Build == c->Build || c->Build == 0))
```
2. The current wow.exe can be used normally, only on the local pc, I couldn't pass it to a friend, because there is no connection error at the stage of ProofResponse (Wrong module) and the client interrupts connection.

These problems appear on both x32 and x64.
Can you tell me if these are really problems, or am I doing something wrong?

P.S.: ruRU client

**Current behaviour:**

1. Client version error
2. Connection error

**Expected behaviour:**

Connection ok

**Steps to reproduce the problem:**

1. Create bnet account
2. Launch ruRU client
3. Try connect

**TC rev. hash/commit:** 

rev. 29e64980d8ee 2020-07-08 00:03:26 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  TDB 434.20051

**Operating system:** Win 10 Pro x64 / Debian 10.4 x64

**Comment by Ovahlord** [comment]
You have fucked up the client patching then. You have to patch a clean exe. The ones that private servers use are not clean.

**Comment by brussens** [comment]
It was a clean exe and original client that I used, however, the error is evident. Anyway, thank you for some feedback.

**Comment by funjoker** [comment]
Can you please give me the Connection log from the client.

**Comment by brussens** [comment]
After I downloaded the modules in the next repo and put them next to connection_patcher.exe, everything started to work fine. However, having forwarded the patched exe to a friend, he gets a connection error.

```
7/12 12:17:17.097  Login program=WoW platform=Wn64 locale=ruRU
7/12 12:17:17.130  Component WoW.Wn64.15595
7/12 12:17:17.163  Component WoW.base.15595
7/12 12:17:17.197  Component WoW.ruRU.15595
7/12 12:17:17.230  Component Tool.Win.0
7/12 12:17:17.280  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
7/12 12:17:17.317  Connecting to 127.0.0.1:1119
7/12 12:17:17.531  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
7/12 12:17:17.572  Disconnected from 127.0.0.1
7/12 12:17:17.607  Client initiated Disconnect from 127.0.0.1
7/12 12:17:17.640  Client initiated Disconnect from 127.0.0.1
7/12 12:17:17.674  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
7/12 12:17:17.706  Login program=WoW platform=Wn64 locale=ruRU
7/12 12:17:17.777  Component WoW.Wn64.15595
7/12 12:17:17.799  Component WoW.base.15595
7/12 12:17:17.826  Component WoW.ruRU.15595
7/12 12:17:17.849  Component Tool.Win.0
```

**Comment by funjoker** [comment]
@brussens he needs the patched .auth files too

**Comment by brussens** [comment]
@funjoker I understand correctly that `.auth` files must be located in `ProgramData/Blizzard Entertainment/Battle.net`?
I suppose it should be unpacked there as `ProgramData/Blizzard Entertainment/Battle.net/Windows/x64/0a3afee2cade3a0e8b458c4b4660104cac7fc50e2ca9bef0d708942e7f15c1d.auth`, right?

**Comment by brussens** [comment]
@funjoker thanks man! I think I figured it out.
