### ISSUE TITLE
[DEV] Warrior Class Trainer Table

### ISSUE THREAD

**Issue by funjoker** [The-Cataclysm-Preservation-Project/TrinityCore#143]
Here we will check one by one.
Missing stuff will be added and existing stuff will be verified.

**TrainerId: 145 = Starting Zone Trainer
TrainerId: 16 = All Spells**

| entry | name | gossip_menu_id | OptionIndex | TrainerId | State |
| ------ | ----- | ------- | ------ | --------- | ------ | 
| 911 | Llane Beshere (A) | 4650 | 0 | 145 | ✔️|
| 912 | Thran Khorman (A) | 4684 | 0 | 145 | ✔️|
| 913 | Lyria Du Lac (A) | 4649 | 0 | 16 | ✔️ |
| 914 | Ander Germaine (A) | 4475 | 0 | 16 | ✔️|
| 985 | Malosh (H) | 523 | 0 | 145 | ❓|
| 1229 | Granis Swiftaxe (A)  | 4683 | 0 | 16 | ✔️|
| 1403 | Mogwah (H) | 0 | (NULL) | (NULL) | ❓ |
| 1901 | Kelstrum Stonebreaker (A) | 4569 | 0 | 16 | ✔️|
| 2119 | Dannal Stern (H) | 4653 | 0 | 145 ✔️ | ❓|
| 2131 | Austil de Mon (H) | 656 | 0 | 16 ✔️| ❓|
| 3041 | Torm Ragetotem (H) | 4526 | (NULL) | (NULL) -> 16 | ❓|
| 3042 | Sark Ragetotem (H) | 4525 | (NULL) | (NULL) -> 16 | ❓|
| 3043 | Ker Ragetotem (H) | 4527 | (NULL) | (NULL) -> 16 | ❓|
| 3059 | Harutt Thunderhorn (H)| 4645 | 0 | 145 ✔️ | ❓|
| 3063 | Krang Stonehoof (H) | 655 | 0 | 16 ✔️ | ❓|
| 3153 | Frang (H)| 523 | 0 | 145 ✔️ | ❓|
| 3169 | Tarshaw Jaggedscar (H) | 523 | 0 | 145 ✔️ | ❓|
| 3353 | Grezz Ragefist (H) | 4509 | 0 | 16 ✔️ | ❓|
| 3354 | Sorek (H) | 4511 | 0 | 16 ✔️ | ❓|
| 3408 | Zel'mak (H) | 655 | 0 | 16 ✔️ | ❓|
| 3593 | Alyissia (A)| 4696 | 0 | 145 | ✔️ |
| 3598 | Kyra Windblade (A) | 4697 | 0 | 16 | ✔️ |
| 4087 | Arias'ta Bladesinger (A) | 4581 | 0 | 16 | ✔️ |
| 4089 | Sildanair (A) | 4578 | 0 | 16 | ✔️ |
| 4593 | Christoph Walker (H) | 0 | (NULL) | (NULL) -> 16  | ❓|
| 4594 | Angela Curthas (H) | 0 | (NULL) | (NULL) -> 16 | ❓|
| 4595 | Baltus Fowler (H) | 0 | (NULL) | (NULL) -> 16  | ❓|
| 5113 | Kelv Sternhammer (A) | 4570 | 0 | 16 | ✔️ |
| 5114 | Bilban Tosslespanner (A) | 4568 | 0 | 16 | ✔️ |
| 5479 | Wu Shen (A) | 4482 | 0 | 16 | ✔️|
| 5480 | Ilsa Corbin (A) | 4481 | 0 | 16 | ✔️ |
| 7315 | Darnath Bladesinger (A) | 4579 | 0 | 16 | ✔️ |
| 8141 | Captain Evencane (A) | 4091 | 0 | 16 | ✔️ |
| 10291 | Krysteea | 0 | (NULL) | (NULL) | ❓|
| 16503 | Kore (A)| 7263❓ | (NULL) | (NULL) -> 145 | ❓|
| 16771 | Ahonan (A) | 7263❓ | (NULL) | (NULL) -> 16 | ❓ |
| 17120 | Behomat (A)| 7263❓ | (NULL) | (NULL) -> 16 | ❓|
| 17480 | Ruada (A)| 7263❓ | (NULL) | (NULL) -> 16 | ❓|
| 17504 | Kazi (A) | 7263❓ | (NULL) | (NULL) -> 16 | ❓|
| 34697 | Warrior-Matic NX-01 (H) | 10821 | 0 | 145 ✔️ | ❓|
| 35807 | Warrior-Matic NX-01 (H) | 10555 | 0 | 16 ✔️| ❓|
| 35839 | Sergeant Cleese (A)  | 10694 | 1 | 16 | ❓ |
| 35839 | Sergeant Cleese (A)  | 10694 | 0 | 145 | ❓ |
| 36525 | Warrior-Matic NX-01 (H) | 10555 | 0 | 16 ✔️ | ❓ |
| 36651 | Sergeant Cleese (A) | 10836 | 0 | 16 ✔️ | ❓|
| 38037 | Nortet (H) | 10977 | 0 | 145 ✔️ | ❓|
| 38518 | Warrior-Matic NX-01 (H) | 11052 | (NULL) | (NULL) -> 16 | ❓|
| 38793 | Sergeant Cleese (A) | 10836 | 0 | 16 ✔️ | ❓|
| 42324 | Drill Sergeant Steamcrank (A)| 0 | (NULL) | (NULL) -> 145 | ❓|
| 43009 | Alsudar the Bastion (H) | 14199 | 0 | 16 ✔️ | ❓|
| 43010 | Delios Silverblade (H) | 11793 | 0 | 16 ❌❓ | ❓|
| 43012 | Lothan Silverblade (H) | 11793 | 0 | 16 ✔️ | ❓ |
| 44128 | Sarithra (H) | 14199 | 0 | 16 ✔️ | ❓|
| 44129 | Beldis (H) | 14199 | 0 | 16 ✔️ | ❓|
| 44455 | Sergeant Cleese (A)| 10694 | 1 | 16 | ❓|
| 44455 | Sergeant Cleese (A)| 10694 | 0 | 145 | ❓|
| 44723 | Nahu Ragehoof (H) | 11875 | 0 | 16 ✔️ | ❓|
| 45019 | Berserker Zanga (H) | 11912 | 0 | 16 ✔️ | ❓|
| 45709 | Bruiser Janx (H) | 12344 | 0 | 16 ✔️ | ❓|
| 46667 | Blademaster Ronakada (H) | 12151 | 0 | 16 ✔️ | ❓ |
| 48616 | Karla Fain (H)| 656 | 0 | 16 ✔️| ❓|
| 49720 | Eugene Daller (H)| 656 | 0 | 16 ✔️| ❓|
| 49736 | Kallen Stanner (A) | 12513 | (NULL) | (NULL) -> 16 | ❓|
| 49781 | Grendin Swiftaxe (A) | 12523 | 0 | 16 ✔️ | ❓|
| 49902 | Warrior-Matic NX-01 (H) | 12532 | (NULL) | (NULL) -> 16 | ❓|
| 49923 | Sentinel Moonwing (A) | 12533 | (NULL) | (NULL) -> 16 | ❓|
| 49955 | Leonic Truehair (H) | 0 | (NULL) | (NULL)  -> 16 | ❓|
| 49961 | Viik (A) | 7263 | (NULL) | (NULL)  -> 16 | ❓|
| 50006 | Yeniss (H) | 11912 | 0 | 16 ✔️ | ❓|
| 50018 | Tarlhir (A H) | 12925 | (NULL) | (NULL) -> 16 | ❓ |
| 50025 | Bratu (A H) | 7263 | (NULL) | (NULL) -> 16| ❓|
| 50033 | Ging (H) | 523 | 0 | 145 ❌ -> 16 | ❓|
| 50149 | Vinsun (H) | 11793 | 0 | 16 ✔️ | ❓|
| 50155 | Naseev (A) | 12533 | (NULL) | (NULL) -> 16 | ❓|
| 50500 | Sergeant Cleese | 12513 | (NULL) | (NULL) -> 16 | ❓|

**Comment by PhaenQ** [comment]
Are these changes being made on the world.creature_default_trainer table? or is there a .DBC or simmilar external that controls this list. I note that I could find no class trainers in the world.creature_default_trainer table and tried adding an entry of [3041, 16] to that table then deleted my cache, but without success. 

Sorry if this is the wrong spot for this, if there is a better place please direct me there. Thanks again.
