### ISSUE TITLE
DB/Quest: The Power of the Light (Paladin starting quest)

### ISSUE THREAD

**Issue by TranceAccount** [The-Cataclysm-Preservation-Project/TrinityCore#163]
**Description:**

The quest The Power of the Light does not work. This is the first Paladin class quest, and after using Judgement, no credit is registered. Also, no credit is registered of learning the spell Judgement.

I am also generally confused by the use of the amount of different tables for quests, e.g. `quest_offer_reward`, `quest_request_items`, `quest_template`, etc..

**Current behaviour:**

The quest is uncompletable:
- When learning the spell Judgement from the Paladin trainer, the credit is not registered.
- When using the spell Judgement on the training dummies, the credit is not registered

Also the progress text is missing of the quest:
![Figure](https://user-images.githubusercontent.com/13118481/89181718-8d41d780-d594-11ea-8c12-5e192ee7b5df.png)

**Expected behaviour:**

https://www.wowhead.com/quest=26918/the-power-of-the-light

- Credit for learning should be given out when the spell Judgement is learned from the Paladin trainer.
- Credit for using the Judgement spell on the Training Dummies is not registered.
- Progress text should be available.

**Steps to reproduce the problem:**

1. Create Paladin.
2. Finish first two quests or get to level 3.
3. Get the quest The Power of the Light (ID = 26918)
4. Talk to trainer about quest and notice no text.
5. Train the required spells, and notice no credit for the Judgement spell.
6. Go to training dummies and cast the Seal and then Judgement on the dummy. Notice not credit.

**TC rev. hash/commit:** 

TrinityCore rev. e57ec6597329 2020-07-29 23:03:02 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  

TDB 434.20051

**Operating system:** 

Windows 10 Home

**Fix for quest progress text and reward text:**

```sql
DELETE FROM `quest_offer_reward` WHERE `ID` = 26918; -- The Power of the Light
INSERT INTO `quest_offer_reward` (`ID`, `RewardText`) VALUES
(26918, "You\'re a quick learner, $N. Return to me as you grow stronger and I\'ll teach you more about using the Light to vanquish your enemies and strengthen your allies.");

DELETE FROM `quest_request_items` WHERE `ID` = 26918; -- The Power of the Light
INSERT INTO `quest_request_items` (`ID`, `CompletionText`) VALUES
(26918, "Well, did you give it a try?");
```

**Comment by huaijiuwow** [comment]
I meet the same issue，how to fix it?pro
