### ISSUE TITLE
DB/Quest: Lou's Parting Thoughts

### ISSUE THREAD

**Issue by TranceAccount** [The-Cataclysm-Preservation-Project/TrinityCore#172]
**Description:**

The quest Lou's Parting Thoughts does not work. The Thugs spawned do not start their gossip nor do they do anything than just standing there.

**Current behaviour:**

Nothing happens.

![WoWScrnShot_081920_163516](https://user-images.githubusercontent.com/13118481/90648652-16fecf80-e23a-11ea-85ff-fd1559b719ff.jpg)

**Expected behaviour:**

Gossip should start when approaching the Thugs and afterwards they may start attacking you.

https://www.youtube.com/watch?v=fKnXDN2EC4Q

**Steps to reproduce the problem:**

1. `.q add 26232`
2. `.go cr id 42387`
3. Move around a bit and observe no gossip starting.

**TC rev. hash/commit:** 

TrinityCore rev. f1bbb7fa64f3 2020-08-09 21:15:59 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  

TDB 434.20051

**Operating system:**

Windows 10 Home

**Comment by Nyr97** [comment]
This has already been fixed by @funjoker on recent fixes for Westfall.

**Comment by TranceAccount** [comment]
Thanks for the update. Closing this issue then.
