### ISSUE TITLE
Means of communication.

### ISSUE THREAD

**Issue by pangolp** [The-Cataclysm-Preservation-Project/TrinityCore#175]
Hello, good evening. I'm sorry I deleted the format of the issue, but I just wanted to know if you have a discord or any means of communication. I'm currently part of the AzerothCore community, try to collaborate with Skyfire. I have some knowledge, although I need to learn more, but I wanted to know how to contact you so you can tell me more about the project and see if I can contribute with you.

I appreciate any information on this. Without further reason and waiting for your response. Say hello Atte. Pagani Walter.

PS. I use a translator to write.
My native language is Spanish.

**Comment by Ovahlord** [comment]
There is no need for further communication. You have a fix, PR it, if it's fine, it gets merged, if not, it gets rejected. Simple as that.

**Comment by TranceAccount** [comment]
Trinitycore has a discord with a subchannel 434, maybe you can ask some questions there? I am not using discord tho.

**Comment by pangolp** [comment]
@Ovahlord It was not the answer I expected, but thanks and good luck with the project.
