### ISSUE TITLE
Movement State Root - Enter Combat

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#183]
**Description:**
Creatures do not enter into combat when they are in the Rooted state, they can be attacked but do not attack and regenerate their health

**Expected behaviour:**

When a Creature is in a rooted state, it should be able to enter combat and attack

**Steps to reproduce the problem:**

1. Choose a creature and insert rooted state in Creature_template_movement.
2. Perform auto attacks on the creature

**TC rev. hash/commit:** 
a6a1c619f5e0d00d070e514289c9152671124496

**TDB version:**  TDB 434.20091

**Operating system:** Windows 10 - 64 bits

**Comment by Ovahlord** [comment]
please be a bit more explicit and provide an example creature

**Comment by DevPrimeR** [comment]
Example:
https://www.wowhead.com/npc=54995/icy-tomb

When inserting the creature template movement:

```DELETE FROM `creature_template_movement` WHERE `CreatureId` = '54995';
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Random`) VALUES
('54995','0','0','0','1','0');```
It automatically regenerates its health or when adding it to any other entity that does not have a defined example Script: 54600

**Comment by DevPrimeR** [comment]
Rooted:
![2](https://user-images.githubusercontent.com/10391503/94978959-b673db00-04e5-11eb-9bcb-a58270fb4073.png)

No rooted:
![1](https://user-images.githubusercontent.com/10391503/94978962-ba9ff880-04e5-11eb-89ea-c2298211c7d4.png)

**Comment by Ovahlord** [comment]
Most of your problems do originate from the script itself. The npc_ice_tomb script is outdated because it uses ScriptedAI while it should use NullCreatureAI so it should not trigger aggro mechanics at all.

**Comment by DevPrimeR** [comment]
Thanks, I'll check it
