### ISSUE TITLE
DB/NPC: Brother Paxton is not casting his abilities

### ISSUE THREAD

**Issue by TQPS** [The-Cataclysm-Preservation-Project/TrinityCore#184]
**Description:**

Brother Paxton (Located in Northernshire Valley) should be casting either "Prayer of Healing" or "Renew" on surrounding soldiers fighting worgs.

https://www.wowhead.com/npc=951/brother-paxton

**Current behaviour:**

Currently he is pathing, and gossips are working, however, he is not casting anything.

**Expected behaviour:**

When he gossips, he is supposed to cast either:

https://www.wowhead.com/spell=93091/prayer-of-healing
or
https://www.wowhead.com/spell=93094/renew

**Steps to reproduce the problem:**

1. Create a human character (so as to start in Northshire)  
2. Run on over to 48.6, 38.0
3. Observe

<details>

![image](https://user-images.githubusercontent.com/66294837/95004224-21cbc300-0634-11eb-8b38-4ff8a4c4f41a.png)

</details>

**TC rev. hash/commit:** 

TrinityCore rev. 973d4a139a83 2020-10-01 22:20:29 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** TDB 434.20091

**Operating system:** Windows 7 64Bit

**Comment by Ovahlord** [comment]
Brother Paxton actually does cast his abilities. However, he does not always cast them when responding to the soldiers as this is blizzlike behavior. There is a cooldown between his ability casts so in some cases he just responds but keeps walking.
