### ISSUE TITLE
End TIme - Murozond ID 54432

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#186]
**Description:**
After killing the NPCs in the Murozond area, he should descend to start the fight

![Sin título](https://user-images.githubusercontent.com/10391503/96794038-12ce6a00-13c3-11eb-9633-ecb99c943026.png)

**Steps to reproduce the problem:**

* Enter the instance
* use the portal
* use .gm off
* kill Npc
* Murozond does nothing

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/90e5e85afd4706138e852e6aebedff3aff01061d

**TDB version:** TDB 434.20091

**Operating system:** Windows 10 x 64 bits

**Comment by Ovahlord** [comment]
Please stop posting your private server issues in my tracker because obviously you are using custom scripts and fucked up my scripts in the process.

![WoWScrnShot_102220_083815](https://user-images.githubusercontent.com/18347559/96834229-f1609300-1441-11eb-824c-64b5108cfe50.jpg)
