### ISSUE TITLE
SMSG_BATTLEFIELD_LIST

### ISSUE THREAD

**Issue by Warpten** [The-Cataclysm-Preservation-Project/TrinityCore#188]
Going awol for a few days/weeks again.

To answer your IRC DM:

* that bit is unused.
* You're missing two `uint8` after the initial `(u)int32` block, being `listLevelRangeMax` and `listLevelRangeMin`

```diff
 WorldPacket const* WorldPackets::Battleground::BattlefieldList::Write()
 {
     _worldPacket << int32(CurrencyHonorBonusHolidayWin);
+    _worldPacket << uint8(listLevelRangeMax);
+    _worldPacket << uint8(listLevelRangeMin);
```

Although while assigned to globals they don't seem used anywhere.

**Comment by Ovahlord** [comment]
4c8fe1c08e82aaa6b1e729aed7f22dfe6ff0db15 yeah, noticed that when I compared the core packet values with sniff ones. It's in there by then
