### ISSUE TITLE
vmap4extractor doesnt work

### ISSUE THREAD

**Issue by doffylarsen434** [The-Cataclysm-Preservation-Project/TrinityCore#189]
**Description:**
trying to use the vmap4extractor and doesnt work i tryed a full 434 client and need help please

**Comment by Ovahlord** [comment]
Use the issue template and provide all the information for it please, otherwise the issue with be closed.
[Read before posting Issues](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/31)

**Comment by doffylarsen434** [comment]
Like what it says in the vmap4extractor

**Comment by doffylarsen434** [comment]
ttp://TrinityCore.org                    \/__/

Extract V4.05 2018_03. Beginning work ....

Loading common MPQ files
Loaded Data\art.MPQ
Loaded Data\expansion1.MPQ
Loaded Data\expansion2.MPQ
Loaded Data\expansion3.MPQ
Loaded Data\world2.MPQ
Loaded Data\wow-update-base-15211.MPQ
Loaded Data\wow-update-base-15354.MPQ
Loaded Data\wow-update-base-15595.MPQ

Loading enGB locale MPQs

Detected and using locale: enGB
Extracting GameObject models...Can't open World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2, err=2!
Can't open World\Detail\Drkbus02.m2, err=2!
Can't open World\Detail\Drkbus04.m2, err=2!

**Comment by Ovahlord** [comment]
These errors are normal and these are models that are not suposed to be extracted and do not prevent the extraction. Just let it do its job.

**Comment by doffylarsen434** [comment]
so i just let it run :D
