### ISSUE TITLE
bnetserver can't connect 

### ISSUE THREAD

**Issue by doffylarsen434** [The-Cataclysm-Preservation-Project/TrinityCore#190]
**Description:**
i made account and try to login using full 4.3.4 client used connection patcher.
i came to authentiacte and just got stuck there and cant come to characters and create one any clue?
CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**TC rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS
windows 10

**Comment by Ovahlord** [comment]
You cannot use private server game clients because we need a original wow exe file and a clean bnet.dll. All downloads from private servers are patched already and can NOT be used.

**Comment by doffylarsen434** [comment]
so where do i find a clean wow.exe

**Comment by Ovahlord** [comment]
Internet. We are not allowed to share any copyrighted files due to obvious reasons. You're on your own with that.

**Comment by doffylarsen434** [comment]
Ah ok


man. 9. nov. 2020 kl. 00:44 skrev Ovah <notifications@github.com>:
