### ISSUE TITLE
Impossible to connect on port 1119

### ISSUE THREAD

**Issue by iThorgrim-Hub** [The-Cataclysm-Preservation-Project/TrinityCore#191]
**Description:**

Disconnect when client try to connect on 127.0.0.1:1119 with the x64Bits client.
I have no problem with x32Bit client.

**Current behaviour:**
```
11/20 20:49:22.510  Login program=WoW platform=Wn64 locale=frFR
11/20 20:49:22.510  Component WoW.Wn64.15595
11/20 20:49:22.516  Component WoW.base.15595
11/20 20:49:22.516  Component WoW.frFR.15595
11/20 20:49:22.516  Component Tool.Win.0
11/20 20:49:22.538  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
11/20 20:49:22.546  Connecting to 127.0.0.1:1119
11/20 20:49:22.675  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
11/20 20:49:22.675  Client initiated Disconnect from 127.0.0.1
11/20 20:49:22.675  Client initiated Disconnect from 127.0.0.1
11/20 20:49:22.692  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
11/20 20:49:22.692  Login program=WoW platform=Wn64 locale=frFR
11/20 20:49:22.692  Component WoW.Wn64.15595
11/20 20:49:22.692  Component WoW.base.15595
11/20 20:49:22.692  Component WoW.frFR.15595
11/20 20:49:22.702  Component Tool.Win.0
```
Port 1118, 1119, 8085, 8086, 3724 open.
Firewall shutdown

Clean Wow.exe & Battle.net.dll
http://us.media.battle.net.edgesuite.net/downloads/wow-installers/live/WoWLive-64-Win-15595.zip

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/2075879183a364bcdcb86c7cdf7c4663a9bdb42e

**TDB version:** 
TDB 434.20091

**Operating system:**
Windows 10

**Comment by Ovahlord** [comment]
The clean client fields are just the first step. You have to patch them with our connection patcher and make sure that the auth module in ProgramData/Blizzard Entertainment/Cache/ is present and patched.

The reason for that is that we use the 2nd worldsocket connection that needs the patched auth module to properly authenticate with emulators.

**Comment by iThorgrim-Hub** [comment]
> The clean client fields are just the first step. You have to patch them with our connection patcher and make sure that the auth module in ProgramData/Blizzard Entertainment/Cache/ is present and patched.
> 
> The reason for that is that we use the 2nd worldsocket connection that needs the patched auth module to properly authenticate with emulators.

Yes with 362Bits version it's nive not with the x64, i have already download authModules repositories but nothing change, In x32bits client work with x64Bits client not work :(

**Comment by BlackMetalz** [comment]
Work with 64 bit. Follow the tutorial here
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information

**Comment by iThorgrim-Hub** [comment]
I have already followed the tutorial, I have no problems with the 32Bits version but with the 64Bits version I can't connect.
I did add the AuthModules in my Blizzard Entertainment files but it doesn't seem to make any difference :-/

**Comment by azure-hu** [comment]
For me the x86 and the x64 version not working. Not sure if it's a server issue. I try to login with the email which had been registered with bnetaccount command. The client displays "Connecting" for some seconds, later "You have been disconnected from the server". Either bnetserver and worldserver running, neither console displays login attempts. What am I doing wrong?

**Comment by funjoker** [comment]
1. Check https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information

Some thoughts here:
1. Get a Clean Wow.exe and a clean Battle.net.ll (4.3.4.15595) and/or Wow-43.exe and Battle-64.net.dll
2. Drag Wow.exe and/or Wow-64.exe on connection_patcher
3. Check log if everything worked
4. Rename the existing Wow.exe and a clean Battle.net.ll and/or Wow-43.exe and Battle-64.net.dll OR move them to another folder
5. Rename the Wow_patched.exe and the Battle.net_patched.dll and/or the Wow-64_patched.exe and Battle-64.net_patched.dll
to:
Wow.exe
Battle.net.dll
Wow-64.exe
Battle-64.net.dll
6. If you have a Launcher.exe, rename it into something else (e.g. Launcher-Backup.exe)

**Comment by funjoker** [comment]
If log says:
1. `GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK `

but then 

2. `GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED `

This mostly means, that the patcher did not create the patched .auth modules OR you are simply missing them, because you just shared the exe and the dll, but not the .auth files


If log says:
`Component Tool.Win.2756 or Component Tool.Win.2736`

you did not rename or remove the Launcher.exe

**Comment by azure-hu** [comment]
Sorry, ignore me, my problem was only a missing "SET portal" from config.wtf.
