### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by iThorgrim-Hub** [The-Cataclysm-Preservation-Project/TrinityCore#192]
To attract more developers I think it would be a good idea to add features to this project which clearly deserves much more support!

- AzerothCore's module system
- Upgrade ElunaTrinityCata with this project
- Rework the Wiki and propose a much more intuitive and complete tutorial
- Set up a docker configuration
- Create a Discord for more direct Support
- Create a ready-to-use repack when major Core and DB updates
   - A repack that could be shared on sites such as AC-Web etc.

**Comment by Ovahlord** [comment]
So let's start with the ugly part: AzerothCore. Long story short: it's not going to happen. We stay as close as possible to the original TrinityCore structure for the sake of compatability and also AzerothCore is filled with hacks that we do not want to find their way in here. A good amount of private server people only see the gains from it but the technical background of AzerothCore is that it's just one giant abomination that's already falling apart.

Same goes with Eluna. Great for beginners and casual code kiddos but the effort it takes to port and maintain it when more major TrinityCore updates are being merged just makes things too big for our limited development capacities.

Next one: the wiki: Would you elaborate further on what steps are not clear?
It's really just these three steps:
1. Get a clean client
2. Run the connection patcher on the clean exe files
3. Drop the original files and replace them with the patched ones. Done.

**Comment by funjoker** [comment]
Also TrinityCore Wiki works here too

**Comment by iThorgrim-Hub** [comment]
> So let's start with the ugly part: AzerothCore. Long story short: it's not going to happen. We stay as close as possible to the original TrinityCore structure for the sake of compatability and also AzerothCore is filled with hacks that we do not want to find their way in here. A good amount of private server people only see the gains from it but the technical background of AzerothCore is that it's just one giant abomination that's already falling apart.

For the main lines I agree, but the module system is something that remains very interesting for the deployment of custom functionalities.
It also avoids developers having to review all their code every time you update your emulator.
AzerothCore understands this, Ashamane understands this, and other fork of emulators get this system too.

> Same goes with Eluna. Great for beginners and casual code kiddos but the effort it takes to port and maintain it when more major TrinityCore updates are being merged just makes things too big for our limited development capacities.

That's not true Eluna is not just for Code Lovers, just because you don't use the Lua doesn't mean it's the case.
The biggest demand for the new Core is precisely an Eluna update, which allows fast code reading without having to reboot.

TrinityCore also has it for C++ scripts, but it's horrible and subject to limitation.

> Next one: the wiki: Would you elaborate further on what steps are not clear?
3 Steps certainly, but it doesn't work anymore when we want to allow players to play with us.

I did the test yesterday with some players and computers connected in 4G, each player must patch the client himself.
How do you want to attract developers if even coming from testers is a challenge?

The goal is not to give a moral lesson or anything but to give some food for thought to try to attract a little more developers.

Even if the procedure is 3 steps, putting pictures is always nice. You won't be able to attract developers by hiding the page to make the client work.

Currently to join the project you have to clone the repo, go to the TrinityCore wiki and follow the TrinityCore Wiki (very good).
To understand how to patch the client we don't look on your Github but on the TrinityCore Wiki because the steps to build the server are on the TrinityCore Wiki.

Highlighting the link that explains how to patch the client seems to be a good idea.
I think simply modifying the ReadMe to explain that the steps for creating the server are on the TrinityCore wIki but the steps for patching the client are on this Github would be a good start.
Rename the "Information" page also to "How to Patch the Client".

Tomorrow if I see an information page I don't necessarily think that this page contains the most important part to join my project, but more information about the project itself (Logic, Information doesn't mean Tutorial).

**Comment by Faq** [comment]
You can start by opening PR for wiki update as you went over all the steps to get it working you should have a good view how it should look better.

**Comment by Mesielecat** [comment]
Well Eluna, not is neccesary with Dynamic Linking, Eluna use the main implementation in the core if the core have any problem a specific hook in Eluna don´t gonna work well, soo why lose the time with Eluna if you can use Dynamic Linking? The only part where Eluna was well for me, was the fast code without reboot, but since the implementation of the Dynamic Linking I have all the power of the C++ in my hands for script and for review. Soo remove the part of the Eluna.
