### ISSUE TITLE
Interrupt Cast GCD not resetting

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#198]
**Description:**

When interrupting a cast aka "fake casting" the Global Cooldown will not reset and you have to wait a for the Global Cooldown to finish before being able to cast again.

This happens when interrupting the cast by:
- /stopcasting
- moving forward
- moving backwards

The mechanic works fine when moving to the right/left (see video).

**Expected behaviour:**

When you interrupt a cast, you should be able to cast a spell immediately after. As displayed when moving to the right/left.

**Steps to reproduce the problem:**

https://streamable.com/n20ndn

**TC rev. hash/commit:** 

c8d37293e81113a09d4944c88e8406f159ca1e34

**TDB version:**

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Ovahlord** [comment]
Please add official information material about this behaivior so I can dig into research

**Comment by lingxDEV** [comment]
Do some research on the term fake casting. 

https://www.youtube.com/watch?v=UtxK1ggaWFw
https://www.youtube.com/watch?v=jhT3d5fn00U

It should be pretty clear that what I described is a bug, as it's partially working (when moving from side to side).

You want the same behaviour that happens when moving from side to side (GCD is reset and you can cast a new spell instantly) to also apply to when moving forward, backwards, jump or doing /stopcasting.

**Comment by Ovahlord** [comment]
5c882e8788b87fe885f4e0d49b307920a2ce798e
