### ISSUE TITLE
Casting while moving to the side

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#199]
**Description:**

You are able to cast while moving a a few steps to the side.

**Current behaviour:**

While casting you can move to a tiny bit to the side. 

**Expected behaviour:**

Cast should be interrupted on all movement.

**Steps to reproduce the problem:**

https://streamable.com/ay6rkt

**TC rev. hash/commit:** 

c8d37293e81113a09d4944c88e8406f159ca1e34

**TDB version:**

TDB 434.20091

**Operating system:**

Win10 64

**Comment by Ovahlord** [comment]
does not happen anymore
