### ISSUE TITLE
Player Frame Aggro Indicator

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#203]
**Description:**

The player frame aggro indicator can keep showing after killing a mob.

**Current behaviour:**

When you kill a mob instantly, in "one shot", the player frame aggro indicator will not show and never disappear.

**Expected behaviour:**

The player frame aggro indicator should only show when the player has aggro on a mob.

**Steps to reproduce the problem:**

1. Kill a mob in one hit.
2. See that the aggro indicator will not disappear.

Video: https://streamable.com/5ge0wy

**TC rev. hash/commit:** 

5c0febcfb38828a28da9edd27900a85e052cc738

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Ovahlord** [comment]
Clientbug, so cannot be fixed in a serverside way. When a unit gets engaged and killed at the same moment, the client ignores the threat clear packet so the unit keeps its threat value while the server told the client to clear it.

**Comment by Faq** [comment]
If thats blizzlike client bug, why not closed?
