### ISSUE TITLE
Animation tier implementation

### ISSUE THREAD

**Issue by Warpten** [The-Cataclysm-Preservation-Project/TrinityCore#21]
Currently going through the code and fixing animation tiers, couple questions

- `boss_nefarians_end`:
You manually set `MOVEMENTFLAG_DISABLE_GRAVITY` after the intro has been run once (so, basically, on wipes). Why not call `Unit::SetDisableGravity(true)` ? Are there no spline packets sent for gravity toggle on Nefarian? If that's the case, document, because it could be that you just don't get the packet because Nefarian is already up in the air when you reenter the instance (iirc, Nefarian despawns on wipe ?)

- Dragha shadowburner
When dismounting his stupid drake, why do you set the animation tier to `ToGround` **before** and **after** you toggle on gravity, and hover off?

```
me->SendMovementSetSplineAnim(Movement::AnimType::ToGround);
me->SetDisableGravity(false);
me->SetHover(false);
me->SendMovementSetSplineAnim(Movement::AnimType::ToGround);
```

One of those can't be right.

Nitpick that you can't do anything about: the fact that one method is called `SetDisableGravity` but the other is `IsLevitating` is pissing me off.

**Comment by Ovahlord** [comment]
There are no disable gravity spline packets sent at the beginning. Also the anim tier sending is based on sniffs. The sniff sends them twice in this order as well. I was confused about this as well. Will investigate later again.

**Comment by Warpten** [comment]
Nefarian: OK

Dragha: OK, but then i have a subsidiary question: is there a similar situation with Sindragosa's phase transitions? That's an implementation hint if there is.
