### ISSUE TITLE
Core/Movement: cyclic spline doesn't works

### ISSUE THREAD

**Issue by gonzo1247** [The-Cataclysm-Preservation-Project/TrinityCore#210]
**Description:**

Cyclic Splines do not work acutally. I test it on this Creature: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/0fe8d6e7f28d063ac1fbc79d20be304d465b2685
after 5 Minutes no Movement of the creature.

**Current behaviour:**

**Expected behaviour:**

Cyclic Splines Waypoints should works.

**Steps to reproduce the problem:**

1. start Server
2. use commands .go creature 396407 (use first .gm fly on)
3. see that Xariona dosn't move

**TC rev. hash/commit:** 

Testet with commit 18cfca291bbeec9042964572feadb7bdd2d564e1

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by Ovahlord** [comment]
![grafik](https://user-images.githubusercontent.com/18347559/104366169-411e9a00-5519-11eb-92dd-37af918865a0.png)

works for me. Pserver issue, not mine.

**Comment by gonzo1247** [comment]
Thats interesstet, it was a clean build from this GIT without external changes, DB was used the last https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/releases TDB release + auto updater...but okey

**Comment by manhdv** [comment]
Xariona doesn't move on my fresh install too.

**Comment by gonzo1247** [comment]
@Ovahlord change 
```c++
CyclicMovementGenerator<Creature>::CyclicMovementGenerator() : _path(nullptr), _moveTimer(0)
```
to
```c++
CyclicMovementGenerator<Creature>::CyclicMovementGenerator() : _path(nullptr), _moveTimer(0), _stalled(false)
```

**Comment by gonzo1247** [comment]
edit:
I debug this parts:
```c++
bool CyclicMovementGenerator<Creature>::DoUpdate(Creature* creature, uint32 diff)
CyclicMovementGenerator<Creature>::DoInitialize(Creature* creature)
 CyclicMovementGenerator<Creature>::CyclicMovementGenerator() : _path(nullptr), _moveTimer(0)
```
all times was _stalled on true and the cyclic movement wont works. Whit the initialized _stalled works fine
