### ISSUE TITLE
[SPELL/PRIEST] Divine Aegis

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#211]
**Current behaviour:**

Absorbs always 0 damage.

**Expected behaviour:**

Should apply a 10%/20%/30% absorb of critical heal depending on talent rank.

**Steps to reproduce the problem:**

1. Create a priest, spec into Divine Aegis (Discipline)
2. Make a critical heal and see that it will absorb 0 damage.

**TC rev. hash/commit:** 

5c0febcfb38828a28da9edd27900a85e052cc738

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by lingxDEV** [comment]
if (AuraEffect const* shieldDiscipline = GetTarget()->GetDummyAuraEffect(SPELLFAMILY_HUNTER, PRIEST_ICON_ID_SHIELD_DISCIPLINE, EFFECT_0))
            AddPct(absorb, shieldDiscipline->GetAmount());

I guess SPELLFAMILY_HUNTER might have something to do with this? I've tried replacing with SPELLFAMILY_PRIEST, no luck.

**Comment by Ovahlord** [comment]
No, you did not learn the mastery properly at a trainer. .learn is adding you the wrong spell id so you will have an aura that wont do shit because it's not updated.

**Comment by Ovahlord** [comment]
The shield discipline mastery btw is in fact a hunter spell (for whatever the reason so that part is not wrong). I assume that the base heal value itself is lacking

**Comment by lingxDEV** [comment]
Divine Aegis should not require mastery, just modified by it. So I don't understand why the issue is closed @Ovahlord as it's not related to mastery.

**Comment by lingxDEV** [comment]
@Ovahlord This is still bugged can you re-open
