### ISSUE TITLE
[SPELL/SHAMAN] Totems friendly / hostile not reflecting casters state

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#213]
**Current behaviour:**

![image](https://user-images.githubusercontent.com/62337627/104474929-cb6d0980-55be-11eb-98be-070f890c1598.png)
(Totem attacking in Dalaran which is a sanctuary)

**Expected behaviour:**

Shaman totems should be attackable when the shaman is. So when the shaman is in a sanctuary, where you can not attack the opposing faction, his totems should also not be attackable/attack.

Additionally, when dueling a shaman of same faction, you can not attack his totems.
![image](https://user-images.githubusercontent.com/62337627/104475271-30c0fa80-55bf-11eb-9c8d-95e04d25a305.png)

**Steps to reproduce the problem:**

Check the screenshots.

**TC rev. hash/commit:** 

4a158fdf22089a3fffacc9df19b814c26452e658

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by gtestdev** [comment]
Related with: #87

**Comment by Ovahlord** [comment]
duplicate of https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/87
