### ISSUE TITLE
DK Runes not working

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#214]
**Description:**

Death Knight Runes

**Current behaviour:**

When you try to use any ability that requires runes, you will get the error message "Not enough runes".

**Expected behaviour:**

You should be able to use spells that will consume runes.

**Steps to reproduce the problem:**

1. Make a DK
2. Use any spell that requires Runes

**TC rev. hash/commit:** 

4a158fdf22089a3fffacc9df19b814c26452e658

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Ovahlord** [comment]
Can you try to pin down when exactly this started to happen?

**Comment by lingxDEV** [comment]
I really haven't looked into DKs much in the past, but someone mentioned this on Discord. He might be able to 
![image](https://user-images.githubusercontent.com/62337627/104649814-8e377300-56b5-11eb-83e0-2dc07ad71075.png)

**Comment by gonzo1247** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/e2d6a2f0cdf5c74356e25020279d9e634818a7bc

the bugs come with this commit. In void Player::SendInitialPacketsBeforeAddToMap() readd     if (getClass() == CLASS_DEATH_KNIGHT)
    {
        for (uint8 i = 0; i < MAX_RUNES; i++)
        {
            WorldPackets::Spells::ConvertRune packet;
            packet.Index = i;
            packet.Rune = GetCurrentRune(i);
            SendDirectMessage(packet.Write());
        }
    }

and looks its works

**Comment by Ovahlord** [comment]
Yeah, but that's a hack so dig deeper
