### ISSUE TITLE
WoW Client Error after Packet Update

### ISSUE THREAD

**Issue by gonzo1247** [The-Cataclysm-Preservation-Project/TrinityCore#215]
**Description:**

After this commit: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c3831d30e580eb75891cf48b83b065d2dfecb540
clients they are in a group and has a phase Update becomes a Client Crash but i can not exactely say in witch cases this happens. Its not always at phase change - i think they is a specific combo or so

**Current behaviour:**

Log in with more as one client, create a party and do something - if fits the client crash

**Expected behaviour:**

client should not be crashed

**Steps to reproduce the problem:**

1. login with 2 or more client
2. create a party
3. do somethin.

**TC rev. hash/commit:** 

5e3b57bae7128a5abb69b46651ad584d5dfcb1c7

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by Faq** [comment]
Any example place where crash happened? So it is easier to repeat. Can you post picture of crash?

**Comment by gonzo1247** [comment]
picture not but this: https://paste2.org/zMcgyznc
https://www.wowhead.com/npc=43612/high-prophet-barim by this boss when he changed the phase from Begone Infidels to Kneel and Repent
in some cases the crashes occures a player stand in stormwind/orgrimmar and a other moved outside of the city (and probably has a phase change) in some case the crash cam if you enter a dungeon.
I try every commit and found at least found out that they commit above is guilty on this crashes. 
its totaly random i try it with two clients at the same time login and moved around 30 mins in the world and nothing happens...in other case a client crash comes a few minutes after login.

**Comment by Ovahlord** [comment]
Log the packets and see where the packet parser chokes

**Comment by DevPrimeR** [comment]
> Any example place where crash happened? So it is easier to repeat. Can you post picture of crash?

![crash2](https://user-images.githubusercontent.com/10391503/105646318-537bca80-5e6d-11eb-9a5c-48fee84c44f0.png)
![unknown](https://user-images.githubusercontent.com/10391503/105646321-570f5180-5e6d-11eb-88c8-c55318d3b9be.png)

Something similar happens to me, I will try to parser the client and show the information apparently the wow errors are produced from this commit:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c3831d30e580eb75891cf48b83b065d2dfecb540

**Comment by Ovahlord** [comment]
you still have to give me examples where and when it happens.

**Comment by DevPrimeR** [comment]
hello, to try to replicate the wowerror you must create 2 characters with auras which can be shared for example: (hunter, paladin) and create a group or band and then try to enter an instance with the owner of the aura and the target of the aura will get the wow error.

Apparently it does not happen with all clients ...

I will try to test the commit https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/cf2267af3f95b539a1d32efae38066d83cdd9e5e
to see if it is solved, otherwise I will make a video explaining how to produce the error. 😄

**Comment by Ovahlord** [comment]
please test again after https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/97686dc28720d0d6b5ce1513add0fb004ac486af
