### ISSUE TITLE
[SPELL/DK] Dancing Rune Weapon

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#216]
**Description:**

Dancing Rune Weapon

**Current behaviour:**

When cast, it will spawn a unit (see picture below) which is only visible to GMs.

The spell itself does nothing.

![image](https://user-images.githubusercontent.com/62337627/104783515-7b40a380-5786-11eb-9ae9-feba87e7db29.png)

**Expected behaviour:**

Should spawn a Rune Weapon that will mirror the DKs attacks. It should also provide the DK with 20% additional parry chance (which as far as I can see isn't working either).

**Steps to reproduce the problem:**

1. Create a  DK
2. Cast Dancing Rune Weapon
3. See that nothing happens. Put on GM mode to see the unit being spawned.

**TC rev. hash/commit:** 

4d95bcc068f0794b4cd70025e0fab8b529c35abc

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Nyr97** [comment]
The spell itself and its NPC involved are not scripted. I checked it out.

**Comment by Ovahlord** [comment]
2161908280b381574ce6e7863a322e5d2bb1c9fc
