### ISSUE TITLE
[SPELL/PRIEST] Psychic Scream

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#217]
**Description:**

Psychic Scream

**Current behaviour:**

There is no fear pathing. When a target is affected by Psychic Scream, it will stand in place not moving around in fear.

**Expected behaviour:**

When a target is affected by Psychic Scream is should move around in random directions in fear.

**Steps to reproduce the problem:**

1. Create a priest
2. Cast Psychic Scream on a target
3. See that it stands in place not moving

**TC rev. hash/commit:** 

4d95bcc068f0794b4cd70025e0fab8b529c35abc

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by lingxDEV** [comment]
It seems to be a general problem for more "fear" spells.

Tested and **not** working:
- Warlock
    - Fear
- Warrior
    - Intimidating Shout


For some reason Warlocks Howl of Terror has fear pathing **work** as the only one.

**Comment by Warpten** [comment]
Psychic Fear has a root component to it on top of the fear, which is needed for the associated glyph to work. It needs to be prevented if the glyph isn't set. Same for warlock fear and warrior shout.
