### ISSUE TITLE
[SPELL/HUNTER] Scatter Shot

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#220]
**Description:**

Scatter Shot

**Current behaviour:**

When you have auto attack ready as hunter and cast Scatter Shot, it will launch the Scatter Shot and the auto attack as well, breaking the Scatter Shot immediately. 

Scatter does have stop auto attack flag, but if the auto attack is ready, it will still fire it.

If you cast an auto attack and then wait .5 seconds and then cast Scatter Shot, hunter will stop casting auto attacks and everything works fine. So the problem only exists when the auto attack is ready.

**Expected behaviour:**

When Scatter Shot is cast, the hunter should not cast an auto attack as well.

**Steps to reproduce the problem:**

1. Make a hunter
2. Cast Scatter Shot on a target and see that it will fire an auto attack as well breaking the Scatter Shot effect.

**TC rev. hash/commit:** 

4d95bcc068f0794b4cd70025e0fab8b529c35abc

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Ovahlord** [comment]
cannot reproduce. auto attack gets interrupted.
