### ISSUE TITLE
[SPELL/ROGUE] Bandit's Guile

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#221]
**Description:**

Combat talent Bandit's Guile

**Current behaviour:**

Right now, casting Sinister Strike 1 time will proc Shallow Insight. Next Sinister Strike procs Moderate Insight and third Sinister Strike procs Deep Insight.

x1 Sinister Strike = Shallow Insight
Another 1x Sinister Strike = Moderate Insight
Another 1x Sinister Strike = Deep Insight

**Expected behaviour:**

Each of the Insight buffs should proc after 4x Sinister Strikes.

x4 Sinister Strike = Shallow Insight
Another 4x Sinister Strike = Moderate Insight
Another 4x Sinister Strike = Deep Insight

**Steps to reproduce the problem:**

1. Make a rogue
2. Spec Combat -> Bandit's Guile
3. Cast Sinister Strike
4. See that you gain the Insight buffs after just 1 Sinister Strike

**TC rev. hash/commit:** 

a15256f47aa9859d5d8cbeb4307daab43254ff69

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by Ovahlord** [comment]
And now the part where you tell me where you got the numbers from

**Comment by lingxDEV** [comment]
> And now the part where you tell me where you got the numbers from

Watch any combat rogue video from retail cata

Rotation here: Sinister, Sinister, Revealing Strike, Sinister = Shallow Insight
https://youtu.be/bjfo46XLLMc?t=43

Watch this rotation, pay attention to what's being pressed:
https://www.youtube.com/watch?v=OBtyMlJNe8k

This opener: Sinister, Revealing.... waiting in disarm... Sinister Sinister = Shallow Insight
https://youtu.be/MFiVe1s7jec?t=222

More examples:
https://youtu.be/_kQiSv4jY0A?t=11

**Comment by lingxDEV** [comment]
Wowhead in 2012:
https://web.archive.org/web/20120222213813/https://www.wowhead.com/spell=84654#comments

Read the comments.
