### ISSUE TITLE
Shaman Totems stop moving.

### ISSUE THREAD

**Issue by zxyjwy** [The-Cataclysm-Preservation-Project/TrinityCore#222]
Current behaviour:

Shaman Totems stop moving.

npcid : 15438 and 15352.

Expected behaviour:

npcid : 15438 and 15352 follows owner.

Steps to reproduce the problem:

cast 2894

cast 2062

TC rev. hash/commit:

4a158fd

TDB version:

TDB 434.20091

Operating system:

Win10 64

**Comment by AGandrup** [comment]
I can't seem to find any evidence that this should be the case for 4.3.4.
In this video below, from [02:37](https://youtu.be/K2fK0Eo-Osw?t=157), the shaman has summoned his Fire Elemental. At [03:00](https://youtu.be/K2fK0Eo-Osw?t=180) the Fire Elemental is feared and resets, and then at [03:13](https://youtu.be/K2fK0Eo-Osw?t=192) it can be seen that the Fire Elemental is standing idle next to its totem.
Source: https://youtu.be/K2fK0Eo-Osw "4.3.4 elemental shaman pvp damage" from 2012.

**Comment by Ovahlord** [comment]
false report. totem summons are not meant to follow the summoner.
