### ISSUE TITLE
Spell queue system not implemented

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#224]
**Description:**

The spell queue system was introduced with Cata

**Current behaviour:**

Not implemented.

**Expected behaviour:**

Basically you can press a spell before the global cooldown is ready and the pressed spell will be queued and cast when the global cooldown is ready. Based on what you set your custom lag tolerance to, you can press the next spell to queue (a max of 400 ms before the global cooldown is ready - see image below).

Here is a video showcasing the issue:

https://www.youtube.com/watch?v=LXruPtkNWS0

This part here is part of the Spell queue system:
![image](https://user-images.githubusercontent.com/62337627/105247719-8411ea80-5b75-11eb-84b1-cafb18fe681f.png)

**TC rev. hash/commit:** 

f91c30868fee9296385222ad73c69af4cac2065b

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by lingxDEV** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/game/Server/Protocol/Opcodes.h#L120

Some opcode for it

**Comment by Ovahlord** [comment]
Of course it's not implemented because it's not needed in private server emulators. Blizzard used to have a 400ms interval when they process spell cast requests which we do not have. We execute spell casts right when they are being requested so that 'feature' is obsolete.

**Comment by lingxDEV** [comment]
>  it's useless.

I don't agree. In order to cast spells as fast as possible, with the current state of the source, you will have to spam you ability as fast as possible, in order to make sure the next spell is cast right after your current cast.

With spell queue, you can press the next spell just once in the 400 ms window and the spell will be cast right after the current cast.

It's not useless and it's blizzlike. Not having it makes it feel like a clunky private server, not the blizzlike experience.

**Comment by Ovahlord** [comment]
Well, good thing we don't care about private servers so their diehard mission of artifically recreating a dated system is none of our concerns

**Comment by lingxDEV** [comment]
So I guess the Preservation project is infact the Improvement project. Good to know

**Comment by Quest79** [comment]
Doesn't preservation mean you're preserving what the game was back then? Private servers are irrelevant, if its not a preservation project just let us know, because this likely isn't the first thing you ant to make different from the actual game.

**Comment by lingxDEV** [comment]
I did not see that coming. Good work Ovah

**Comment by Quest79** [comment]
So it's not a Cataclysm preservation project. It's a Trinity preservation project. The project is just mislabeled. Good to know for everyone.
