### ISSUE TITLE
fix crash  SetCharmedBy ASSERTION FAILED

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#229]
**Description:**
Hello, I have found a solution to an error which occurs when the players become vehicles and they are controlled or enchanted during the encounter of a boss or a creature ...
for example spell 102334 which uses the player as a vehicle and in turn adds SPELL_AURA_AOE_CHARM

```
Unit.cpp: 11968 in Unit :: SetCharmedBy ASSERTION FAILED:
  (type == CHARM_TYPE_VEHICLE) == IsVehicle ()
```

This fix can fix it:
https://github.com/TrinityCore/TrinityCore/commit/1fecbc6892b41bfe9d1e474d038c3b1f6e2dd125

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/ef25a19326535655ba84cd88b577bc1be1ebb0b3
