### ISSUE TITLE
WaypointMovementGenerator issues with flying creatures

### ISSUE THREAD

**Issue by Nyr97** [The-Cataclysm-Preservation-Project/TrinityCore#230]
**Description:**

When a flying NPC, which has a different animation (added through bytes1 on _addon) for flying and walking, such as Val'kyr models, follows a waypoint path with move_type 2 (flight), it will make a land animation when reaching first pointId and then use IDLE animation as default while moving through the entire path.

**Current behaviour:**

Exactly what was described above. Link for reference: https://youtu.be/BZKdEMXjCLM

**Expected behaviour:**

When reaching the first pointId, the creature should keep the hover animation.

**Steps to reproduce the problem:**

1. On creature_template_addon, add 50331648 on bytes1 for the creature 45314. 
2. Create a waypoint with flying patterns for such creature.
3. Make the npc use the path and watch it bug out.

**TDB version:** TDB_full_world_434.20091_2020_09_22.sql

**Operating system:** Windows 10.

**Comment by Ovahlord** [comment]
first of all, movement type 2 is  WAYPOINT_MOVE_TYPE_LAND so you actually launched a landing spline which disables hover movement once landed. There is no flying movement type. for that you have to disable gravity of the unit permanently which you should know if you would use sniffs.

Also this quest is not scripted by any of us people here so private development gets no support.

**Comment by Nyr97** [comment]
First, according to https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130114/waypoint+data, movement_type 2 is for flying splines.

Second, no wonder it is not scripted by any of you because it's me doing it so I can make a pull request for everyone to have it.

**Comment by Faq** [comment]
@Nyr97 Feel free to do so.
