### ISSUE TITLE
[Visual bug] Flying unit movement do not have pitch

### ISSUE THREAD

**Issue by miirak** [The-Cataclysm-Preservation-Project/TrinityCore#235]
**Description:**

Flying units moving to their path without turning their pitch to correctly look at the target path.

**Current behaviour:**

For example let's look at the Ocolus dragons. They are using PointMovementGenerator to move to the player's location, but their pitch doesn't change at all to look down: https://imgur.com/h3Bbtly

**Expected behaviour:**

Their pitch should be changed aswell: https://imgur.com/gzGRHrW

**TC rev. hash/commit:** 

TrinityCore rev. c20838ceaa5b+ 2021-02-05 11:16:45 +0100 (master branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB 434.20091

**Operating system:** Win10

**Comment by Ovahlord** [comment]
That's not a real bug corewise, it's bad spline data since flying units like that dragon use a static path

**Comment by miirak** [comment]
Thank you for your answer!
That is strange because in the core where I got the expected result is using the same method to move that dragon, with `MovePoint` function. I've tried to figure out the differences in this function, but I couldn't figure out how the MonsterMove packet differed in the other core to achieve that pitch as target point visual.

**Comment by Ovahlord** [comment]
All I can tell you is that the Oculus is probably one of the worst spots to look for issues since that instance is old and has been scripted without sniffs by some mangos guys very long ago so yeah. Don't take anything there as reference.
