### ISSUE TITLE
DB/NPC: Innkeeper Farley has switched gossip texts

### ISSUE THREAD

**Issue by TQPS** [The-Cataclysm-Preservation-Project/TrinityCore#236]
**Description:**

Innkeeper Farley's menu options are switched.

`Make this inn your home.` is switched with what's supposed to be a chat bubble `What can I do at an inn?`. 

Instead, his other 2 options are both referencing browsing his goods.

**Current behaviour:**

His current options look like the following:

<details>

![image](https://user-images.githubusercontent.com/66294837/108136016-4e790680-710d-11eb-8cc9-813442066c1b.png)

</details>

**Expected behaviour:**

Options should be as follows:

<details>

![image](https://user-images.githubusercontent.com/66294837/108136330-fd1d4700-710d-11eb-998b-057d3425a1ba.png)

</details>

NPC Info:

<details>

![image](https://user-images.githubusercontent.com/66294837/108136959-1bd00d80-710f-11eb-9134-83222202237b.png)

</details>

**Steps to reproduce the problem:**

1. Go to Goldshire in Elwynn Forest
2. Enter Inn, Innkeeper Farley is the Innkeeper
3. Right click him to see options.

**TC rev. hash/commit:** 

TrinityCore rev. 116a9864d83b 2021-02-16 17:09:46 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  

434.20091

**Operating system:** 

Windows 7 Ultimate x64 SP1

**Comment by SargeroDeV** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/pull/259
