### ISSUE TITLE
Core/FollowMovementGenerator: Charmed creatures ignore its HoverHeight when following a player during LaunchMovement

### ISSUE THREAD

**Issue by Nyr97** [The-Cataclysm-Preservation-Project/TrinityCore#241]
**Description:** Creatures summoned through a spell (meaning these creature have UNIT_FLAG_PLAYER_CONTROLLED) which have a certain Hover Height added either through C++ or database should stay above the ground, not clip through it while following its owner.

**Current behaviour:** A creature's Hover Height is completely ignored when following a player (e.g. temporal summon controlled by a player). It doesn't matter whether you set the creature as a ground/flying creature, its movement generator will ignore the value anyway. It's probably a missing feature regarding its movementgenerator system. Proof: https://youtu.be/FYie7afch4U

**Expected behaviour:** A creature's hover float should be respected by its movementgenerator system when following a player. Proof: https://www.youtube.com/watch?v=p2HcbFvTwac (skip to 1:52 to notice its correct behaviour).

**Steps to reproduce the problem:**

1. On creature_template, set HoverHeight to 4 on entry 46034.
2. On creature_template_addon, set bytes1 to 50331648 (activates flying hover anymation, otherwise it uses its walking animation) on entry 46034.
3. On creature_template_movement, set Flying to 1 on CreatureId 46034.
4. Log in-game and use spell 85870.

**TC rev. hash/commit:** TrinityCore rev. 0621b066f4a1+ 2021-02-25 01:20:12 +0100 (Teleqraph branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** TDB 434.20091

**Operating system:** Windows 10

**Comment by Nyr97** [comment]
Created a pull request to fix this behaviour: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/pull/240/commits/0463fcf74e2c2a87efc09c8df076e8a94f8dcf0a

**Comment by Ovahlord** [comment]
you're missing creature_template_movement ground = 2 to apply hover movement.
