### ISSUE TITLE
[compile] environmental problems

### ISSUE THREAD

**Issue by kuramajssken001** [The-Cataclysm-Preservation-Project/TrinityCore#244]
**Description:**

19>C:\local\boost_1_74_0\boost/asio/detail/io_object_impl.hpp(168,17): error C2079: “boost::asio::detail::io_object_impl<boost::asio::detail::resolver_service<InternetProtocol>,Executor>::executor_”使用未定义的 class“boost::asio::executor”
19>        with
19>        [
19>            InternetProtocol=boost::asio::ip::tcp,
19>            Executor=boost::asio::executor
19>        ] (编译源文件 F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp)
19>C:\local\boost_1_74_0\boost/asio/ip/basic_resolver.hpp(1022): message : 查看对正在编译的 类 模板 实例化“boost::asio::detail::io_object_impl<boost::asio::detail::resolver_service<InternetProtocol>,Executor>”的引用
19>        with
19>        [
19>            InternetProtocol=boost::asio::ip::tcp,
19>            Executor=boost::asio::executor
19>        ] (编译源文件 F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp)
19>F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp(132): message : 查看对正在编译的 类 模板 实例化“boost::asio::ip::basic_resolver<boost::asio::ip::tcp,boost::asio::executor>”的引用
19>F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp(132,163): error C2664: “std::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)”: 无法将参数 1 从“_Ty”转换为“boost::asio::ip::tcp::resolver &”
19>        with
19>        [
19>            _Ty=boost::asio::ip::tcp_resolver
19>        ]
19>F:\Code\CTM\TrinityCore\src\common\Asio\Resolver.h(29,57): message : 参见“Trinity::Net::Resolve”的声明 (编译源文件 F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp)
19>F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp(139,157): error C2664: “std::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)”: 无法将参数 1 从“_Ty”转换为“boost::asio::ip::tcp::resolver &”
19>        with
19>        [
19>            _Ty=boost::asio::ip::tcp_resolver
19>        ]
19>F:\Code\CTM\TrinityCore\src\common\Asio\Resolver.h(29,57): message : 参见“Trinity::Net::Resolve”的声明 (编译源文件 F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp)
19>F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp(146,157): error C2664: “std::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)”: 无法将参数 1 从“_Ty”转换为“boost::asio::ip::tcp::resolver &”
19>        with
19>        [
19>            _Ty=boost::asio::ip::tcp_resolver
19>        ]
19>F:\Code\CTM\TrinityCore\src\common\Asio\Resolver.h(29,57): message : 参见“Trinity::Net::Resolve”的声明 (编译源文件 F:\Code\CTM\TrinityCore\src\server\bnetserver\Realms\BNetRealmList.cpp)

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/947b56f0fc999387fdd97e83e52f18043502eac8
**Operating system:** 

win10
Boost  1.74 
MySQL  5.7.0
CMake  3.9.0
OpenSSL  1.0.h
MS Visual Studio 16 2019
ZeroMQ-4.0.4~miru1.0  x64

**Comment by kuramajssken001** [comment]
Am I the only one with this problem?

**Comment by Ovahlord** [comment]
boost 1.74 is currently not supported (yet). any version below will compile

**Comment by kuramajssken001** [comment]
thank u Ovahlord I'll close this.

**Comment by Ovahlord** [comment]
b9c72c3c7f1b6090231163f133fe1be4d399b218 should solve this
