### ISSUE TITLE
Cata client not able to connect to server

### ISSUE THREAD

**Issue by mgracia012020** [The-Cataclysm-Preservation-Project/TrinityCore#247]
**Description:**
Not able to connect to private server. Recompiled the latest code revision with DB updates. I downloaded 2 other Cataclysm older repacks and I am able to connect (not to the latest compilation).

**Current behaviour:**
Created new account via worldserver console and set gmlevel rights. I launch the (4.34-15595) wow-patched client (after using connection patcher exe) and the client keeps getting disconnected from server. The realmlist is configured to listen on localhost only. Client settings are configured to connect to 127.0.0.1 only.

Also ran the server in a different machine - same issue

Also tried multiple cataclysm clients - same behavior

Turned firewall and AV off

I also run the Trinitycore 3.3.5 private server - able to connect with client using localhost settings.

No crash - wow client is not able to connect.

**Expected behaviour:**

I expect the client to connect . I am able to connect with the same client/settings using older 4.34 server repacks.

**Steps to reproduce the problem:**

1. Compile latest cataclysm preservation code
2. Followed the wiki step by step and installed all requirements
3. Auth/Worldserver bins load up fine - no errors - server starts as expected.
4. Client does not connect - Error - You have been disconnected from server.
**TC rev. hash/commit:** 

TrinityCore rev. 6301a324cd7e 2021-03-25 17:10:51 +0100 (master branch) (Win64, Release, Static) (bnetserver)
TrinityCore rev. 6301a324cd7e 2021-03-25 17:10:51 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB_full_434.20091_2020_09_22  Version of the TrinityCore database

**Operating system:** Windows 10

**Comment by dsikiba** [comment]
create a new folder in your client folder and name it backup
you need to move wow.exe and battle.net.dll to this folder
then rename wow_patched.exe to just wow.exe
then rename battle.net_patched.dll to just battle.net.dll
should work after this if you didnt get a error in the connection_patcher
i've helped a few people fix this issue over the week i was gonna make a video yesterday for it but i had to goto work

**Comment by mgracia012020** [comment]
Thanks so much.
