### ISSUE TITLE
Connection_Patcher

### ISSUE THREAD

**Issue by CrossUCI** [The-Cataclysm-Preservation-Project/TrinityCore#25]
In windows works fine but , in linux give me this error.

./connection_patcher Wow.exe 
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static) (connection_patcher)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Creating patched binary...
Win32 client...
Patching client binary...
patching redirect RSA Modulus
Found offset 7961504
Patching done.
Patching battle.net binary...
patching Portal
Found offset 1694224
patching Bnet
Found offset 864857
patching Signature
Found offset 134009
Patching done.
EX: basic_string::_M_construct null not valid

**Comment by DickFiddler** [comment]
https://community.trinitycore.org/topic/11588-error-112/
See post by Elckerlijc near end of thread.

**Comment by CrossUCI** [comment]
@DickFiddler thanks , i can close this issue
