### ISSUE TITLE
DK Starter Zone portals not working. Quest 13188 & 13189. Can not leave the zone without gm cmds.

### ISSUE THREAD

**Issue by acidmanifesto** [The-Cataclysm-Preservation-Project/TrinityCore#250]
**Description:**

https://www.wowhead.com/quest=13188/where-kings-walk
https://www.wowhead.com/quest=13189/warchiefs-blessing

Game Template guid 193052 Portal to orgrimmar  which casts 58418 on player
Game Template guid 193053 Portal to stormwind which casts 58420 on player

Both game objects do not teleport the player.
to their respected areas for the ending of the DK Starter area.

**Current behaviour:**
When you get the two quests and click on the portals (horde for orgrimmar and alliance for stormwind)
nothing happens. I suspect issus with spell 58418 and 58420 of the game object. see nots below.

**Expected behaviour:**

Needs to teleport to the player to the respected zones.

**Steps to reproduce the problem:**

1. Complete DK Starter area and get quest:
https://www.wowhead.com/quest=13188/where-kings-walk
https://www.wowhead.com/quest=13189/saurfangs-blessing

2. Click on portal

**TC rev. hash/commit:** 

d4b9063

**TDB version:**  TDB 434.20091

**Operating system:** Windows 10 Pro x64

**Side Note:**
now i am  currently able to temporary work around this issue with changing the spells up with the following sql adjsutments:
/*
orgrimmar portal spells that work
originally spell 58418, however that does not work in game for the portal to orgrimmar spell portal in dk starter area
*/
```UPDATE `gameobject_template` SET `Data0`='94724' WHERE  `entry`=193052;```

/*
stormwind portal spell that work
originally spell 58420, however that does not work in game for the portal to stormwind spell portal in dk starter area
*/
```UPDATE `gameobject_template` SET `Data0`='85546' WHERE  `entry`=193053;```

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/113738777-31a08e80-96cd-11eb-849f-999f5325e0c3.png)
![image](https://user-images.githubusercontent.com/16887899/113738813-39603300-96cd-11eb-8cbd-a2c42fcc0cf1.png)
In game gobject near for further information.

**Comment by acidmanifesto** [comment]
Debugger mode brings me to this line
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/d4b90631feca664b6cc1a5403f04c4f709171543/src/server/game/Spells/SpellEffects.cpp#L3284

**Comment by Ovahlord** [comment]
The proper fix would be adding spell_target_position data for spell 58419 and 58421 which both have a db dest locations

**Comment by acidmanifesto** [comment]
i will look into it now. thank you for the insight.

**Comment by acidmanifesto** [comment]
@Ovahlord i have done the following 
```-- correct fix for orgrimmar portal
DELETE FROM `spell_target_position` WHERE  `ID`=58418;
INSERT INTO `spell_target_position` (`ID`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`) VALUES ('58418', '1', '1569.59', '-4397.63', '16.06', '0.54');

-- correct fix for stormwind portal
DELETE FROM `spell_target_position` WHERE  `ID`=58420;
INSERT INTO `spell_target_position` (`ID`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`) VALUES ('58420', '0', '-8833.37', '628.62', '94.00', '1.06');```

So far it does not fix the issue.

**Comment by Ovahlord** [comment]
look again. you changed the wrong spells.

**Comment by acidmanifesto** [comment]
@Ovahlord Im not sure how to get with you in private. but i'm curious if you are interested in setting up a custom branch of CPP like how there is one for 335 that TC setup. I have some modules i made for 335 working with cata if you feel like it will be a good fit?
