### ISSUE TITLE
Gameobject GUID 235520 & 236492 Potentional Duplicates

### ISSUE THREAD

**Issue by acidmanifesto** [The-Cataclysm-Preservation-Project/TrinityCore#254]
**Description:**
Gameobject GUID 235520 & 236492 Potentional Duplicates

**Current behaviour:**

There are two gates when i was doing a playthru audit of the worgen starter areas. I was doing quest To Greymane Manor
https://www.wowhead.com/quest=14465/to-greymane-manor

When you are heading to the objective you are to come to a set of gates, that show auto open.
However we have two of the same gates matching exactly with phase and xyz and state.
Makes it impossible to progress without gm command usuage.
Double Clicking the gates results with inconsistent one being open and one being closed.

Screen shots included

**Expected behaviour:**
Link to WOD Expansion video of game play. Can not seem to find the catacylsm recording
11 second mark shows the gate in retail.

https://youtu.be/k8ykvtveSdA?t=11

**Steps to reproduce the problem:**

1. Take quest 14465 as a Worgen
2. Proceed to quest objective
3. Encounter the duplicate gates.

**TC rev. hash/commit:** 

c41fe84

**TDB version:**  TDB 434.20091

**Operating system:** Windows 10

![image](https://user-images.githubusercontent.com/16887899/114729442-fbd35980-9d0d-11eb-9269-eea6a62d9ade.png)
![image](https://user-images.githubusercontent.com/16887899/114729476-04c42b00-9d0e-11eb-8d6a-949c639f679e.png)

**Comment by Ovahlord** [comment]
Gilneas is not supported beyond the first terrain swap so anything after that needs db fixups and data from sniffs. These two gameobjects are not duplicate. They belong to different phases

**Comment by acidmanifesto** [comment]
> Gilneas is not supported beyond the first terrain swap so anything after that needs db fixups and data from sniffs. These two gameobjects are not duplicate. They belong to different phases

Thank you for the clarification.
