### ISSUE TITLE
Trainers not working

### ISSUE THREAD

**Issue by maddubz** [The-Cataclysm-Preservation-Project/TrinityCore#258]
**Description:**
Class trainers not working, i've been searching around #147 
i have tried the fixes that were floating around on the issues section but to no avail 

**Current behaviour:**
Trainer menu doesn't open.

**Expected behaviour:**
Should be able to learn class spells.

**Steps to reproduce the problem:**
Download & Compile latest CPP, do some start quests and try to learn talents.

**TC rev. hash/commit:** 

TrinityCore rev. eda56e744c13 2021-04-21 20:00:23 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  CHANGEME Version of the TrinityCore database
Latest on "Release Page"

**Operating system:**
Linux (Debian 10)

Help on this would be appreciated! :)

**Comment by Ovahlord** [comment]
Be more specific please and add creature IDs of the trainers that suposedly not working.

**Comment by acidmanifesto** [comment]
@maddubz there is this from a git i am assisting a jr dev in our discord. However these are not VERIFIED by Sniffs or Parses.
They do work but they are all hand edited. If you are a bit determined to get them working for progression testing and further development with Cata then check them out. 
https://github.com/dsikiba/TrinityCore/blob/master/sql/custom/world/alliance_trainers.sql
https://github.com/dsikiba/TrinityCore/blob/master/sql/custom/world/horde_trainers.sql

**Comment by maddubz** [comment]
> @maddubz there is this from a git i am assisting a jr dev in our discord. However these are not VERIFIED by Sniffs or Parses.
> They do work but they are all hand edited and there fore considered a Hack Fix. If you are a bit determined to get them working for progression testing and further development with Cata then check them out. Use at your own risk.
> https://github.com/dsikiba/TrinityCore/blob/master/sql/custom/world/alliance_trainers.sql
> https://github.com/dsikiba/TrinityCore/blob/master/sql/custom/world/horde_trainers.sql

Ty these work!
