### ISSUE TITLE
[Critical] AI Chase movement is scuffed

### ISSUE THREAD

**Issue by miirak** [The-Cataclysm-Preservation-Project/TrinityCore#260]
**Description:**

Mob's chase movement doesn't dynamic meaning it will always move to the player's past position instead directly to the player.

**Current behaviour:**

Mob's attack can be easily avoided by running back and forth because its movement chase AI doesn't know if a player has moved from its first position that the mob perceived.

**Expected behaviour:**

Chase movement should get updated if the player has a new position and start moving to that position instead of finishing its current one. 

**Steps to reproduce the problem:**

1. Get in combat with a mob  
2. Start moving from one position to other and repeat
3. See that the mob's AI finishes its current position instead moving to the player

**TC rev. hash/commit:** 

TrinityCore rev. 7cc3577d7548a 2021-05-05 10:37:20 +0200 (master) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Win 10

**Comment by Ovahlord** [comment]
The movement is not suposed to be strict position based but instead it's based on melee and boundary ranges. Meaning that as long as the npc can hit you, it wont care about moving again.

**Comment by miirak** [comment]
> The movement is not suposed to be strict position based but instead it's based on melee and boundary ranges. Meaning that as long as the npc can hit you, it wont care about moving again.

I'm sorry you didn't understand the issue. It's not about strict position. Just run towards the mob while running away you'll see that this way you can avoid its attack. If it still doesn't clear then I guess I'll post a video.
