### ISSUE TITLE
Spell queue system gcd problem

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#264]
**Description:**

Triggering GCD without spell being cast

**Current behaviour:**

When you cast a spell, long before the current cast is finished, the spell queue system will trigger a GCD after the cast, but not cast the queued spell.

**Expected behaviour:**

GCD should only be triggered if a spell is cast.

**Steps to reproduce the problem:**

1. make a priest
2. Cast Greater Heal 
3. When the GCD of Greater Heal is finished press Greater Heal again
4. When the Greater Heal cast is complete, the GCD of the next spell will be triggered, but not cast.

Video example: 
https://streamable.com/c3uz52

**TC rev. hash/commit:** 

d5c0fda09607

**TDB version:**  CHANGEME Version of the TrinityCore database

Win10 64

**Comment by Ovahlord** [comment]
This happens when you spam the spell too often and as far as I'm aware it's a clientside restriction. gonna try to dig into the matter.
