### ISSUE TITLE
Allowable Races not correct working

### ISSUE THREAD

**Issue by gonzo1247** [The-Cataclysm-Preservation-Project/TrinityCore#275]
**Description:**

After kick the AllowableRaces from quest_template to quest_template_addon (https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/d9cbf60fd1ba076b48a02c7313fda585f47f43da) the race check it's not correct working.

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce the problem:**
While the position change from _allowableRaces they downgraded to a 16bit and can so only story up to 65535 and this is to small.
change from:
`_allowableRaces = fields[18].GetUInt16();`
to
`_allowableRaces = fields[18].GetUInt32();`

and its works fine

**TC rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by gonzo1247** [comment]
fixed with https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/a36e52e58761c9967061d3d3735d451f21ab8758

**Comment by funjoker** [comment]
Thanks 👍🏼
