### ISSUE TITLE
Exception thrown during packet processing

### ISSUE THREAD

**Issue by majere** [The-Cataclysm-Preservation-Project/TrinityCore#277]
**Description:**

bnetserver error: `Exception thrown during packet processing Attempted to read more bits (333) from stream than exist (304)`.

**Current behaviour:**

When I try connect to server, in bnetserver console's shows next error: `Exception thrown during packet processing Attempted to read more bits (333) from stream than exist (304)` and on client next error: `You have been disconnected from the server`.

**Expected behaviour:**

The client must pass authentication.

**Steps to reproduce the problem:**

1. Start `worldserver.exe`
2. Start `bnetserver.exe`
3. Start patched game client (x86 or x64) version `4.3.4.15595`
4. Enter login `test` in game client (user `test` has been already created)
5. Enter password in game client
6. Press `Login` in game client
7. In the console bnetserver shows the error `Exception thrown during packet processing Attempted to read more bits (333) from stream than exist (304)`
8. In game client shows error `You have been disconnected from the server`

**TC rev. hash/commit:** 

`TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)`
`TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (bnetserver)`

**TDB version:** `TDB_full_world_434.21071_2021_07_06`, `TDB_full_hotfixes_434.21071_2021_07_06`

**Operating system:** Windows 10 Pro 21H1 19043.1110 x64

Notes:
I think this exception occurs in `https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/bnetserver/Packets/AuthenticationPackets.cpp` in `void Battlenet::Authentication::LogonRequest::Read()`.
Error occurs in the third iteration `component.Program = _stream.ReadFourCC();`

**Comment by funjoker** [comment]
can you check the connection logs of your wow client and give us the content please

**Comment by majere** [comment]
`8/5 20:59:56.420  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK`
`8/5 20:59:56.460  GRUNT: state: RESPONSE_CONNECTED result: LOGIN_OK 127.0.0.1:1119`
`8/5 20:59:56.521  GRUNT: state: LOGIN_STATE_AUTHENTICATING result: LOGIN_OK `
`8/5 20:59:56.589  GRUNT: state: LOGIN_STATE_DISCONNECTED result: LOGIN_OK `
`8/5 20:59:56.611  GRUNT: state: LOGIN_STATE_FAILED result: DISCONNECTED `

**Comment by Ovahlord** [comment]
you're not logging in via email
