### ISSUE TITLE
Mapextractor does not extract some DBCs required for mmap generation

### ISSUE THREAD

**Issue by Geigerkind** [The-Cataclysm-Preservation-Project/TrinityCore#284]
**Description:**
The `map_extractor` does not extract some DBCs required for the `mmap_generator`.

**Current behaviour:**
LiquidType.dbc and Map.dbc seems to be missing.

**Expected behaviour:**
Should run without any issues.

**Steps to reproduce the problem:**
1. Download fresh client using the downloader and WoWRegeneration
2. Build master with tools
3. Copy tools into your newly downloaded client
4. Execute Tools

**TC rev. hash/commit:**:
TrinityCore rev. 5ed75162809c 2021-08-19 06:20:05 +0200 (master branch) (Unix, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  434.21074

**Operating system:** GNU/Linux PopOs! v. 21

**Comment by Ovahlord** [comment]
not related to the core. that's a client issue.
