### ISSUE TITLE
Core/Movement: WaypointReached function misbehaviour due to smoothTransition

### ISSUE THREAD

**Issue by Nyr97** [The-Cataclysm-Preservation-Project/TrinityCore#292]
**Description:** There's a bug regarding the use of WaypointReached if the waypointId has smoothTransition activated. It seems the NPC stops midway of the spline even though it hasn't reached its final destination.

**Current behaviour:** Let's say a certain pathId has 4 waypointIds. If WaypointReached is set for the NPC to do something when reaching waypointId 4, which has smoothTransition activated, the NPC will stop midway from waypointId 3 to 4, causing it to be misplaced. Though I don't know if this a desynchronization from the server to the client or it's on both sides.

**Expected behaviour:** WaypointReached should take the spline into account and not launch anything in said function until the final point of the spline has been reached.

**Steps to reproduce the problem:** 

1. Create a simple pathId which includes smoothTransition. 
2. Make the NPC do something when reaching the last waypointId through WaypointReached.
3. Watch it stop midway of the last spline instead of waiting to reach its final point.

**TDB version:** TDB 434.21071

**Operating system:** Win10 64

**Comment by Ovahlord** [comment]
The smooth transition calls the waypointreached when the transition happens, not when the destination of the packet has been reached. That's intended and I went with that because it makes more sense to trigger it at the transition instead of while being in the middle of a new spline.

**Comment by Nyr97** [comment]
Maybe adding some sort of support on WaypointReached through a boolean to make NPCs do stuff when reaching the final point when smoothTransition is enabled instead of following that case? Since I can't think of anything else to use for actions to be taken when smoothTransition is on and waypoints are the guide for the NPC.
