### ISSUE TITLE
Unknown column 'smoothTransition' in 'field list'

### ISSUE THREAD

**Issue by Hyldran0** [The-Cataclysm-Preservation-Project/TrinityCore#295]
In mysql_stmt_prepare() id: 4, sql: "SELECT entry, pointid, position_x, position_y, position_z, orientation, velocity, delay, smoothTransition FROM waypoints ORDER BY entry, pointid"
Unknown column 'smoothTransition' in 'field list'

Fresh compiled 4.3.4 TC.
Opening worldserver.exe makes this error and wont open fully.

**Comment by Ovahlord** [comment]
you did not use the correct database or screwed up the updating process
