### ISSUE TITLE
Core/Spell: TARGET_UNIT_UNK_105 insights (NYI)

### ISSUE THREAD

**Issue by Nyr97** [The-Cataclysm-Preservation-Project/TrinityCore#297]
**Description:** Apparently, there are 50 spells using this TARGET_UNIT flag and most of them belong to the Cataclysm expansion. It seems it targets both the vehicle and its owner.

**Current behaviour:** Any spell using TARGET_UNIT_UNK_105 will not work at all since it's not yet implemented. Many of them are used for spell credits and such these are not completing several quests when used.

**Expected behaviour:** TARGET_UNIT_UNK_105 should target both the vehicle and its owner.

**Steps to reproduce the problem:**

1. Add VehicleId 1105 and AIName SmartAI on creature_template for Gilneas Camera 01 (45427).
2. Add a SmartAI to cast Quest Credit: What Tomorrow Brings (84929) after 1s when boarded.
3. Add quest What Tomorrow Brings (24701) on you.
4. Spawn the creature Gilneas Camera 01 (45427) and use any ride spell on it.
5. The quest is not completed after the creature uses the spell.

**TC rev. hash/commit:** TrinityCore rev. 8aea16c62803+ 2021-10-15 05:43:04 +0200 (silverpinereworks branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** TDB 434.21071

**Operating system:** Windows 10 (64 bits)

**Notes**: I'm adding both SMSG_SPELL_START and SMSG_SPELL_GO to give some insight on this flag.
SMSG_SPELL_START: ![image](https://user-images.githubusercontent.com/30064812/137596912-ba7d0581-b12b-477a-833b-1e677b994173.png)
SMSG_SPELL_GO: ![image](https://user-images.githubusercontent.com/30064812/137645287-7192e297-1fd0-40d4-ae90-ca2fa7e4cc5c.png)

**Comment by Lordron** [comment]
yes, 1 of the spells in MoP has name 
ID - 114723 Vehicle: Hide Self and Passengers (Invis 1)(Broke)
