### ISSUE TITLE
Starting the game Client

### ISSUE THREAD

**Issue by SuperSmelly** [The-Cataclysm-Preservation-Project/TrinityCore#30]
**On logon the client just disconnects:**

I have complied this project and set up BNET and the world server. However When i launch the cilent and login the client posts the message "you have been disconnected form the server"

**Current behaviour:**

No login to cilent

**Expected behaviour:**

Logon to cilent
**Steps to reproduce the problem:**

I expect I am missing something from the setup
Step1: Run the wow.exe (15595) patched
try to login using created bnet account

**TC rev. hash/commit:** 

TrinityCore rev. bc84e6371e98 2020-02-03 20:34:04 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** WIN64

**Comment by Ovahlord** [comment]
You need to patch a CLEAN wow.exe with the connection patcher. The old patched exe files no longer work with this version. The patcher need to patch the exe. as well as install the bnet authentication modules.

**Comment by SuperSmelly** [comment]
Any idea where I could get a clean wow.exe. I cannot install from the disk i own

**Comment by Ovahlord** [comment]
No and I wont link any downloads here for legal reasons. This is not a support section here. The issue tracker is for actual issues that can be reproduced and can be fixed and not for setup questions
