### ISSUE TITLE
auth & characters database migration from current 3.3.5a to 4.3.4

### ISSUE THREAD

**Issue by kruchor** [The-Cataclysm-Preservation-Project/TrinityCore#306]
Hi there,

Not a proper bug issue there.

Do you know if database conversor from 3.3.5a to 4.3.4 are going to be upgraded ? It doesn't seem to work anymore. I've started to make some conversion but i'd like to avoid to make some work twice.

Thx!

**Comment by Ovahlord** [comment]
not supported and not planned to change anytime soon
