### ISSUE TITLE
DB/Auth: Applying new update fails on "incorrect datetime value"

### ISSUE THREAD

**Issue by TQPS** [The-Cataclysm-Preservation-Project/TrinityCore#309]
**Description:**

New DB change is failing on datetime value in Updates table

**Current behaviour:**

CHANGEME Tell us what happens.
```
Updating Auth database...
>> Applying update "2021_12_31_00_auth.sql" 'D5B6B38'...
mysql: [Warning] Using a password on the command line interface can be insecure.♪◙ERROR 1292 (22007) at line 19: Incorrect datetime value: '0000-00-00 00:00:00' for column 'timestamp' at row 11♪◙
Applying of file 'C:/Servers/Trinity/sql/updates/auth/4.3.4/2021_12_31_00_auth.sql' to database 'auth' failed! If you are a user, pull the latest revision from the repository. If you are a developer, fix your sql query.
Could not update the Login database, see log for details.
```

**Expected behaviour:**

Table should update

**Steps to reproduce the problem:**

(After Core built in dev and moved to dedicated server)
1. Git pull
2. Run SQL
3. Run Bnetserver
4. Run Worldserver (error occurs)

**TC rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  
TrinityCore rev. 7cdac9bd9ec0 2021-12-31 19:01:15 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** 
Windows 7 x64

**Comment by Ovahlord** [comment]
what's your mysql version?

**Comment by TQPS** [comment]
```
mysql  Ver 8.0.22 for Win64 on x86_64 (MySQL Community Server - GPL)
```

**Comment by Ovahlord** [comment]
```
>> Applying update "2021_12_31_00_auth.sql" 'D5B6B38'...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Applied 1 query. Containing 1 new and 69 archived updates.
```

can't reproduce

**Comment by TQPS** [comment]
I'll fix it manually then apply the updates.
