### ISSUE TITLE
[Spell/Priest] Penance Heal does not target non-caster friendly units

### ISSUE THREAD

**Issue by dolph1nn** [The-Cataclysm-Preservation-Project/TrinityCore#317]
**Description:**

When casting Penance as a Priest with a friendly player targeted, it is cast on you instead of your target.

**Current behaviour:**

Penance heals the caster instead of a friendly healable target.

**Expected behaviour:**

Penance should heal the caster's target, not the caster.

**Steps to reproduce the problem:**

http://cata.cavernoftime.com/spell=47540
1. Create a Priest and learn Penance.
2. Cast Penance on a friendly healable target (e.g a player).
3. Observe that you are healing yourself instead of your target.

**TC rev. hash/commit:** 

TrinityCore rev. cf29d9416155+ 2022-01-10 22:18:45 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  434.22011

**Operating system:** Server 2019 x64

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/86d84437320c808e7699b388b36c566eef3ba000
