### ISSUE TITLE
crash Murozond CancelSpellMissiles

### ISSUE THREAD

**Issue by gtestdev** [The-Cataclysm-Preservation-Project/TrinityCore#320]
**Description:**

crash in murozond encounter - end time
https://gist.github.com/gtestdev/06ee657f9cfa67c547957832f40117c2
I think this happens when two or more players click hourglass at the same time

**Current behaviour:**

crash

**Expected behaviour:**

don't crash

**Steps to reproduce the problem:**

1. For easy reproduce steps init encounter
2. do .reload all when hourglass can be clickable
3. spam hourglass clicking it
demo: https://imgur.com/ZSCrvFs

**TC rev. hash/commit:** 

[08:52:38] TrinityCore rev. 83456ed8533d 2022-01-14 21:40:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)
[08:52:38] Online players: 1 (max: 1)
[08:52:38] Active connections: 1 (max: 1) Queued connections: 0 (max: 0)
[08:52:38] Server uptime: 20 Second(s).
[08:52:38] Update time diff: 1.

**TDB version:**  TDB 434.22011

**Operating system:** Debian10

**Comment by Ovahlord** [comment]
Crashlog. You know the drill.

**Comment by Ovahlord** [comment]
How have you been able to click it again? The object becomes unselectable on activation.

**Comment by gtestdev** [comment]
due to .reload all used in the demo, you have a lapse time to do things with "lag server"
I imagine that if two or more players click at the same time the same thing can happen

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/db769f5e520257d0c8f941eab2511ee80bf818f0
