### ISSUE TITLE
ruRU client can't connect to the worldserver! ruRU DBC Files can't load!

### ISSUE THREAD

**Issue by BrexyS** [The-Cataclysm-Preservation-Project/TrinityCore#322]
**Description:**

hi all! looks like Cata support only English lang
I set in worldconf DBC.Locale = 8
and worldserver doesn't run, I reextracted dbc files from ruRU client,the same problem exist
I can login only using english client

**Current behaviour:**

I have enUS Client and ruRU client
When I set up enUS in Config.wtf , I can log in
so, I changed enUS to ruRU in Config.wtf and can't connect
WoW-64.exe the same pached
so, I changed ruRU to enUS in Config.wtf back
now I can't connect using enUS client !  I found intresting thing! when I changed Config.wtf  and set  SET locale "ruRU" I can't connect and got error ( Connection lost), but more intresting thing is that after this connection error SET portal "127.0.0.1" dissapear from Config.wtf, that's why I can't logIn again using SET locale "enUS"

When I set DBC.Locale = 8 in worldserver.conf file I can't run worldserver.exe and got error! I checked all DBC.Locale versions, that's my test result:

DBC.Locale = 1 good
DBC.Locale = 2 good
DBC.Locale = 3 good
DBC.Locale = 4 good
DBC.Locale = 5 good
DBC.Locale = 6 good
DBC.Locale = 7 good
DBC.Locale = 8 bad

**Expected behaviour:**

worldserver must run with DBC.Locale = 8 and ruRU Client connect to the server

**Steps to reproduce the problem:**

1. get ruRU client or ruRU locale on enUS client
2. in Config.wtf SET locale "ruRU"
3. try login, you got Connection Error
4. close worldserver.exe, go to conf file, set DBC.Locale = 8
5. try run worldserver.exe, you got Error Unable to load db2/dbc files for ruRU locale specified in DBC.Locale config!

**TC rev. hash/commit:** 

TrinityCore rev. 81813c1c0bd2 2021-12-27 18:46:53 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  Last TDB version

**Operating system:** Windows 10 x64

![unknown](https://user-images.githubusercontent.com/98172950/150555944-a39340f4-160c-4553-a8b8-3a0eff12b7ff.png)
![unknown (1)](https://user-images.githubusercontent.com/98172950/150555982-075f5479-ac1e-4e0e-9fb8-eb5d379806f2.png)
![unknown (2)](https://user-images.githubusercontent.com/98172950/150556032-0ec3f838-6dde-4189-9474-03ae35aa3464.png)
![unknown (3)](https://user-images.githubusercontent.com/98172950/150556062-a92049af-6f7e-4d7e-9e10-798459a7bf3b.png)
![unknown (4)](https://user-images.githubusercontent.com/98172950/150556082-933601a0-669a-4d77-8ed2-a869dd57d061.png)

**Comment by BrexyS** [comment]
![image](https://user-images.githubusercontent.com/98172950/150556288-19562f64-c190-42c4-94f1-600e674858c8.png)

**Comment by BrexyS** [comment]
![image](https://user-images.githubusercontent.com/98172950/150556474-9529d179-bb8f-4376-a98f-43094dd483ef.png)

**Comment by BrexyS** [comment]
![image](https://user-images.githubusercontent.com/98172950/150556862-a1c5eed8-aa70-40a5-b096-fdef7ac19b94.png)

**Comment by BrexyS** [comment]
ok, result:
Only Russian localization and Client can't connect to the core

**Comment by BrexyS** [comment]
may be problem exist after this commit? https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/d077c920112861988725cb3b4c0e7cf81958201e#diff-cbee95ea767c4439743c06e66aa2ffa40c5adf25f8215dbeef9660d34706eb5f

**Comment by Ovahlord** [comment]
for starters: why do you post a repack issue here? You are obviously not using the original source.

**Comment by ReyDonovan** [comment]
@Ovahlord there are no problems with extracting data from all clients, including ruRU

**Comment by BrexyS** [comment]
![image](https://user-images.githubusercontent.com/98172950/150579114-7fc7beb0-9f31-4715-8ea7-45db1398d5ac.png)

DBC.Locale = 8 good )))

**Comment by BrexyS** [comment]
but still can't log in to ruRU client

**Comment by BrexyS** [comment]
![image](https://user-images.githubusercontent.com/98172950/150579484-715555ae-d0b6-45c0-8b63-986d7a52e3a9.png)

**Comment by Ovahlord** [comment]
translation please. can't read the error message at all

**Comment by BrexyS** [comment]
@Ovahlord  Connection with Server Lost

**Comment by Ovahlord** [comment]
![image](https://user-images.githubusercontent.com/18347559/150580757-94ad527d-7d39-4d84-a84d-e3004d2d164a.png)
works for me. can't reproduce

**Comment by BrexyS** [comment]
hmmm.. why ? in Conf.wtf I lost 
SET portal "127.0.0.1"  when have connection error, it's dissapear from conf

**Comment by Ovahlord** [comment]
you have to delete the realmlist.wtf from the data/ruRU folder.

**Comment by BrexyS** [comment]
@Ovahlord YES!! my hero))

![image](https://user-images.githubusercontent.com/98172950/150581890-491dcbd9-1567-4e69-af86-a52e9c193ba1.png)

**Comment by BrexyS** [comment]
thanks for the help and fix))) I close issue
