### ISSUE TITLE
Spell Rogue 1943 Rupture - ID - 8647 Expose Armor

### ISSUE THREAD

**Issue by StarlordDev** [The-Cataclysm-Preservation-Project/TrinityCore#324]
**Description:**

these spells are not increasing their duration time correctly, apparently the attr1 SPELL_ATTR1_FINISHING_MOVE_DURATION is implemented correctly but these spells do not have said ATTR1 implemented so they are not working as they should.

**Steps to reproduce the problem:**

1. create a rogue class character
2. .learn 1943 or .learn 8647
3. .cast 1752 on any training dummy or victim until completing the max number of combo points.
4. .cast 1943 or .cast 8647 on any training dummy or victim.

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/9da4acce08f225046c88125e6157397ff9f73b49

**TDB version:**  TDB 434.22011

**Operating system:** Windows 10 

 Note: 
Possible solution:
Modify spells by adding attr1 SPELL_ATTR1_FINISHING_MOVE_DURATION in SpellMgr.cpp

```cpp
// Rogue
ApplySpellFix({
    1943,  // Rupture
    8647  //  Expose Armor
}, [](SpellInfo* spellInfo)
{
    spellInfo->AttributesEx |= SPELL_ATTR1_FINISHING_MOVE_DURATION;
});
```

**Comment by Ovahlord** [comment]
f01012aac988a8c61c7df97bbe2ef70ee47c6db5
