### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Tommy-Traviline** [The-Cataclysm-Preservation-Project/TrinityCore#325]
I have the following problem compiling this project 

**
CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)
**

I'm using Ubuntu 18, and my cmake version is 3.22

**Comment by Ovahlord** [comment]
follow the issue template.
