### ISSUE TITLE
Problem with duplicate aura with same casterguid

### ISSUE THREAD

**Issue by gtestdev** [The-Cataclysm-Preservation-Project/TrinityCore#331]
**Description:**

if you enchant two weapon with same enchant and you get the two procs, by example warrior with titan grip or any class switching weapon when get the first enchant proc and after that you logout, you get a rollback player because:
```sql
2022-02-07_09:35:44 SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxduration, remaintime, remaincharges) VALUES (1636, 1636, 59620, 3, 3, 1, 400, -5, 0, 400, -5, 0, 15000, 5952, 0)
 [ERROR]: [1062] Duplicate entry '1636-1636-59620-3' for key 'PRIMARY'
2022-02-07_09:35:44 Transaction aborted. 176 queries not executed.
```

**Expected behaviour:**

this commit is needed for fix the issue: https://github.com/TrinityCore/TrinityCore/commit/be47254a4f7ac9fd0497477a597e2a09019561e9

**Steps to reproduce the problem:**

1. get any char with two weapons and same enchant in two weapons
2. get two proc enchant auras
3. logout and login

**TC rev. hash/commit:** 

TrinityCore rev. 83456ed8533d 2022-01-14 21:40:27 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Ovahlord** [comment]
can't reproduce. used a titan grip warrior, equipped two akirus weapons and applied two heartsong enchantments on each of the weapons. No rollback, no transaction issues.

**Comment by gtestdev** [comment]
you can easy reproduce it, you can follow this steps:
learn titan's grip
equip two weapons
.add 44493 10
enchant two weapons
.cheat cooldown
.mod rage 100000
go to dummie and spam whirlwind and get two enchant auras
logout and login
proof: https://imgur.com/fXPICcS

**Comment by Ovahlord** [comment]
issue has been resolved.
