### ISSUE TITLE
Error updating player movements when mounted.

### ISSUE THREAD

**Issue by StarlordDev** [The-Cataclysm-Preservation-Project/TrinityCore#336]
**Description:**

Hello! This issue is a bit confusing as I don't know if it's a core issue or a client issue. Apparently when a player mounts or dismounts the other players will look at the player making strange movements (as if they were lag). The latency and FPS are working fine.

https://imgur.com/uuWh8IZ

**Steps to reproduce the problem:**

1. Login with 2 accounts.
2. learn flying skills.
3. use any mount with 1 of the characters.

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/ba4df11ab8172ca9c2b1c3bd8bb540a47a087d77

**Operating system:** Windows 10 x 64

**Comment by DevPrimeR** [comment]
I think it is solved with this commit:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/3c88782b8743f02a5799da314340238c24780c3b
update the project.
