### ISSUE TITLE
CMake Error 

### ISSUE THREAD

**Issue by JadeCore** [The-Cataclysm-Preservation-Project/TrinityCore#337]
CMake Error: Cannot open file for write: C:/Program Files/CMake/bin/CMakeCache.txt.tmp
CMake Error at CMakeLists.txt:11 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 3.8.0

Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: C:/Program Files/CMake/bin/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. C:/Program Files/CMake/bin/CMakeCache.txt
CMake Error: : System Error: Permission denied
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. C:/Program Files/CMake/bin/CMakeCache.txt
CMake Error: : System Error: Permission denied

Boost ≥  1.70 (Windows)
MySQL ≥ 5.7.37
CMake ≥  3.8.0 (Windows)
OpenSSL = 1.0.2d
MS Visual Studio ≥ 16.4 (2019) (Windows only)

**Comment by Ovahlord** [comment]
do you even read these errors? You cmake is obviously outdated.
