### ISSUE TITLE
cmake  error

### ISSUE THREAD

**Issue by JadeCore** [The-Cataclysm-Preservation-Project/TrinityCore#339]
CMake Warning at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:905 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1027 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1727 (_Boost_MISSING_DEPENDENCIES)
  dep/boost/CMakeLists.txt:46 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:905 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1027 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1727 (_Boost_MISSING_DEPENDENCIES)
  dep/boost/CMakeLists.txt:46 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:905 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1027 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1727 (_Boost_MISSING_DEPENDENCIES)
  dep/boost/CMakeLists.txt:46 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:905 (message):

**Comment by Ovahlord** [comment]
you're either not using the boost libaries and installed the source code instead or you forgot to set the boost_root variable. Please follow the trinitycore setup guide instead of posting your setup issues here.
