### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Tommy-Traviline** [The-Cataclysm-Preservation-Project/TrinityCore#340]
I am using Ubuntu 18 and when I go to compile the source it gives me the following error:

https://ibb.co/DMHXdNK

**Comment by Ovahlord** [comment]
need the full build log please

**Comment by Tommy-Traviline** [comment]
# cmake ../sources/ -DCMAKE_INSTALL_PREFIX=/home/$USER/servertr
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: SFMT enabled, SSE2 flags forced
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found Git: /usr/bin/git (found suitable version "2.17.1", minimum required is "1.7")

* TrinityCore revision   : 9c88c6ea9142 2022-03-17 22:41:58 +0100 (master branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /home/root/servertr
* Install libraries to   : /home/root/servertr/lib

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test STD_HAS_WORKING_WREGEX
-- Performing Test STD_HAS_WORKING_WREGEX - Success
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.71") found components: system filesystem thread program_options iostreams
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for MADV_FREE
-- Looking for MADV_FREE - found
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1") found components: Crypto SSL
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Detected epoll polling method
-- Looking for include file ifaddrs.h
-- Looking for include file ifaddrs.h - found
-- Looking for include file sys/uio.h
-- Looking for include file sys/uio.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Maelstrom
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

-- Configuring done
-- Generating done
-- Build files have been written to: /home/cloud/build

**Comment by Ovahlord** [comment]
Not your cmake log, your entire build log. Apparently there is a compile error somewhere. And please post these things as pastebin oder gist file

**Comment by Tommy-Traviline** [comment]
Sorry, I'll upload it in a moment

**Comment by Tommy-Traviline** [comment]
https://pastebin.com/akVsMis9

**Comment by Ovahlord** [comment]
these are only warnings so you should change your built settings to not abort when warnings occur

**Comment by Tommy-Traviline** [comment]
I already changed the settings And it keeps giving me the same error
