### ISSUE TITLE
The server is set up successfully, but the client cannot log in.

### ISSUE THREAD

**Issue by fengzi3209** [The-Cataclysm-Preservation-Project/TrinityCore#341]
echo y | rd /s "Cache"
echo SET realmlist "127.0.0.1" > Data\zhTW\realmlist.wtf
echo SET realmlist "127.0.0.1" > Data\enTW\realmlist.wtf
echo SET realmlist "127.0.0.1" > Data\zhCN\realmlist.wtf
echo SET realmlist "127.0.0.1" > Data\enCN\realmlist.wtf
echo SET realmlist "127.0.0.1" > Data\enUS\realmlist.wtf
echo SET realmlist "127.0.0.1" > realmlist.wtf
start wow.exe
goto end

I'm using a Taiwanese client and can't log in. The server is running normally. I don't know why. If my method is wrong, please specify the specific login method. thank you.

I use software to translate English, sorry.

**Comment by Ovahlord** [comment]
set realmlist is no longer used. Read https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Setup-and-troubleshooting-for-connecting
