### ISSUE TITLE
Worgen quest Moonfire (14283)

### ISSUE THREAD

**Issue by ReyDonovan** [The-Cataclysm-Preservation-Project/TrinityCore#351]
kill credit was not counted when using spell Moonfire

fix:
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=35118 AND `id`=5;
INSERT INTO `smart_scripts` VALUES
(35118, 0, 5, 0, 8, 0, 100, 0, 8921, 0, 0, 0, 0, 33, 44175, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On spell Moonfire (8921) hit - Caster: Give kill credit Spell Practice Credit (44175)');

**Comment by ReyDonovan** [comment]
hm
https://www.wowhead.com/quest=14283/moonfire
patch 4..0.3

**Comment by Ovahlord** [comment]
The quest probably got changed between MoP and WoD as it's obsolete in Legion and according to the comments, you can see that it originally was indeed Rejuvenation.
