### ISSUE TITLE
GameObjectModel created twice for transport

### ISSUE THREAD

**Issue by Lordron** [The-Cataclysm-Preservation-Project/TrinityCore#362]
**Description:**

CreateModel is called twice for MapTransport.
First call in Transport::CreateTransport https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/game/Entities/Transport/Transport.cpp#L308

second one
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/game/Entities/Transport/Transport.cpp#L546

**Expected behaviour:**

second call can be safely removed

**Comment by Ovahlord** [comment]
that's going to be solved once I merge my transport branch
