### ISSUE TITLE
Installation instructions incomprehension.

### ISSUE THREAD

**Issue by f3rret** [The-Cataclysm-Preservation-Project/TrinityCore#365]
**Description:**

Installation instructions incomprehension.

**Current behaviour:**

I follow installation instructions on trinitycore.info:

git clone -b master https://github.com/The-Cataclysm-Preservation-Project/TrinityCore.git
git pull origin master
and so on

low level areas at Kalimdor and EK have some wrong quest, Outland and Northrend works well, Cataclysm areas quests is broken about 50%

when i don't do  
git pull origin master

low level areas have some wrong, Outland and Northrend work very bad, but Cataclysm areas seems to work much better

**Expected behaviour:**

Which way is correct? May be there is some steps to provide optimal working world

**TDB version:**  
TDB 434.22011

**Operating system:** 
Ubuntu 21.10

**Comment by Ovahlord** [comment]
there isn't.
