### ISSUE TITLE
Connection to bnetserver times out.

### ISSUE THREAD

**Issue by bottmint** [The-Cataclysm-Preservation-Project/TrinityCore#368]
**Description:**

Cannot connect to bnetserver despite having followed the steps to patch vanilla exes outlined in the wiki. All ports are opened in the host computer's firewall. All auth modules list in this comment are present [(https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/29#issuecomment-582175050)] and patched.

**Current behaviour:**

The client stays on "Connecting" until it times out. The client connection log contains 
`8/2 21:34:26.510  Login program=WoW platform=Wn64 locale=enUS
8/2 21:34:26.538  Component WoW.Wn64.15595
8/2 21:34:26.560  Component WoW.base.15595
8/2 21:34:26.588  Component WoW.enUS.15595
8/2 21:34:26.610  Component WoW.enUS.15595
8/2 21:34:26.638  Component Tool.Win.0
8/2 21:35:00.333  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
8/2 21:35:00.362  Connecting to 192.168.1.10:1119
8/2 21:39:01.386  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
8/2 21:39:01.468  Disconnected from 192.168.1.10`
Grunt is in the log, despite using a battlenet account created in the worldserver when trying to log in.
The server log shows 
`Battlenet::ModuleInfo Locale EU, ModuleId 851C1D2EF926E9B9A345A460874E65517195129B9E3BDEC7CC77710FA0B1FAD6, DataSize 321, Data 001CDB2D60E7254AE01B712E9C91F1C6E00BA728C43F620DB8EB66A70D618F61327B1264AD679438213951A42D529544DF3D32CA492DD57C03F85DF5E1E716239D100B6557E47DFACF146956DBD9E1E8B041E5AD0D86C92EE7DD55E24DEBC4400E0FEA2F366BC8163F622F5E147229CC3B291B018689B1F559E90A3CD4E8A16E5BF929BB5528144F0E54FEEB1E92420496AE9F34168B5FE181E92240B5DC864914B1152FE1FEB1896DC683ABD7979FBD92997EF9CDA84A50D24817D227F6D24B6FE7576BC962ACEEFAECCCFE8C58575BA45AF857B0C3BA4FF2FA2430F5E04407EC6F2EAA4B864E984DB13D271F0CAA2AFDB79B74F0724B922BB965483FD4B47E13361FE46AB192D1278AB4EEC1FDBBA3C1F70519F180F157C8DFB9AF12FF5047E0E09038D63928185A8E0D508A04174367240E0055FFFEA079F3719475F5253FD5
Battlenet::ModuleInfo Locale EU, ModuleId C3A1AC0694979E709C3B5486927E558AF1E2BE02CA96E5615C5A65AACC829226, DataSize 512, Data E716F4F0A01EB9C032A6C1393356A4F766F067949D71023C0CFC0613718966EF814E65CC6EE70C432A7F8AFD8A062B52603A2697E851D231D72C0277614181D713369B1E8E4BEEAB72045A9AAD45F319DB918ECDDB83C8EF8B7510600D391D45E7FEC0BEEAE904A5F9FA620F1CCDAD699D84A4739CE669B5A551831E396214E13B4C88F573F5CDC784CD01530C086B674C03BEB66403A0F87ED17ABBB403DE54CF31BE828A20C566C22E4D4263AA77220B0644D99245345BCAC276EA06925EB984D664725C3CB757140AFE12E27CB996F17159B1057E9B58B78BBB5A139C9FF6215A0D250B75FC9DD435655DDEADCD6CFD84800792C146B3633188ECEB53D2038C185E0BD51A9E6C70FD38ADF530F8DF50FB62053C5E894897AB7DD65C7AC80665F18E7989BE6E30F15E939751123D6D8A44F033175301D15AAAD2AEA06FAC60BA4065846AE938F32B1CB15F16DC0E76792A7332346896048065D17C059899E1D2300E402BD0EA74265DA6A42B1C854E2470D7B21AE4A2DAE90E602A759B2CA0EE610B50D5389DB89335D5451FE76DD85B09FD5297D6F9EFB6C34CE885007F7DF20D6A524E0C3E772FA04B3DD2E014D3A337A790943DAD523CBB5453F4FDF8E74DFE361BD5F25AB31952B478148B570DF5762643F32B994FEC99A747E4A265A66EE84A53509EC285C84679606049314FC526C61B537AC8061C788F8B86F52208
[79 ms] SQL(p): UPDATE battlenet_accounts SET v = '0A99AC3F41ED0C3827B451B49F9942D40F00E55512C31FDF911CAB7F3962DEBB0014AD5ABAFDF6864DC40B62396624BD3FC7FB13BF77321955F4F53707B858D40BB54CA4CCBF96925DD7F4D51114A95E57771B36175432B9E51B653BE133A993A7F51D2B720A2E4AF7191F6F58EF9EA32B5F7C397BC56872C948F5A7158B32AE', s = '9D2316E7E1F55DF8037CD52D49CA323DDF4495522DA4513921389467AD64127B' WHERE email = 'TEST@TEST.COM'` Note that the client locale is set to enUS and was downloaded using the client downloader and the wowregeneration tool. 
**Expected behaviour:**

The client should either connect or be refused connection for a given reason (listed in the bnet log like connecting with an unknown account, or connecting from a client other than wow).

Should full logs be needed, I can provide them. Let me know what else may assist in diagnosing this issue.

**Steps to reproduce the problem:**

1. Clone master repo as of this date, compile the core using debian 11.  
2. Set up mysql databases.
3. After changing auth.realmlist to allow lan connections, attempt connection using patched client (32 or 64-bit) downloaded via the tools provided and using the patcher compiled on windows 10.
4. Attempt to connect to bnetserver with logging set to trace on bnetserver and observe the client attempting to connect, some ping pong between client/server, then eventually time out.

**TC rev. hash/commit:** 

TrinityCore rev. 45af6bbd4b34 2022-07-23 23:12:18 +0200 (master branch) (Unix, RelWithDebInfo, Static) (bnetserver)

Not sure where to pull this from, but it's using the Jan 8, 2022 TBD.

**Operating system:** Debian 11 (Bullseye)

**Comment by Ovahlord** [comment]
are you trying to run the client on linux?

**Comment by LukasVolgger** [comment]
Confirm on same rev. I'm also not able to connect to bnet server on win 11.

**Comment by micckkk** [comment]
Confirm on same rev. I'm also not able to connect to bnet server on win 10.

**Comment by bottmint** [comment]
> are you trying to run the client on linux?

The client is being run on windows 10.

**Comment by micckkk** [comment]
@bottmint server run on win10, client run on win10,Same One PC

**Comment by micckkk** [comment]
`Quote Originally Posted by Alistar View Post
[https://github.com/The-Cataclysm-Pre...ct/TrinityCore](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore)
This, best open source for cataclysm right now
Angry
Quote Originally Posted by blackmetalz View Post
This, best open source for cataclysm right now
Ya, but patcher won't work, so this live and dev. sources useless.`
from AC-WEB.ORG

**Comment by Ovahlord** [comment]
In the end, it's always the user not knowing how things work. The reasons why the connection fails are listed in the wiki. These are the only possible reasons.

**Comment by LukasVolgger** [comment]
@Ovahlord Thanks for the information!  According to the wiki, I installed it and it seems that others cannot clearly read the necessary step in the wiki either.  Here it would be great if you could tell us where exactly we can find it or please change the wiki to be clearer.  Btw thanks for the great project!

**Comment by bottmint** [comment]
@Ovahlord Care to tell me which step I missed? The step about patching the clean client files (both 32 and 64-bit clients are patched, launcher is not in the folder)? Or is it the auth modules (all 4 are present, going off the comment in another issue) which are successfully patched by the connection patcher? Or perhaps it's the set portal hostip line in the Config.wtf (which is set with patchlist being set to localhost.) So, what step am I missing, exactly? I've patched and repatched multiple times, with and without removing the auth modules and letting the patcher download them. I'm using battlenet accounts created with bnetaccount create. So, what step could I have possibly misread? 

Let's break this down, step by step, per the steps outlined in the wiki regarding connection issues;

1. I am using battlenet accounts.
2. I patched and renamed the dlls and exes using the provided connection patcher, which reports success for every patch it applies.
3. The auth files stated as necessary are present in the relevant directories.
4. I am not using realmlist.wtf, I am using Config.wtf with "set portal "hostip"" as the very first line.
5. I do not have the launcher in the directory, so I do not get invalid version errors.
6. All pertinent ports are open in the host firewall, I can clearly see connection attempts in the bnetserver console.
7. I obtained the full client utilizing the clientdownloader and wowregeneration as provided under this organization.
8. I have the correct information in wow.mfil, and it is marked read-only by windows.
9. I have changed the realmlist IP in the auth database to allow connection from clients on the same LAN.
10. Once again, clean client obtained using the tools your organization provided, and patched using the connection patcher built from source.

Honestly, did you even read anything beyond the title of the issue? It certainly feels like you didn't, especially since you asked what the client OS was, which was evident by the Wn64 strings. I've already covered that I've followed all the steps. I have spent hours trying to resolve this on my own. I don't see how you can mark this as resolved when it is not resolved at all.

**Comment by funjoker** [comment]
@bottmint is the server running on the same machine or another?

**Comment by bottmint** [comment]
Client and host machines are separate. The server is being hosted from a debian 11 box, the client is being run on windows 10. @funjoker

**Comment by funjoker** [comment]
@bottmint can you host a session on your local machine and try to connect to it :)

**Comment by bottmint** [comment]
@funjoker I attempted to host and join on my local machine, and it exhibited the same behavior. I couldn't get the bnetserver to show the trace log like I had it on the linux host, but a valid account attempting to connect results in a timeout, but an invalid account attempting to connect immediately gets rejected.

**Comment by funjoker** [comment]
@bottmint that's weird, since i do not run into this issue at all :/
Would you mind sending connection.log from your wow?

PS: Are you in the discord channel ?

**Comment by LukasVolgger** [comment]
I'm also having big troubles to connect. I tried everything described in the wiki or previous issues at this topic.

**Comment by funjoker** [comment]
> I'm also having big troubles to connect. I tried everything described in the wiki or previous issues at this topic. The client downloader does not work because 404 error. I have now found a full client from ManGOS but the patcher crashes when running.

possible that your firewall is blocking the download? Do you have net core version installed quoted in readme and release info?

**Comment by LukasVolgger** [comment]
![image](https://user-images.githubusercontent.com/55922592/183259434-2eb5d1dd-8a5d-4034-84ad-6ff165e1133a.png)

**Comment by bottmint** [comment]
> @bottmint that's weird, since i do not run into this issue at all :/ Would you mind sending connection.log from your wow?
> 
> PS: Are you in the discord channel ?

I was unaware there was a discord server for this project, but I am on discord (bottmint#0344) if you'd like to reach out there. I can certainly upload the connection log
[connection.log](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/9275522/connection.log)
.

**Comment by funjoker** [comment]
> ![image](https://user-images.githubusercontent.com/55922592/183259434-2eb5d1dd-8a5d-4034-84ad-6ff165e1133a.png) i deactivated my firewall.
> 
> Crashlog: https://gist.github.com/LukasVolgger/7ef5f0ef6d1bac8638e00e3bb5529166

ok its blizzard server which is dead. will switch to the last CDN which is alive. Gimme 1 min

**Comment by funjoker** [comment]
> ![image](https://user-images.githubusercontent.com/55922592/183259434-2eb5d1dd-8a5d-4034-84ad-6ff165e1133a.png) i deactivated my firewall.
> 
> Crashlog: https://gist.github.com/LukasVolgger/7ef5f0ef6d1bac8638e00e3bb5529166

https://github.com/The-Cataclysm-Preservation-Project/ClientDownloader/releases/tag/1.2

**Comment by funjoker** [comment]
> > @bottmint that's weird, since i do not run into this issue at all :/ Would you mind sending connection.log from your wow?
> > PS: Are you in the discord channel ?
> 
> I was unaware there was a discord server for this project, but I am on discord (bottmint#0344) if you'd like to reach out there. I can certainly upload the connection log. [connection.log](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/9275522/connection.log)

https://discord.com/invite/NevNbcagJX

**Comment by funjoker** [comment]
> > @bottmint that's weird, since i do not run into this issue at all :/ Would you mind sending connection.log from your wow?
> > PS: Are you in the discord channel ?
> 
> I was unaware there was a discord server for this project, but I am on discord (bottmint#0344) if you'd like to reach out there. I can certainly upload the connection log. [connection.log](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/9275522/connection.log)

this actually sounds like mising .auth | unpatched data | corrupted data

Did you patch your client on the system you are using? or did you copy wow from another PC where i was patched alreay?

**Comment by bottmint** [comment]
@funjoker I patched on the client PC that I'm using. I've verified that all 4 auth modules are in place on this machine, per your comment in another issue, and I've tried letting the patcher download them, as well as grabbing the auth modules hosted in the authmodules repo.

**Comment by funjoker** [comment]
@bottmint i added you on DC Kisshu is my name there

**Comment by bottmint** [comment]
Apologies for being slow to respond today, a package upgrade left my build environment in a bad way and I was working to resolve that. I added you on DC, feel free to contact me there as you'd like.

**Comment by funjoker** [comment]
You have to download all modules by yourself. https://github.com/The-Cataclysm-Preservation-Project/AuthModules/tree/master/Windows The path must be exactly the same "C:/ProgramData/Blizzard Entertainment/Battle.net/Cache/..." as represented in the repository.

Also added it to the wiki.

**Comment by bottmint** [comment]
@funjoker Can confirm with no changes other than the additional modules you added, connection works properly. I'm not sure if the patch tool was unable to download all the required modules, but as it's resolved, I suppose it's a moot point. Thank you for looking into it and resolving the issue.

**Comment by bottmint** [comment]
That is unfortunate, but thankfully, it was brought to attention and can be worked around. Thanks again for your time!

**Comment by micckkk** [comment]
@funjoker you idiot!
there are still a lot of people can't connect ,but you like close same topics!
