### ISSUE TITLE
Brother Sammuel - Missing trainer entry 

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#37]
**Description:**

Brother Sammuel - Missing trainer entry

Inserted Trainer entry to npc:
Brother Sammuel:
https://classic.wowhead.com/npc=925/brother-sammuel

**Fix:**

DELETE FROM `gossip_menu_option_trainer` WHERE `MenuId` = '4663' AND `TrainerId` = '168';
INSERT INTO `gossip_menu_option_trainer` (`MenuId`, `OptionIndex`, `TrainerId`) VALUES
('4663', '0', '168');

**Comment by Ovahlord** [comment]
That's not a good trainer ID that you have picked here. Low level trainers most have a different trainer menu with only the first few spells available to them. In this case   168 is the correct one

**Comment by DevPrimeR** [comment]
Oh I understand, thanks for the clarification, I have already corrected it.
