### ISSUE TITLE
Prepatched client?

### ISSUE THREAD

**Issue by jwh1981** [The-Cataclysm-Preservation-Project/TrinityCore#372]
I apologize ahead of time if this has been asked/answered before. Is there anyway to pre-patch the client to make it easy to give to friends, etc. to play on my server?

I assume I need to provide the auth files, put them in the correct folder, and have them patch the client on their own. Is there an alternative?

**Comment by funjoker** [comment]
Legally I do not recommend to provide downloads.

**Comment by Ovahlord** [comment]
Because of legal reasons sharing copyrighted material, such as the game client, let alone manipulating it via patcher is leadin to nothing but trouble. So your only solution is to do it yourself.
