### ISSUE TITLE
can't connect to bnetserver

### ISSUE THREAD

**Issue by Ziedden** [The-Cataclysm-Preservation-Project/TrinityCore#373]
**Description:**

I can't connect to my bnet server.

**Current behaviour:**

I have setup on my private root server the full TC 4.3.4 server from this repository. I have patched the Client with the connection patcher but it dosn'T work. I have create a bnet Account and a normal Account and have link they with `bnet link`

**Expected behaviour:**

here the connection.log
9/11 22:46:03.379  Login program=WoW platform=Win locale=deDE
9/11 22:46:03.457  Component WoW.Win.15595
9/11 22:46:03.506  Component WoW.base.15595
9/11 22:46:03.555  Component WoW.deDE.15595
9/11 22:46:03.604  Component WoW.enGB.15595
9/11 22:46:03.653  Component Tool.Win.0
9/11 22:46:03.913  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
9/11 22:46:04.063  Connecting to 91.59.169.45:1119
9/11 22:46:04.209  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
9/11 22:46:04.263  Disconnected from 91.59.169.45
9/11 22:46:04.318  Client initiated Disconnect from 91.59.169.45
9/11 22:46:04.374  Client initiated Disconnect from 91.59.169.45
9/11 22:46:04.444  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
9/11 22:46:04.494  Login program=WoW platform=Win locale=deDE
9/11 22:46:04.542  Component WoW.Win.15595
9/11 22:46:04.590  Component WoW.base.15595
9/11 22:46:04.640  Component WoW.deDE.15595
9/11 22:46:04.690  Component WoW.enGB.15595
9/11 22:46:04.738  Component Tool.Win.0
9/11 22:46:09.436  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
9/11 22:46:09.683  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_SERVER_DOWN 
9/11 22:46:09.736  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 

**Steps to reproduce the problem:**

1. The port is open and the ip its my.
2. nmap show's open bnet
3. Patch my client with connection_patcher

**TC rev. hash/commit:** 

(the newest i post it at the morning my terminal dons't work at the moment)

**TDB version:**  Newest (11.09.2022)

**Operating system:** Linux Mint 20

**MY Basic Language:** German sorry for my English ;-)

**Comment by micckkk** [comment]
@Ovahlord you idiot!
there are still a lot of people can't connect ,but you like close same topics!
