### ISSUE TITLE
Clients that cannot be verified?

### ISSUE THREAD

**Issue by pklloveyou** [The-Cataclysm-Preservation-Project/TrinityCore#375]
**Description:**
I use wikis
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Setup-and-troubleshooting-for-connecting#can-i-play-with-my-patched-wowexe
Display error when logging in Clients that cannot be verified
1. Using ClientDownloader 1.2
2. wowregeneration
3. ![image](https://user-images.githubusercontent.com/18535853/193606565-fcb60348-a7ca-4438-a05d-f143b49c7d02.png)
4. delete realmlist.wtf use 
5. WTF\Config.wtf SET portal "127.0.0.1"
6. AuthModules 
![image](https://user-images.githubusercontent.com/18535853/193605863-e54cfd1a-27fd-4195-baf9-f914dafd9f31.png)
7. ![image](https://user-images.githubusercontent.com/18535853/193606060-fc336270-b2a8-4e5a-a0f3-f6a40c628d29.png)
8. Battle.net-64_Patched.dll AND Wow-64_Patched.exe Modified as Wow-64.exe AND Battle.net-64.dll
9. ![image](https://user-images.githubusercontent.com/18535853/193606926-e12db100-a633-4ad9-a628-fbbf7589f273.png)
10. ![image](https://user-images.githubusercontent.com/18535853/193607003-5473cfaa-254b-441b-b6dc-9555b897b184.png)
11. Display error when logging in Clients that cannot be verified

**Comment by funjoker** [comment]
PS can you try a different locale too? :)

**Comment by pklloveyou** [comment]
en?

**Comment by pklloveyou** [comment]
I'll try it now en

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/193611029-64052d8c-2eb2-464b-baeb-345cd7de16fc.png)
Is that right? Do need to download the client again?

**Comment by pklloveyou** [comment]
Does it have anything to do with here? https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/pull/374

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/193613877-09f6bb5d-4d5c-4a67-b96f-69b8861b2f27.png)
Which do I test?

**Comment by pklloveyou** [comment]
Successfully, I only kept the following files
![image](https://user-images.githubusercontent.com/18535853/193616484-a3670888-3c3f-4c23-ac54-4681d8fce0b6.png)
