### ISSUE TITLE
Item_Template i not found in DB

### ISSUE THREAD

**Issue by Dokman** [The-Cataclysm-Preservation-Project/TrinityCore#38]
**Description:**

The latest release doesn't have inside item_template

**Current behaviour:**

In mysql_stmt_prepare() id: 56, sql: "SELECT entry FROM item_template WHERE name = ?"
Table 'cata_world.item_template' doesn't exist

**Expected behaviour:**

Load the DB

**Steps to reproduce the problem:**

1. Download DB
2. Run Worldserver for first time

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/25b18096d81fbccdf77086863427ccea52182d6b

**TDB version:**  TDB 434.20021

**Operating system:** Win10

**Comment by DevPrimeR** [comment]
Hi,
With the last changes inserted in the DB item_template is no longer in World but in the new database called Hotfixes, you must download the new database, create the hotfixes and world database again and insert the updates.

Release:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/releases/tag/4.3.20021

**Comment by Dokman** [comment]
Thanks
