### ISSUE TITLE
Original client Bad patching

### ISSUE THREAD

**Issue by Dokman** [The-Cataclysm-Preservation-Project/TrinityCore#39]
**Description:**

So i am using an original client, when i patch it, tells me that all is patched, then when i connect setting in Config.WTF SET portal "127.0.0.1" it tell's me that it can't verify the build version.

![image](https://user-images.githubusercontent.com/2290904/75400440-92bd3680-58ff-11ea-98cc-cb77df288066.png)

![WoWScrnShot_022720_012250](https://user-images.githubusercontent.com/2290904/75400492-b54f4f80-58ff-11ea-888e-cc0137db285e.jpg)

![image](https://user-images.githubusercontent.com/2290904/75401509-ac13b200-5902-11ea-949d-08b9ddb7d344.png)

![image](https://user-images.githubusercontent.com/2290904/75401519-b0d86600-5902-11ea-8478-339deb801b83.png)

**Current behaviour:**

When i go to log into game it tell's me that isn't the same version

**Expected behaviour:**

Log in, into the character selector/ creator

**Steps to reproduce the problem:**

1 . Original client
2. Patch 32 bit executable
3. Login in game

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/25b18096d81fbccdf77086863427ccea52182d6b

**TDB version:**  TDB 434.20021

**Operating system:** Win10

**Comment by Dokman** [comment]
i found a fix in a issue

`UPDATE `battlenet_components` SET `Build`=1807 WHERE `Program`='Tool' AND `Platform`='Win';`

**Comment by Ovahlord** [comment]
You have to delete the original launcher in this case. The tools will be checked on login and since the launcher is useless anyways  deleting it will do the trick

**Comment by Dokman** [comment]
okay thanks
