### ISSUE TITLE
Error: invalid template argument for 'std :: get'; a constant expression was expected at compile time.

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#40]
Hi.
I have a doubt about the requirements to install the project in windows 10 x64, I am using the recommended ones on the project page and these give me an error when compiling.

`
25> with
25> [
25> TypedHandler = bool (__cdecl *) (ChatHandler *, const char *)
25>]
25> src \ server \ game \ Chat \ ChatCommands \ ChatCommand.h (243): error C2975: '_Idx': invalid template argument for 'std :: get'; a constant expression was expected at compile time (compiling source file \ src \ server \ scripts \ Commands \ cs_ahbot.cpp)
25> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ VC \ Tools \ MSVC \ 14.10.25017 \ include \ array (511): note: see the statement of '_Idx' (compiling source file src \ server \ scripts \ Commands \ cs_ahbot.cpp)
25> \ src \ server \ game \ Chat \ ChatCommands \ ChatCommand.h (243): error C2975: 'Idx': invalid template argument for 'std :: get'; a constant expression was expected at compile time (compiling source file \ src \ server \ scripts \ Commands \ cs_ahbot.cpp)
25> C: \ local \ boost_1_66_0 \ boost / array.hpp (445): note: see the 'Idx' statement (compiling source file src \ server \ scripts \ Commands \ cs_ahbot.cpp) `

The problem occurs in 64-bit windows, I'm not sure if the problem only happens to me or is an error in general.

Programs:
Visual Studio 17
Windows 10 (64 bits)
Cmake 3.16.2 x 64
OppenSSL 1.0.2 u x 64
Boost 1.66 x 64
MySql 5.7 x 64

Thank you.
```

**Comment by Ovahlord** [comment]
what are your cmake settings?

**Comment by DevPrimeR** [comment]
Ok I'll try with more updated versions, thanks.
