### ISSUE TITLE
Trinity Core Fails To Build

### ISSUE THREAD

**Issue by FuzzyWuggzy** [The-Cataclysm-Preservation-Project/TrinityCore#400]
**Description:**

When trying to compile Trinity Core make fails at about 92%

**Current behaviour:**

Make terminates with Error 2.

**Expected behaviour:**

Make completes building successfully.

**Steps to reproduce the problem:**

1. Clone master branch. 
2. Extract OpenSSL 1.1.1 lib and devel packages to cloned dir.
3. mkdir build and cd into it
4. run `cmake .. -DOPENSSL_LIBRARIES=../lib64 -DOPENSSL_INCLUDE_DIR=../include -DCMAKE_INSTALL_PREFIX=/home/$USER/server`
5. run `make`

**Operating system:** Fedora 37

Make log: [make.txt](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/11580681/make.txt)

**Comment by Ovahlord** [comment]
Your operating system sounds kinda weird. Mind to offer some insight regarding your compiler version?

**Comment by FuzzyWuggzy** [comment]
Here they are:
```
~/server/bin >>> make --version                                                
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

~/server/bin >>> gcc --version                                                 
gcc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/server/bin >>> cmake --version                                               
cmake version 3.26.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).                                                              

~/server/bin >>> clang --version                                        
clang version 15.0.7 (Fedora 15.0.7-2.fc37)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by FuzzyWuggzy** [comment]
Thank you, commit https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/67fa80392e8cb250ff028aa8db3a6f1cc9f18f09 fixed that issue for me, but it's now failing at 100% while `Linking CXX executable worldserver`. It's not a huge deal if I'm the only one having this issue, I have the server running in a Debian VM so please take your time while there's more important tasks.

Here's the make log, it's a big one this time: [make.txt](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/11616516/make.txt)

Thank you again.

**Comment by Ovahlord** [comment]
just some deprecation warnings. they should be fixed now. your build fails not because of errors but because of warnings

**Comment by Ovahlord** [comment]
As of b17585fc55e8e2bb4d39de82eafec1bd73496d14 clang, gcc and msvc have been building successfully, hence this issue is solved.
