### ISSUE TITLE
Server crash when do quest Further Concerns

### ISSUE THREAD

**Issue by manhdv** [The-Cataclysm-Preservation-Project/TrinityCore#401]
**Description:**
In Goldshire, Marshal Dughan will give you quest Further Concerns. After accept the quest, you have option to use Stormwind Charger by talking to him "I wish to ride the Stormwind Charger, sir". Now if you click on that option, you will be teleport to your inn, and when you comback to Marshal Dughan, there is Stormwind Charger next to him. If you ride that Stormwind Charger, server will crash.

**Current behaviour:**
Server crash. Crash log: https://gist.github.com/manhdv/4d28dbcddb49ee914dffaaa95e1197fc

**Expected behaviour:**
N/A

**Steps to reproduce the problem:**

1. Accept quest Further Concerns from Mashal Dughan in Goldshire
2. Talk to Mashal Dughan and chose option: "I wish to ride the Stormwind Charger, sir"
3. Come back to him and ride Stormwind charger

**TC rev. hash/commit:** 

TrinityCore rev. 26a3a05e2915 2023-05-19 23:45:43 +0200 (master branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB_full_hotfixes_434.22011_2022_01_09.sql

**Operating system:** Window 11

**Comment by Ovahlord** [comment]
There has been a bug which caused players false being teleported to the starting area which has been fixed but other than that I was unable to reproduce any crash
