### ISSUE TITLE
(Starting Troll Area/ Echo Isles): Invisible Water

### ISSUE THREAD

**Issue by BeSilentBob** [The-Cataclysm-Preservation-Project/TrinityCore#403]
**Description:**

Invisible Water on Echo Isle (Troll starting Area).

PS: Sorry I'm new to GitHub. If I mess anything up in the bug report please excuse this ...

**Current behaviour:**

Starting with a troll results in the water not properly rendered. If you are underwater however it will be rendered correctly and everything works. Leaving the water results in the same bug with the water not being visible.

**Expected behaviour:**

Water should be visible.

**Steps to reproduce the problem:**

1. Map bug: Invisible water
2. Create a new Character: Troll
3. Look behind you and you see floating ships and no water.

**TC rev. hash/commit:** 

TrinityCore rev. 82e27f72afec 2023-06-14 16:52:23 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB434.22011

**Operating system:** Debian 11

**Comment by Ovahlord** [comment]
Cannot reproduce. Water is a fully clientside thing which is unfixable. So either you broke your client or your client is no longer fully compatible with your graphics API (too modern hardware/drivers)
![image](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/assets/18347559/9789bc9d-17b9-4dc2-819b-72a39dd045c3)
