### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by lemondsMs** [The-Cataclysm-Preservation-Project/TrinityCore#404]
Hi

 I suggest you put a section where the general information of this project is included and be updated.

This topic will be of great help to those who are new to this project

As :
The amount of progress of Instance Cataclysm
The amount of progress of Battlegrounds
The amount of progress of talent heroes
And ...

**Comment by Ovahlord** [comment]
I don't see any real benefit from this. The only people who do care about these informations are folks who are looking for source codes that don't require any further effort to fix. Developers will test things on their own and improve based on what they find and observe. Percentages also don't represent the actual state of things for one may always find something missing or broken.
