### ISSUE TITLE
compile error, ProducerConsumerQueue.h need to update

### ISSUE THREAD

**Issue by chinahvc** [The-Cataclysm-Preservation-Project/TrinityCore#405]
**Description:**
sorry for bad english.
After add support for openssl3, build can not work.
I found same issue :https://github.com/TrinityCore/TrinityCore/commit/85d5f4bc0683d99cfaab244a8f0355b463f93267.
when replace the file with which in trinitycore master branch, it does work. Would you please check for it?

**Current behaviour:**
when build came an error.

In file included from /home/maciek/old_home/trinitycore/src/server/database/Database/DatabaseWorker.cpp:20:
/opt/trinitycore/src/common/Threading/ProducerConsumerQueue.h:38:30: error: expected unqualified-id before ‘)’ token

**Expected behaviour:**

complete 100%

**Steps to reproduce the problem:**

1. Step 1 git clone the code.
2. Step 2 cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/trinity-server-ctm/ -DWITH_WARNINGS=1 -DUSE_SCRIPTPCH=1 -DTOOLS=0 -DUSE_COREPCH=1 -DSCRIPTS=static
3. Step 3 make -j3
4. Setp 4 wait, it will show

**TC rev. hash/commit:** 

TrinityCore rev. 774323691147+ 2023-07-18 08:26:27 +0200 (master branch) (Unix, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** Ubantu 22.04

**Comment by Ovahlord** [comment]
done. please try again

**Comment by chinahvc** [comment]
I removed and rebuild folder build. Compile ok, Bnetserver login ok, can't login worldserver. worldserver logs below:CMSG_CONNECT_TO_FAILED
----------------------------------------
RBACData::ExpandPermissions: Expanded: 
S->C: [Player: Account: 1] [SMSG_AUTH_RESPONSE 0x5DB6 (23990)]
S->C: [Player: Account: 1] [SMSG_ADDON_INFO 0x2C14 (11284)]
S->C: [Player: Account: 1] [SMSG_CLIENTCACHE_VERSION 0x2734 (10036)]
S->C: [Player: Account: 1] [SMSG_TUTORIAL_FLAGS 0x0B35 (2869)]
C->S: [Player: Account: 1] [CMSG_READY_FOR_ACCOUNT_DATA_TIMES 0x2B16 (11030)]
WORLD: CMSG_READY_FOR_ACCOUNT_DATA_TIMES
S->C: [Player: Account: 1] [SMSG_ACCOUNT_DATA_TIMES 0x4B05 (19205)]
C->S: [Player: Account: 1] [CMSG_ENUM_CHARACTERS 0x0502 (1282)]
C->S: [Player: Account: 1] [CMSG_REALM_SPLIT 0x2906 (10502)]
CMSG_REALM_SPLIT
S->C: [Player: Account: 1] [SMSG_REALM_SPLIT 0x2714 (10004)]
Loading char guid GUID Full: 0x0000000000000001 Type: Player Low: 1 from account 1.
Loading char guid GUID Full: 0x0000000000000004 Type: Player Low: 4 from account 1.
S->C: [Player: Account: 1] [SMSG_ENUM_CHARACTERS_RESULT 0x10B0 (4272)]
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Account: 1] [CMSG_LOADING_SCREEN_NOTIFY 0x2422 (9250)]
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Account: 1] [CMSG_PLAYER_LOGIN 0x05B1 (1457)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
[Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] failed to connect 5 times to world socket, aborting login
S->C: [Player: Account: 1] [SMSG_CHARACTER_LOGIN_FAILED 0x4417 (17431)]
C->S: [Player: Account: 1] [CMSG_LOADING_SCREEN_NOTIFY 0x2422 (9250)]
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Account: 1] [CMSG_READY_FOR_ACCOUNT_DATA_TIMES 0x2B16 (11030)]
C->S: [Player: Account: 1] [CMSG_REALM_SPLIT 0x2906 (10502)]
WORLD: CMSG_READY_FOR_ACCOUNT_DATA_TIMES
S->C: [Player: Account: 1] [SMSG_ACCOUNT_DATA_TIMES 0x4B05 (19205)]
CMSG_REALM_SPLIT
S->C: [Player: Account: 1] [SMSG_REALM_SPLIT 0x2714 (10004)]
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]

**Comment by Ovahlord** [comment]
That's most likely a port problem.  We use two Sessions so make sure these are open. However, thats out of scope of this issue. Check the repo Wiki for that

**Comment by chinahvc** [comment]
> That's most likely a port problem. We use two Sessions so make sure these are open. However, thats out of scope of this issue. Check the repo Wiki for that

updated from an old and worked version, conf files unchange. New version goes wrong when page load 90%. so may not ports problem. anyway i'll check it again and comment an new issue.
