### ISSUE TITLE
Login ok, can't enter world

### ISSUE THREAD

**Issue by chinahvc** [The-Cataclysm-Preservation-Project/TrinityCore#406]
**Description:**
After click 'enter world' button, progress loaded aroud 90%，client [told](url) ‘world server is down’. 
Updated from the old but playable version, with conf files unchange. 
I checked ports 1118, 1119, 8086, 8087(changed 2 ports for wlk version) from client PC with telnet ; in server with command netstat, all of them can be reached. Tryed Trinitycore 10 (ports 1119, 8086, 8087, 8081), it can be played.

![issue1 fw](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/assets/139999520/80f3bd14-f549-4c25-b7b6-171be8f3e5e0)

![issue2 fw](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/assets/139999520/7422e93e-8a1c-4975-8ed5-c05c327f1245)

**Current behaviour:**

S->C: [Player: Account: 1] [SMSG_AUTH_RESPONSE 0x5DB6 (23990)]
S->C: [Player: Account: 1] [SMSG_ADDON_INFO 0x2C14 (11284)]
S->C: [Player: Account: 1] [SMSG_CLIENTCACHE_VERSION 0x2734 (10036)]
S->C: [Player: Account: 1] [SMSG_TUTORIAL_FLAGS 0x0B35 (2869)]
C->S: [Player: Account: 1] [CMSG_READY_FOR_ACCOUNT_DATA_TIMES 0x2B16 (11030)]
WORLD: CMSG_READY_FOR_ACCOUNT_DATA_TIMES
S->C: [Player: Account: 1] [SMSG_ACCOUNT_DATA_TIMES 0x4B05 (19205)]
C->S: [Player: Account: 1] [CMSG_ENUM_CHARACTERS 0x0502 (1282)]
C->S: [Player: Account: 1] [CMSG_REALM_SPLIT 0x2906 (10502)]
CMSG_REALM_SPLIT
S->C: [Player: Account: 1] [SMSG_REALM_SPLIT 0x2714 (10004)]
Loading char guid GUID Full: 0x0000000000000001 Type: Player Low: 1 from account 1.
Loading char guid GUID Full: 0x0000000000000004 Type: Player Low: 4 from account 1.
S->C: [Player: Account: 1] [SMSG_ENUM_CHARACTERS_RESULT 0x10B0 (4272)]
C->S: [Player: Account: 1] [CMSG_REQUEST_ACCOUNT_DATA 0x6505 (25861)]
C->S: [Player: Account: 1] [CMSG_REQUEST_ACCOUNT_DATA 0x6505 (25861)]
C->S: [Player: Account: 1] [CMSG_REQUEST_ACCOUNT_DATA 0x6505 (25861)]
WORLD: Received CMSG_REQUEST_ACCOUNT_DATA
RAD: type 0
S->C: [Player: Account: 1] [SMSG_UPDATE_ACCOUNT_DATA 0x6837 (26679)]
WORLD: Received CMSG_REQUEST_ACCOUNT_DATA
RAD: type 2
S->C: [Player: Account: 1] [SMSG_UPDATE_ACCOUNT_DATA 0x6837 (26679)]
WORLD: Received CMSG_REQUEST_ACCOUNT_DATA
RAD: type 4
S->C: [Player: Account: 1] [SMSG_UPDATE_ACCOUNT_DATA 0x6837 (26679)]
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Account: 1] [CMSG_LOADING_SCREEN_NOTIFY 0x2422 (9250)]
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Account: 1] [CMSG_VIOLENCE_LEVEL 0x7816 (30742)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_KEEP_ALIVE 0x0015 (21)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
C->S: [Player: Account: 1] [CMSG_PLAYER_LOGIN 0x05B1 (1457)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
S->C: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [SMSG_CONNECT_TO 0x0942 (2370)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: 192.168.2.50 [CMSG_PING 0x444D (17485)]
S->C: 192.168.2.50 [SMSG_PONG 0x4D42 (19778)]
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
BattlegroundMgr: UPDATING ARENA QUEUES
C->S: [Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] [CMSG_CONNECT_TO_FAILED 0x2533 (9523)]
[Player: Logging in: GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1] failed to connect 5 times to world socket, aborting login
S->C: [Player: Account: 1] [SMSG_CHARACTER_LOGIN_FAILED 0x4417 (17431)]
C->S: [Player: Account: 1] [CMSG_CANCEL_TRADE 0x731E (29470)]
Received unexpected opcode [CMSG_CANCEL_TRADE 0x731E (29470)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 1]
C->S: [Player: Account: 1] [CMSG_LOADING_SCREEN_NOTIFY 0x2422 (9250)]
C->S: [Player: Account: 1] [CMSG_READY_FOR_ACCOUNT_DATA_TIMES 0x2B16 (11030)]
WORLD: CMSG_READY_FOR_ACCOUNT_DATA_TIMES
S->C: [Player: Account: 1] [SMSG_ACCOUNT_DATA_TIMES 0x4B05 (19205)]
C->S: [Player: Account: 1] [CMSG_REALM_SPLIT 0x2906 (10502)]

**Expected behaviour:**

Enter world.

**Steps to reproduce the problem:**

1. Step 1 update to latest version.
2. Step 2 login
3. Step 3 click 'enter world' button

**TC rev. hash/commit:** 

TrinityCore rev. 4b7aefb05ba8 2023-07-21 01:05:41 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** ubantu 22.04

**Comment by Ovahlord** [comment]
The client failed to establish the 2nd worldsession. Did you patch a clean original wow.exe file with our connection patcher? We do not support login with older patched exe files (the ones that most pservers use nowadays)

**Comment by chinahvc** [comment]
I compile it again with code downloaded  10 minutes ago, still same error.(VS community 2022)

**Comment by chinahvc** [comment]
> The client failed to establish the 2nd worldsession. Did you patch a clean original wow.exe file with our connection patcher? We do not support login with older patched exe files (the ones that most pservers use nowadays)

After change ports to default 8085 8086, it works properly, then change to 8086 and 8087,it also works. no clue what happened , close for now. Thanks for your help.
