### ISSUE TITLE
[CORE/Battlefield] Tol'Barad Issues

### ISSUE THREAD

**Issue by JustZerooo** [The-Cataclysm-Preservation-Project/TrinityCore#408]
**Description:**

There are some issues i have been identified myself.

- Doors not closing on battlefield begin ![https://i.imgur.com/Nq986hU.png](https://i.imgur.com/Nq986hU.png)
- Capture status not updated on client (Status bar) ![https://i.imgur.com/zR7Eu8v.png](https://i.imgur.com/zR7Eu8v.png)

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Start server, enable WG / BF in config
2. login into gameserver and teleport to bf
3. results

**TC rev. hash/commit:** 

TrinityCore rev. 4b7aefb05ba8+ 2023-07-21 01:05:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  CHANGEME Version of the TrinityCore database

Windows 11

**Comment by Ovahlord** [comment]
TolBarad isn't supported right now so whatever is going on there, expect it to be boken

**Comment by JustZerooo** [comment]
Reference https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/413
