### ISSUE TITLE
Dockerfile new OpenSSL libraries

### ISSUE THREAD

**Issue by Snify89** [The-Cataclysm-Preservation-Project/TrinityCore#414]
**Description:**

Docker-Image doesn't find SSL libraries

**Current behaviour:**

bnetserver: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
worldserver: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

**Expected behaviour:**

Processes should find the libraries and start properly

**Steps to reproduce the problem:**

Pull docker image.
use bnetserver/worldserver as entrypoint

**Comment by Ovahlord** [comment]
openssl 3 ships libssl-3 on their own and are not distributed by the build. so you gotta fix your environment.

**Comment by Snify89** [comment]
> openssl 3 ships libssl-3 on their own and are not distributed by the build. so you gotta fix your environment.

Thanks for the answer.
I am not quite an expert.
Are you suggesting to download and compile OpenSSL 3 into that docker image prior?

Is the current master branch compiled only with v3 support? What about 1.1? And isn't OpenSSL3 distributed with Ubunutu 22.04 (or any/some other distribution that can be used)?

**Comment by funjoker** [comment]
please retry after 1bae56ff8b626b963478fb35e4a44ada6c412597

**Comment by Snify89** [comment]
> please retry after [1bae56f](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/1bae56ff8b626b963478fb35e4a44ada6c412597)

Thank you. I have just pulled the newest image and it seems to work now.

**Comment by funjoker** [comment]
Nice :) thanks for the feedback
