### ISSUE TITLE
Docker-Image Database not working

### ISSUE THREAD

**Issue by Snify89** [The-Cataclysm-Preservation-Project/TrinityCore#416]
**Description:**

/home/circleci/project/src/server/database/Database/DatabaseWorkerPool.cpp:70 in DatabaseWorkerPool FATAL ERROR:
Used MySQL library version (8.0.33 id 80033) does not match the version id used to compile TrinityCore (id 80034). Search on forum for TCE00011.
Segmentation fault

**Current behaviour:**

Does not start authserver/worldserver

**Expected behaviour:**

should start

**Steps to reproduce the problem:**

pull latest docker image
bind mount regular config to /home/circleci/project/bin/check_install/etc
change database connection accordingly
start mysql 8.1.0-1
execute create_mysql.sql for user and databases
bind mount world db files to home/circleci/
start worldserver

Edit: Same error comes with latest MariaDB 

**TC rev. hash/commit:** 

https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/1bae56ff8b626b963478fb35e4a44ada6c412597

**Operating system:** Linux

**Comment by Ovahlord** [comment]
well, according to your error, your mysql installation is 8.0.33 and the image has been built with 8.0.34 so your server is outdated. Are you sure that you're running mysql 8.1?

**Comment by Snify89** [comment]
> well, according to your error, your mysql installation is 8.0.33 and the image has been built with 8.0.34 so your server is outdated. Are you sure that you're running mysql 8.1?

To my understanding the circle-ci environment is different from the docker base-image.
The binaries are compiled with a different header version.
The error occurs even if no database is attached (e.g. socket or tcp-protocol)
I have tried different versions of mysql/mariadb.

**Comment by Snify89** [comment]
The docker image has:
libmysqlclient-dev (8.0.33-0ubuntu0.22.04.2).

The problem can be fixed by updating the library:
apt update; apt-get install libmysqlclient-dev

Could you please add this in the dockerfile?

**Comment by funjoker** [comment]
well i saw circle ci used 4.3.4 image instead of master image to build the docker file.
I deleted the deprecated image and i am rerunning the compile now. hopefully it will take the correct image now

**Comment by funjoker** [comment]
Try again after 8403605

**Comment by Snify89** [comment]
> Try again after [8403605](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/84036055910cfe4d619bf0ca791083abee858cdd)

It works great now.
Thank you very much!

**Comment by Snify89** [comment]
> Try again after [8403605](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/84036055910cfe4d619bf0ca791083abee858cdd)

It works great now.
Thank you very much!
