### ISSUE TITLE
The Forge of Souls Portcullis in 

### ISSUE THREAD

**Issue by cyberpro98** [The-Cataclysm-Preservation-Project/TrinityCore#417]
Hi, i am having an ISSUE with the gate/door  The Forge of Souls Portcullis in Frozen Halls (ICECROWN) .
I should could click on it and to open it but I cannot click on it it has no circle on it to click ...
This is what is in DB in gameobject_template
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `RequiredLevel`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES (201759, 0, 9173, 'The Forge of Souls Portcullis', '', '', '', 2.04, 0, 86, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 15595);

I am running 
TrinityCore rev. 4d8da1fcf30f 2023-08-21 17:03:54 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/31
