### ISSUE TITLE
BlizzCMS now support Cataclysm Preservation Project

### ISSUE THREAD

**Issue by sayghteight** [The-Cataclysm-Preservation-Project/TrinityCore#42]
**Description:**

Hi Ovahlord, I am the founder of BlizzCMS (WoW-CMS.com) some users informed me of your project, and that there were problems for other CMS in the creation of accounts.

I do not know if this is the best method to contact you, through an Issue, but I wanted you to know that my CMS now supports your project and that it is completely free with good support through discord.

**Comment by funjoker** [comment]
Future note: Ovahlord is also at TC IRC, TC Discord and Modcraft
