### ISSUE TITLE
Issue with multiple locale dbc files on Linux

### ISSUE THREAD

**Issue by Snify89** [The-Cataclysm-Preservation-Project/TrinityCore#426]
I have the full client with all 14 locales installed.
When I extract the dbc files, it creates subdirectories in the dbc folder for each locale.
I think there is a bug, cause inside the dbc/[locale] folder the files are named:
DBFilesClient\LiquidType.dbc

I think DBFilesClient is an extra subdirectory but it's included in the filename.
I am using Linux.

This causes mmaps to fail cause it cant find any dbc files.

How are the different (locale) dbc files related to mmaps?
Do I really need different mmaps for each locale?

**Comment by Ovahlord** [comment]
The MMaps extractor needs dbc files to identify liquids and phased terrain.
As for your dbc naming issue: I can't reproduce the issue on windows at all so I cannot test for solutions right now.

**Comment by Snify89** [comment]
> The MMaps extractor needs dbc files to identify liquids and phased terrain. As for your dbc naming issue: I can't reproduce the issue on windows at all so I cannot test for solutions right now.

It's a Linux issue I guess.
The following helps snippet helps me to rename the dbc files:

`for i in $(find /trinity/data/dbc | grep 'DBFilesClient\\')
do
filename=$(basename "$i")
sudo mv "$i" "$(dirname "$i")"/"${filename:14}"
done
`

**Comment by Shauren** [comment]
3cfee9d3d05ffd1dea368dcf8f9a27ac91a6a01c broke it, more specifically the changes in ExtractDBCFiles

**Comment by Snify89** [comment]
> ExtractDBCFiles

I see. Thank you for the investigation.
So are the dbc files even complete and is renaming (removing DBFilesClient\), a valid workaround until this is fixed?
