### ISSUE TITLE
Bnetserver - Port 3724 missing?

### ISSUE THREAD

**Issue by Snify89** [The-Cataclysm-Preservation-Project/TrinityCore#427]
I am trying to setup TrinityCore with the docker image cataclysmpreservationproject/trinitycore:master

Everything seems to work just fine, except the bnetserver does NOT listen on Port 3724, hence, I can't login with the client.

The worldserver listens successfully on port 8085/8086 but bnetserver listens to only 1118/1119

Where is the port 3724? Is this somehow replaced?

I also ran bnetserver as sudo inside the container with no luck. I also changed the default 1119 port in the bnetserver.conf to 3724 with no luck?

Am I missing something?

PS.: How can I debug the bnetserver with the bnetserver.conf (Logger)?

**Comment by funjoker** [comment]
3724 is legacy ports, which is 3.3.5a and old TC 4.3.4 (with authserver).

**Comment by Ovahlord** [comment]
![image](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/assets/18347559/e88b2a7b-fbec-4c28-8dec-6fd06ffa32c8)
 perhaps you should read your configs first
