### ISSUE TITLE
bnetserver and worldserver cannot be synchronized

### ISSUE THREAD

**Issue by LordGrim1121** [The-Cataclysm-Preservation-Project/TrinityCore#435]
Just like the title, bnetserver and worldserver cannot synchronize. Both sides show waiting for 127.0.0.1:1118 connection, but I have both opened. I really can't find a solution.

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/31

**Comment by LordGrim1121** [comment]
But my 1118port is not connected? I don’t know what to do. Am I missing some environment?
