### ISSUE TITLE
Unhandled procs / procs with trigger spell id = 0

### ISSUE THREAD

**Issue by zxyjwy** [The-Cataclysm-Preservation-Project/TrinityCore#44]
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 82899 proc, because the spell does not have an entry in Spell.dbc.

**Comment by CrossUCI** [comment]
i have the same with
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 78204 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 87100 proc, because the spell does not have an entry in Spell.dbc.

**Comment by funjoker** [comment]
When reporting an issue, please follow the simple template.
This makes it far easier to identify, reproduce and fix the issue.
If you do not follow the simple template, we are not able to reproduce or confirm the issue.

**Comment by zxyjwy** [comment]
Sorry, my English is not very good, I don't know how to express!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Runico"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 凌晨1:49
收件人:&nbsp;"The-Cataclysm-Preservation-Project/TrinityCore"<TrinityCore@noreply.github.com&gt;;
抄送:&nbsp;"``JACKY``"<182222654@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [The-Cataclysm-Preservation-Project/TrinityCore] Unhandled procs / procs with trigger spell id = 0 (#44)





 
When reporting an issue, please follow the simple template.
 This makes it far easier to identify, reproduce and fix the issue.
 If you do not follow the simple template, we are not able to reproduce or confirm the issue.
