### ISSUE TITLE
smart_action_jump_to_pos

### ISSUE THREAD

**Issue by Neromas** [The-Cataclysm-Preservation-Project/TrinityCore#47]
Description:

smart_action_jump_to_pos dont let the npc jump.

Current behaviour:

The npc dont jump with action type 97 + target type 8

Expected behaviour:
The NPC should jump if the SAI with Actiontype 97 get used.

Steps to reproduce the problem:

1. create a SAI script with actiontype 97
2. let a npc use this script.

TDB version: TDB 434.20021

Operating system: Win10

**Comment by Ovahlord** [comment]
jump_to_pos does not use the target parameter for coordinate based destinations. Just use the target_x y z values.

**Comment by Neromas** [comment]
I dont use the Target parameter. I used target type 8 for Cords and target xyzo

**Comment by Ovahlord** [comment]
And that's your mistakes. You don't need a target type for pure coordinates.
