### ISSUE TITLE
Client login issues

### ISSUE THREAD

**Issue by xXBentRealityXx** [The-Cataclysm-Preservation-Project/TrinityCore#48]
**Description:**

I am able to login to the server just fine, but when I send other users the Wow_patched.exe and Battle.net.dll files it doesn't work. They type in their credentials, press enter, WoW freezes for about 5 seconds and they says "You have been disconnected".

Side note: these people are using the same full client as me, I'm just sending them the updated patched files.

**Current behaviour:**

Only I am able to login, nobody else.

**Expected behaviour:**

Everyone should be able to login.

**Steps to reproduce the problem:**

1. Send the patched client files to someone with a full client.
2. Have them put the files in their WoW 4.3.4 install.
3. Have them run Wow_patched.exe and try to login.

**TC rev. hash/commit:** 

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  TDB 434.20021

**Operating system:** Win 10 x64

**Comment by funjoker** [comment]
You are missing the .auth files

**Comment by funjoker** [comment]
C:\Program Data\Blizzard Entertainment\Battle.net

Give them these folder

**Comment by funjoker** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information

Check „I cannot login“

**Comment by Ovahlord** [comment]
I recommend to read what the code inside of the connection patcher does. It downloads the authentication modules and patches them and puts them into your programm data folder. If your friends wanna join, you have to make sure that they have the modules as well.

**Comment by xXBentRealityXx** [comment]
Ah my bad, I even had them use the connection_patcher themselves before and no dice, but I'll send them that folder. Thanks for the replies

**Comment by Ovahlord** [comment]
Also keep in mind that the core uses two ports now instead of one since we use the 2nd connection just like the TC master branch does. So check your firewall as well.

**Comment by xXBentRealityXx** [comment]
I gave them the folder and even did everything myself through AnyDesk, put Blizzard Entertainment folder in ProgramData, set the portal, then ran the Wow_patched.exe. Still same issue, freezes for a few seconds then "You have been disconnected"

**Comment by xXBentRealityXx** [comment]
Firewall is configured correctly as well

**Comment by Ovahlord** [comment]
Did he really use a clean wow .exe. It has to be a clean one that has not been patched before. Also what does your bnet or worldserver return on failed logins?

**Comment by xXBentRealityXx** [comment]
Bnetserver and Worldserver haven't shown any signs of the other clients connecting. Wow.exe was not a fresh one because I have no idea where to find that, but it works perfect for me on localhost and when I connect to my server machine in germany

**Comment by funjoker** [comment]
Gimme screenshot of your wow folder.
And gimme connection log of your wow

**Comment by xXBentRealityXx** [comment]
> Gimme screenshot of your wow folder.
> And gimme connection log of your wow

Mine or theirs or both?

**Comment by xXBentRealityXx** [comment]
https://i.imgur.com/y1ji7a8.png

[connection(Mine).log](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/4340582/connection.Mine.log)
[connection(Theirs).log](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/files/4340583/connection.Theirs.log)

**Comment by Ovahlord** [comment]
A assume the locale of your guy is enGB, right? does he use any kind of client mods?

**Comment by xXBentRealityXx** [comment]
Yes we use enGB, and no client mods. We do all use a custom patch with dbc files in it, though that doesn't seem to matter for me as I can login fine

**Comment by xXBentRealityXx** [comment]
Update: We found out it keeps setting his portal to nothing. It basically just deletes the ip in the ""

**Comment by Ovahlord** [comment]
So if it's that it's not a core but a user problem.

**Comment by xXBentRealityXx** [comment]
How is it a user problem? Every time he runs Wow_patched.exe it deletes the IP in the SET portal line

**Comment by xXBentRealityXx** [comment]
I'm not trying to talk shit or anything, this is an amazing source. The only major problem I've encountered is the login thing

**Comment by funjoker** [comment]
We run a Testserver on Linux and we did never encounter this issue

**Comment by Ovahlord** [comment]
It's clearly caused by the user and is not related to the server software itself. If your friends portal keeps getting overwritten it's the client that does it. He might consider checking out his realmlist file because the realmlist.wtf can also affect the config.wtf file. Aka. delete it.
