### ISSUE TITLE
HandleGravityAck Opcode mover guid check for vehicles

### ISSUE THREAD

**Issue by zxyjwy** [The-Cataclysm-Preservation-Project/TrinityCore#49]
HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000006 Type: Player Low: 6 and should be GUID Full: 0xf1506ece0000000f Type: Vehicle Entry: 28366  Low: 15.

**Comment by funjoker** [comment]
When reporting an issue, please follow the simple template.
This makes it far easier to identify, reproduce and fix the issue.
If you do not follow the simple template, we are not able to reproduce or confirm the issue.

**Comment by zxyjwy** [comment]
Sorry, my English is not very good, I don't know how to express!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Runico"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 凌晨1:49
收件人:&nbsp;"The-Cataclysm-Preservation-Project/TrinityCore"<TrinityCore@noreply.github.com&gt;;
抄送:&nbsp;"``JACKY``"<182222654@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [The-Cataclysm-Preservation-Project/TrinityCore] HandleGravityAck Opcode mover guid check for vehicles (#49)





 
When reporting an issue, please follow the simple template.
 This makes it far easier to identify, reproduce and fix the issue.
 If you do not follow the simple template, we are not able to reproduce or confirm the issue.
