### ISSUE TITLE
leave a vehicle

### ISSUE THREAD

**Issue by Chronaa** [The-Cataclysm-Preservation-Project/TrinityCore#50]
If you leave a vehicle with the "leave" button you just stand in the air and yo ucan walk in the air like a "hovermode" ahead of  the ground. while you hover over the ground you can walk but not jump.

tested with ground vehicle like cannons and flying vehicle.

**Comment by Ovahlord** [comment]
follow the issue template and add more details.

**Comment by zxyjwy** [comment]
this  HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000006 Type: Player Low: 6 and should be GUID Full: 0xf1506ece0000000f Type: Vehicle Entry: 28366 Low: 15.

**Comment by Ovahlord** [comment]
Wintergrasp is not supported.
