### ISSUE TITLE
HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000027 Type: Player Low: 39 and should be GUID Full: 0xf150c0380000003a Type: Vehicle Entry: 49208  Low: 58.

### ISSUE THREAD

**Issue by zxyjwy** [The-Cataclysm-Preservation-Project/TrinityCore#51]
HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000027 Type: Player Low: 39 and should be GUID Full: 0xf150c0380000003a Type: Vehicle Entry: 49208  Low: 58.

The Deadmines

**Comment by zxyjwy** [comment]
fuck you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Runico"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 晚上9:11
收件人:&nbsp;"The-Cataclysm-Preservation-Project/TrinityCore"<TrinityCore@noreply.github.com&gt;;
抄送:&nbsp;"``JACKY``"<182222654@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [The-Cataclysm-Preservation-Project/TrinityCore] HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000027 Type: Player Low: 39 and should be GUID Full: 0xf150c0380000003a Type: Vehicle Entry: 49208  Low: 58. (#51)





 
Closed #51.

**Comment by funjoker** [comment]
@zxyjwy Please watch you language.

When reporting an issue, please follow the simple template.
This makes it far easier to identify, reproduce and fix the issue.
If you do not follow the simple template, we are not able to reproduce or confirm the issue.

**Comment by zxyjwy** [comment]
Sorry, my English is not very good, I don't know how to express!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Runico"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 凌晨1:48
收件人:&nbsp;"The-Cataclysm-Preservation-Project/TrinityCore"<TrinityCore@noreply.github.com&gt;;
抄送:&nbsp;"``JACKY``"<182222654@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [The-Cataclysm-Preservation-Project/TrinityCore] HandleGravityAckMessage: incorrect mover guid: mover is GUID Full: 0x0000000000000027 Type: Player Low: 39 and should be GUID Full: 0xf150c0380000003a Type: Vehicle Entry: 49208  Low: 58. (#51)





 
@zxyjwy Please watch you language.
 
When reporting an issue, please follow the simple template.
 This makes it far easier to identify, reproduce and fix the issue.
 If you do not follow the simple template, we are not able to reproduce or confirm the issue.
