### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by kazuke353** [The-Cataclysm-Preservation-Project/TrinityCore#52]
**Description:**

When i click the "Enter World" button most of the time my client gets stuck at the loading screen.

Worldserver reports this:
> TC>TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, MinSizeRel, Static) (worldserver-daemon) ready...
Opening muxer thread from inproc://bnetmgr to tcp://127.0.0.1:1118
[Player: Logging in: GUID Full: 0x000000000000000a Type: Player Low: 10, Account: 5] failed to connect 5 times to world socket, aborting login
Received unexpected opcode [CMSG_CANCEL_TRADE 0x731E (29470)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 5]

This is the first time i am logging in as well.

**Steps to reproduce the problem:**

1. Start worldserver
2. Log into your account
3. Click "Enter World"

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/b0e1c7100ecba3ed09caf89619ef91d2c97322a9
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, MinSizeRel, Static) (bnetserver)

**TDB version:**  TDB 434.20021

**Operating system:** Win 10

**Comment by funjoker** [comment]
No proper commit hash.
Are you using custom core or clean?

**Comment by kazuke353** [comment]
I am using a clean core
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/b0e1c7100ecba3ed09caf89619ef91d2c97322a9

**Comment by Ovahlord** [comment]
What wow.exe are you using?

**Comment by kazuke353** [comment]
A fresh download from Atlantiss.eu that i patched with connection_patcher.exe

**Comment by Ovahlord** [comment]
You cannot do that. You need a original wow.exe from a original retail client. You cannot patch a wow.exe from private servers.

**Comment by funjoker** [comment]
Hint: blizzard still provides the x64 client as download

**Comment by kazuke353** [comment]
@funjoker Can you check your email please?
