### ISSUE TITLE
Error to compile

### ISSUE THREAD

**Issue by DevPrimeR** [The-Cataclysm-Preservation-Project/TrinityCore#55]
Compile error in debian 9

CHANGEME Description of the problem or issue here.
When i compile on debian 9 the following error is generated:
src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:49:58: error: member access into incomplete type 'const SummonPropertiesEntry'
if ((summon->m_Properties && summon->m_Properties->Control != SUMMON_CATEGORY_WILD) || summon->IsPet())
^
/src/server/game/Entities/Creature/TemporarySummon.h:23:8: note: forward declaration of 'SummonPropertiesEntry'
struct SummonPropertiesEntry;

**TC rev. hash/commit:** 
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c9961e6a94b021d2c7bfef086ba9b694a4c2609a

**Operating system:** Debian 9

**Comment by Ovahlord** [comment]
Your source is outdated. These lines do not exist anymore
