### ISSUE TITLE
Unable to connect character

### ISSUE THREAD

**Issue by Dreaxxx** [The-Cataclysm-Preservation-Project/TrinityCore#56]
**Description:**

Cannot connect to server after character creation , the worldserver print this when i enable warden :

Prevented sending of [SMSG_WARDEN_DATA 0x31A0 (12704)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x6E37 (28215)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_SET_PROFICIENCY 0x6207 (25095)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x6E37 (28215)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_SET_PROFICIENCY 0x6207 (25095)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x6E37 (28215)] to non existent socket 1 to [Player: Account: 12]
Prevented sending of [SMSG_SET_PCT_SPELL_MODIFIER 0x0224 (548)] to non existent socket 1 to [Player: Account: 12]

And with the patch : 

WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 12 ('Furrazlhf159') address: ************

If warden not enabled , player is automatically disconnected after loading without message in the worldserver console.

**Current behaviour:**

Can't connect a character after creation

**Expected behaviour:**

Can connect character ^^

**Steps to reproduce the problem:**

1. Create a char
2. Try to connect this one

**TC rev. hash/commit:** 

914da12

**TDB version:**  TDB 434.20021 - 2020/02/21

**Operating system:** Linux debian 9

**Additionnal informations: ** Do you have a discord ? :O
I'm using French officiel client same for the data

**Comment by Ovahlord** [comment]
You are not using a correct wow.exe. You cannot use the standard private server wow.exe as we use the 2nd connection socket of the client. So you have to patch a original retail 4.3.4 exe with the connection patcher of this project.

**Comment by Dreaxxx** [comment]
Yes i already done that , and launched with the patcher.exe builded in my debian 9 machine

**Comment by Ovahlord** [comment]
You also have to make sure that the authentication modules in the programm data folder that are being downloaded by the patcher are being placed on the machine that runs the exe.

**Comment by Dreaxxx** [comment]
Yes , i'v find something who said the patcher isn't available for linux , maybe problem can be here ?

**Comment by Ovahlord** [comment]
Well, obviously if you are emulating a windows environment via wine you also have to make sure that the program data path is available. One of the older issues was about the tool crashing on linux but you don't seem to have that issue.

**Comment by Ldqtheone** [comment]
Ah no, I'm emulating and compiling on Linux and playing on windows

**Comment by Dreaxxx** [comment]
Ah no, I'm emulating and compiling on Linux machine but play on windows

**Comment by Ovahlord** [comment]
Well, that explains all then.When you patch the wow.exe with the connection patcher, it downloads and patches auth modules for the battle.net login. If you patch the exe files on a different system you also have to grab these auth files and put them on your windows machine

**Comment by Dreaxxx** [comment]
Yep already done , but i just seeing , have errors during patching in linux , and with the linux tool can't patch on windows , so i'm trying to recompile all on my windows machine to get the correct connect patcher.exe

**Comment by Dreaxxx** [comment]
I'v done all things to be good on Windows machine, no errors occurred when patching the wow.exe, but same thing when I try to log char in world after that.
I'v delete the realmlist and set portal in the config

**Comment by Ovahlord** [comment]
And you have used a clean wow.exe? With clean I mean a original retail exe file. (you can still download the 64 bit version from their forums)

**Comment by Dreaxxx** [comment]
When you mean original retail , it's original 4.3.4 exe ou retail bfa exe ? 
because i'v done with a no patched wow.exe from 4.3.4 virgin client , i can't with retail because Battle.net.dll seem's not exist in retail client

**Comment by funjoker** [comment]
Short instruction:

1. Get Wow.exe and battlenet.dll (unpatched Original) or wow-64.exe and Battle.net-64.dll (unpatched original)
2. Get connection-patcher.exe
3. move connection patcher to wow folder.
4. drag wow.exe or wow-64.exe on patcher
5. rename original wow exe and Original dll to whatever (wow-Original.exe)
6. rename wow-patched.exe and Battle.net-patched.dll to wow.exe and Battlenet.dll or the 64 equivalent to wow-64.exe and battlenet-64.dll
7. delete or rename Launxher

**Comment by Dreaxxx** [comment]
All of this points already done in order...

**Comment by Dreaxxx** [comment]
I can confirm, we can't build the connection-patcher in Linux actually and for me the wow64 patched doesn't work, only the 32.

Thanks for your help guys! And good job for the dev, I'm begginer in c++ of I find time to help you :)

**Comment by Mayhem121** [comment]
Sorry to open a post that has been closed already, but I also noticed the same problem and I have downloaded the unmodified, retail version from here:

http://us.media.battle.net.edgesuite.net/downloads/wow-installers/live/WoWLive-64-Win-15595.zip

https://i.imgur.com/uMvCnk1.png

I am able to login without warden set to 1, however it spams op code errors in the ws.exe.

Could you share the link where you found your retail version of 4.3.4?
