### ISSUE TITLE
DK / Quest: How To Win Friends And Influence Enemies

### ISSUE THREAD

**Issue by Chronaa** [The-Cataclysm-Preservation-Project/TrinityCore#65]
**Description:**

If you equip the 2 swords and auto attack the humans, every time the spell procs you get the error message that you cant do it while youre scilenced.

**Current behaviour:**

Everytime the spells of the swords procs you get a error message "you cant do that while youre scilenced"

**Expected behaviour:**

If the spell hits you have a chance to let a event starts to complete the Quest.

**Steps to reproduce the problem:**

1. Take the Quest How To Win Friends And Influence Enemies (ID 12720)
2. Equip the swords: ID: 39371) SpellID (52781)
3. start auto attacking the scarlet NPC´s arround there

**TC rev. hash/commit:** 

rev: c3fd5d2

**TDB version:**   TDB 434.20021 - 2020/02/21

**Operating system:** Win10

**Comment by Ovahlord** [comment]
893b80d0c468bbd54da8205a865151acce35c2bd
