### ISSUE TITLE
Unix compile

### ISSUE THREAD

**Issue by Naddley** [The-Cataclysm-Preservation-Project/TrinityCore#66]
**Description:**

Error getting on Unix with latest TC requirements.

[ 20%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/                                                                                                                                                             MySQLPreparedStatement.cpp.o
[ 20%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/                                                                                                                                                             MySQLThreading.cpp.o
1 error generated.
make[2]: *** [src/server/database/CMakeFiles/database.dir/build.make:162: src/se                                                                                                                                                             rver/database/CMakeFiles/database.dir/Database/MySQLConnection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1248: src/server/database/CMakeFiles/database                                                                                                                                                             .dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Current behaviour:**

Getting Error while compile the Source with TC requirements.

**Expected behaviour:**

Core should compile fine.

**Steps to reproduce the problem:**

1. pull Source
2. let your machine compile it

**TC rev. hash/commit:** 

commit e64a3bcd90d98f800026569b794f91e38bbdf0ae

**TDB version:**  TDB 434.20021 - 2020/02/21

**Operating system:** Debian10

**Comment by Ovahlord** [comment]
Please post a complete error log of the build process.

**Comment by Naddley** [comment]
CmakeError.log or is there a specific one for building process?

**Comment by Ovahlord** [comment]
The complete build log.

**Comment by Naddley** [comment]
https://pastebin.com/w3fyRNJc

**Comment by Ovahlord** [comment]
What's your mysql server version?

**Comment by Naddley** [comment]
Server version: 10.3.22-MariaDB-0+deb10u1 Debian 10

**Comment by Ovahlord** [comment]
Try again on latest rev please.

**Comment by Naddley** [comment]
Works now without problems. Thank You !
