### ISSUE TITLE
Unix restarter problem (Old bugg from Trinity)

### ISSUE THREAD

**Issue by Naddley** [The-Cataclysm-Preservation-Project/TrinityCore#67]
**Description:**

If you restart your worldserver and open it as fast as you can again, you will get a failed to initialize network error. You need to wait arround 45-60 sec until you can start your worldserver after a restart.

Trinity has the same bugg in 2017 and get fixxed it: 
https://github.com/TrinityCore/TrinityCore/issues/20032
https://github.com/TrinityCore/TrinityCore/issues/20069

**Current behaviour:**

Worldserver failed to connect to network after you restart your worldserver too fast.

**Expected behaviour:**

It should restart without problems

**Steps to reproduce the problem:**

1. start Worldserver on Unix
2. restart your Server
3. see in worldserver console that you get a network error

**TC rev. hash/commit:** 

commit 2e9f4285d93ad003feadbbb5c7f88a5561755dd9

**TDB version:**  TDB 434.20021 - 2020/02/21

**Operating system:** Unix Debian10

**Comment by Ovahlord** [comment]
fixes have been cherrypicked.
