### ISSUE TITLE
Spell - Dark Simulacrum (Death Knight)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#71]
**Description:**

Dark Simulacrum isn't copying spells correctly.

**Current behaviour:**

When you cast Dark Simulacrum on another player, and that player casts a spell _(that **can** be copied)_ it doesn't do anything but remove the aura from that player.

**Expected behaviour:**

Player casts Dark Simulacrum on another player/(NPC), then when said player/(NPC) casts next copy-able spell, it will allow the death knight to cast the same spell within a certain time frame.

**Steps to reproduce the problem:**

1. Create death knight and alternate account (preferably spell caster)
2. Bring your two characters together and /duel them.
3. Cast Dark Simulacrum on the other character
4. Cast a spell within the time frame of Dark Simulacrum.

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
78a6d8468960c88279515e8c59423f2db5832b0f
