### ISSUE TITLE
Spell - Shadowmeld (Night Elf Racial)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#74]
**Description:**

Shadowmeld has a few minor fixes needed.
(https://wow.gamepedia.com/Shadowmeld)

**Current behaviour:**

Shadowmeld does not remove combat immediately.
Shadowmeld does not wait for the cooldown to start while still in Shadowmeld.
Shadowmelded players can be seen from an unusually long distance.
[NEW]: Shadowmeld allows druid feral abilities that normally require Prowling to be casted while Shadowmelded.

**Expected behaviour:**

Shadowmeld should properly remove combat while fighting.
Shadowmeld should not begin it's cooldown until the player exits Shadowmeld.
Shadowmeld should not be seen beyond 10-12 yards. (Tested)
[NEW]: Shadowmeld should not let druid be able to cast 'Ravage' and 'Pounce'.

**Steps to reproduce the problem:**

1. Create a night elf character.
2. Create another character.
2. Duel each other and cast Shadowmeld on the night elf
4. Stand ontop of the player and slowly move away.
5. [NEW]: Cast Shadowmeld while in melee range of another character. [Druid only]

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by AGandrup** [comment]
> Shadowmeld does not remove combat immediately.

Can't seem to reproduce this, but then again this issue is pretty old, so chances are that it has been fixed already.
