### ISSUE TITLE
Spell - Pounce/Pounce Bleed (Druid)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#76]
**Description:**

Pounce applys Pounce Bleed and does not last for 18 second(s).

**Current behaviour:**

When using Pounce, it applys the Pounce Bleed but only lasts for approx. 8 seconds **_instead of_** 18 seconds AND the bleed is also subject to diminishing returns. (Unconfirmed if Intentional)

**Expected behaviour:**

Using pounce should apply the Pounce Bleed effect for 18 second(s).
Also the bleed is being affect by Diminishing Returns. 
 (The Stun is always subject to DR, I don't think the bleed is subject to DR.)

**Steps to reproduce the problem:**

1. Create a Druid.
2. Find an enemy to pounce.

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
![WoWScrnShot_050920_004050](https://user-images.githubusercontent.com/18347559/81454931-e1a00b80-918d-11ea-99a2-943583690b26.jpg)
The bleeding effect is working as intended with its full duration. About the diminishing return please find a valid article that confirms it.

**Comment by Core002** [comment]
Sorry I meant to add to this, that it only lasts 8 second(s) on **_players_**
