### ISSUE TITLE
Stat - Mastery (All classes)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#79]
**Description:**

Mastery not working on any classes

**Current behaviour:**

When equipping an item with mastery, the mastery does not increase.
It is somehow not being updated in the core from ITEM_MOD_MASTERY.

**Expected behaviour:**

Should properly update mastery percentage and apply spell aura.

**Steps to reproduce the problem:**

1. Create any class

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
This is not a bug. You have to learn the mastery spell at a class trainer before the mastery rating bonus rating is getting applied. Tested it, and it works as intended.
