### ISSUE TITLE
Spell - Arcane Missiles! (Mage)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#80]
**Description:**

Arcane Missiles! the proc [Spell: 79683] is procing I believe more than 40%.

**Current behaviour:**

Casting any damaging spell will proc this.
Casting Polymorph will proc this.

**Expected behaviour:**

Should only be 40% chance to proc this.

**Steps to reproduce the problem:**

1. Create a Mage.
2. Cast Ice Lance a few times.

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/scripts/Spells/spell_mage.cpp#L1598 Nope, the proc chance is explicitely 40% and I've tested it just now. There are plenty of casts where the proc did not fire off.

**Comment by Core002** [comment]
Ah okay. It just confused me because it was proc'ing from a non-offensive ability (polymorph)

**Comment by Ovahlord** [comment]
Polymorph actually is considered a offensive spell. It uses a damage class (damage class magic) which is considered offensive by default.

**Comment by Core002** [comment]
okay yeah that makes sense then.
