### ISSUE TITLE
Spell - T12 DPS 4P Bonus (Death Knight)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#90]
**Description:**

This [SpellProc](https://cata-twinhead.twinstar.cz/?spell=98996) does not trigger correctly when casting Obliterate OR Scourge Strike

**Current behaviour:**

Casting Obliterate OR Scourge Strike does not trigger this itemset spell proc.

**Expected behaviour:**

Should instantly deal 6% additional fire damage.

**Steps to reproduce the problem:**

1. Create a Death Knight.
2. Equip [this](https://cata-twinhead.twinstar.cz/?itemset=1000) itemset.
3. Cast Obliterate OR Scourge Strike

**TC rev. hash/commit:** 
TrinityCore rev. d3dd36c77612e0ea8e979a5e8c58c72660d71ae5

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
973d4a139a831724063d916e259f1749b7f8d1ad
