### ISSUE TITLE
Spell - T12 DPS 2P Bonus (Death Knight)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#91]
**Description:**

This [SpellProc](https://cata-twinhead.twinstar.cz/?spell=98970) is not granting any runic power / 5s

**Current behaviour:**

Equipping this item set and re-casting horn of winter does not grant the bonus effect of 3 runic power / 5s

**Expected behaviour:**

Should grant you 3 runic power every 5 seconds.

**Steps to reproduce the problem:**

1. Create a Death Knight.
2. Equip [this](https://cata-twinhead.twinstar.cz/?itemset=1000) itemset.
3. Cast Horn of Winter

**TC rev. hash/commit:** 
TrinityCore rev. d3dd36c77612e0ea8e979a5e8c58c72660d71ae5

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
973d4a139a831724063d916e259f1749b7f8d1ad
