### ISSUE TITLE
Talent - Force of Nature (Druid)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#92]
**Description:**

Casting Force of Nature summons a singular treant, **_not_** 3

**Current behaviour:**

Summons 1 treant instead of 3.

**Expected behaviour:**

Should summon 3 treants.

**Steps to reproduce the problem:**

1. Create a Druid.
2. Specialize down the tree of Balance
3. Cast Force of Nature

**TC rev. hash/commit:** 
TrinityCore rev. d3dd36c77612e0ea8e979a5e8c58c72660d71ae5

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by Ovahlord** [comment]
Wrong. They just follow you on the same position
![WoWScrnShot_051320_140456](https://user-images.githubusercontent.com/18347559/81810159-c719b980-9522-11ea-81bd-cd4a0327a14f.jpg)
