### ISSUE TITLE
Interface - Hiding Helmet and Cloak options do not save

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#94]
**Description:**

Game Menu -> Interface -> Display -> "Show Cloak", "Show Helm" If you uncheck these options they're working but when you logout and back in they go back to default and re-enable itself.

**Current behaviour:**

It works as intended but it re-enables on every login.

**Expected behaviour:**

It should be saving these options somewhere _locally_ or
 .... Database? (Not sure if it's actually suppose to go in _account_data.characters_ or _character_account_data.characters_)

**Steps to reproduce the problem:**

1. Create any char.
2. Disable these config/display options.
3. Relog and they're enabled again.

**TC rev. hash/commit:** 
TrinityCore rev. d3dd36c77612e0ea8e979a5e8c58c72660d71ae5

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by lingxDEV** [comment]
This is only a problem to the player self. After a relog, helm/cloak will still be hidden to other players.

Just thought I'd add this, not sure if it's help solving it.
