### ISSUE TITLE
Spell - Power Word: Shield (Priest)

### ISSUE THREAD

**Issue by Core002** [The-Cataclysm-Preservation-Project/TrinityCore#96]
**Description:**

Casting Power Word: Shield never gives the the selected target the Weakened Soul debuff, allowing players to cast this unlimited amount of times on the same target with only 3 second cooldown..

**Current behaviour:**

Power Word: Shield missing Weakened Soul debuff.

**Expected behaviour:**

Should cast Weakened Soul on the target of Power Word: Shield

**Steps to reproduce the problem:**

1. Create priest.
2. Cast Power Word: Shield on yourself or any other player.

**TC rev. hash/commit:** 
TrinityCore rev. d3dd36c77612e0ea8e979a5e8c58c72660d71ae5

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

**Comment by SpikeZ-WoW** [comment]
![WoWScrnShot_051420_220854](https://user-images.githubusercontent.com/47333860/81980858-ac813680-962f-11ea-9376-f180f8f37d40.jpg)

Uhm?
