### ISSUE TITLE
Retail Client is not detected by warden

### ISSUE THREAD

**Issue by Mayhem121** [The-Cataclysm-Preservation-Project/TrinityCore#98]
**Yes I have patched the client. Yes I can get ingame and play the server. However I just want to know if this is a known issue or not. If it's not, why are those errors being posted in the worldserver.exe?**

**Description:**

Every time I try to login with warden enabled, it shows prints this error in worldserver and closes the connection = 
`WorldSocket::HandleAuthSession: Client 127.0.0.1 attempted to log in using invalid client OS (Wn64).`
When I turn warden off, it logs me in fine, however when I create a new character it puts this in the worldserver.exe:
https://i.imgur.com/z4loj88.png
Are these errors a known problem with this source, or is there something I am missing?
Yes I am using a clean client, and it is patched

**Current behaviour:**
I am able to login game just fine, however on character creation this happens in worldserver: https://i.imgur.com/z4loj88.png and with warden it is unable to validate the original retail client that I have gotten off retail archives.

**Expected behaviour:**

Warden should validate the client

**Steps to reproduce the problem:**

1. Get your client.
I got mine from here: http://us.media.battle.net.edgesuite.net/downloads/wow-installers/live/WoWLive-64-Win-15595.zip

2. Log in-game

3. Make a new character and watch the world server

*WITH WARDEN*

1. Get your client.
I got mine from here: http://us.media.battle.net.edgesuite.net/downloads/wow-installers/live/WoWLive-64-Win-15595.zip

2. Try to login, you can't

**Yes I have patched the client. Yes I can get ingame and play the server. However I just want to know if this is a known issue or not. If it's not, where am I going wrong if I can play the game?**

**TC rev. hash/commit:** 
[55155d1](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/55155d1295983df6050e71fecd5be45f655a3cd8)

**TDB version:**  TDB 434.20021 - 2020/02/21

**Operating system:** WIN10 OS

**Comment by Core002** [comment]
With the latest revision and warden enabled, I'm still able to correctly start worldserver and login normally. 55155d1295983df6050e71fecd5be45f655a3cd8

**Comment by Mayhem121** [comment]
> With the latest revision and warden enabled, I'm still able to correctly start worldserver and login normally. [55155d1](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/55155d1295983df6050e71fecd5be45f655a3cd8)

Mind sharing your steps then?

**Comment by Core002** [comment]
Ah sorry, please also note I'm using a 32-bit client and not 64, even tho my OS is actually 64-bit i still use 32-bit client for overall compatibility issues. This may have something to do with it, i'll test it.

**Comment by Mayhem121** [comment]
> Ah sorry, please also note I'm using a 32-bit client and not 64, even tho my OS is actually 64-bit i still use 32-bit client for overall compatibility issues. This may have something to do with it, i'll test it.

Yes I am using the 64 bit client. I am unable to find the 32 bit one. Would you be able to share it where you got it, please?

**Comment by Ovahlord** [comment]
Warden is not supported for 4.x
